// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module denoiser_top_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        select_ln147_1,
        select_ln147,
        cmp23_i72_not_mid1364,
        cmp25_i74_not_mid1366,
        sext_ln162_1,
        d_address0,
        d_ce0,
        d_q0,
        d_address1,
        d_ce1,
        d_q1,
        s_V_18_out,
        s_V_18_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] select_ln147_1;
input  [4:0] select_ln147;
input  [0:0] cmp23_i72_not_mid1364;
input  [0:0] cmp25_i74_not_mid1366;
input  [8:0] sext_ln162_1;
output  [13:0] d_address0;
output   d_ce0;
input  [15:0] d_q0;
output  [13:0] d_address1;
output   d_ce1;
input  [15:0] d_q1;
output  [15:0] s_V_18_out;
output   s_V_18_out_ap_vld;

reg ap_idle;
reg d_ce0;
reg d_ce1;
reg s_V_18_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln153_reg_1110;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [5:0] conv_out_kernel_V_address0;
reg    conv_out_kernel_V_ce0;
wire  signed [10:0] conv_out_kernel_V_q0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln153_fu_424_p2;
reg   [0:0] icmp_ln153_reg_1110_pp0_iter1_reg;
wire   [0:0] select_ln155_2_fu_726_p3;
reg   [0:0] select_ln155_2_reg_1114;
wire   [5:0] add_ln163_3_fu_919_p2;
reg   [5:0] add_ln163_3_reg_1135;
wire    ap_block_pp0_stage1_11001;
wire   [15:0] val_V_10_fu_985_p3;
reg  signed [15:0] val_V_10_reg_1150;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln162_fu_838_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1271_fu_867_p1;
wire   [63:0] zext_ln162_1_fu_900_p1;
wire   [63:0] zext_ln1271_2_fu_992_p1;
wire    ap_block_pp0_stage1;
reg   [15:0] lhs_fu_124;
reg   [15:0] ap_sig_allocacmp_lhs_load_2;
wire    ap_loop_init;
reg   [2:0] k_fu_128;
wire   [2:0] add_ln157_fu_925_p2;
reg   [2:0] ap_sig_allocacmp_k_load;
reg   [1:0] j_fu_132;
wire   [1:0] select_ln155_1_fu_664_p3;
reg   [1:0] ap_sig_allocacmp_j_2;
reg   [3:0] indvar_flatten328_fu_136;
wire   [3:0] select_ln155_5_fu_937_p3;
reg   [3:0] ap_sig_allocacmp_indvar_flatten328_load;
reg   [1:0] i_fu_140;
wire   [1:0] select_ln153_8_fu_642_p3;
reg   [1:0] ap_sig_allocacmp_i_1;
reg   [4:0] indvar_flatten386_fu_144;
wire   [4:0] add_ln153_1_fu_430_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten386_load;
wire    ap_block_pp0_stage1_01001;
wire   [4:0] zext_ln153_fu_274_p1;
wire   [4:0] empty_fu_278_p2;
wire   [5:0] p_cast114_fu_284_p1;
wire   [3:0] p_shl2_fu_294_p3;
wire   [4:0] p_shl30_cast_fu_302_p1;
wire   [5:0] empty_64_fu_288_p2;
wire   [10:0] shl_ln162_2_fu_332_p3;
wire   [13:0] shl_ln162_1_fu_324_p3;
wire  signed [13:0] sext_ln162_fu_340_p1;
wire   [4:0] zext_ln155_fu_350_p1;
wire   [4:0] empty_66_fu_354_p2;
wire   [5:0] p_cast125_fu_360_p1;
wire   [5:0] empty_67_fu_364_p2;
wire   [0:0] cmp21_i70_not_fu_318_p2;
wire   [0:0] cmp23_i72_not_fu_370_p2;
wire   [0:0] cmp20_i68_not_fu_312_p2;
wire   [0:0] cmp25_i74_not_fu_376_p2;
wire   [0:0] tmp60_fu_388_p2;
wire   [0:0] tmp59_fu_382_p2;
wire   [8:0] shl_ln4_fu_400_p3;
wire  signed [13:0] sext_ln162_2_fu_408_p1;
wire   [13:0] sub_ln162_fu_344_p2;
wire   [4:0] empty_65_fu_306_p2;
wire   [0:0] icmp_ln155_fu_448_p2;
wire   [1:0] add_ln153_fu_442_p2;
wire   [4:0] zext_ln153_1_fu_470_p1;
wire   [4:0] p_mid1346_fu_474_p2;
wire   [5:0] p_cast114_mid1_fu_480_p1;
wire   [3:0] p_shl30_mid1_fu_490_p3;
wire   [4:0] p_shl30_cast_mid1_fu_498_p1;
wire   [4:0] p_mid1350_fu_502_p2;
wire  signed [4:0] select_ln153_2_fu_508_p3;
wire   [0:0] cmp20_i68_not_mid1_fu_520_p2;
wire   [5:0] p_mid1348_fu_484_p2;
wire   [0:0] cmp21_i70_not_mid1_fu_534_p2;
wire   [10:0] shl_ln162_2_mid1_fu_556_p3;
wire   [13:0] shl_ln162_1_mid1_fu_548_p3;
wire  signed [13:0] sext_ln162_3_fu_564_p1;
wire   [13:0] sub_ln162_1_fu_568_p2;
wire   [0:0] tmp60_mid1370_fu_588_p2;
wire   [0:0] tmp59_mid1368_fu_582_p2;
wire   [0:0] brmerge98_mid1372_fu_594_p2;
wire   [0:0] brmerge98_fu_394_p2;
wire  signed [13:0] sext_ln162_1_cast_fu_231_p1;
wire   [4:0] add_ln163_2_fu_418_p2;
wire   [0:0] tmp_fu_622_p3;
wire   [0:0] xor_ln157_fu_630_p2;
wire   [1:0] select_ln153_fu_454_p3;
wire   [0:0] or_ln153_fu_636_p2;
wire   [2:0] select_ln153_1_fu_462_p3;
wire   [1:0] add_ln155_fu_650_p2;
wire   [4:0] zext_ln155_2_fu_676_p1;
wire   [4:0] p_mid1324_fu_680_p2;
wire   [5:0] p_cast125_mid1_fu_686_p1;
wire   [5:0] p_mid1326_fu_690_p2;
wire   [0:0] select_ln153_4_fu_540_p3;
wire   [0:0] cmp23_i72_not_mid1_fu_696_p2;
wire   [0:0] select_ln153_3_fu_526_p3;
wire   [0:0] cmp25_i74_not_mid1_fu_702_p2;
wire   [0:0] tmp60_mid1_fu_714_p2;
wire   [0:0] tmp59_mid1_fu_708_p2;
wire   [0:0] select_ln153_6_fu_600_p3;
wire   [0:0] brmerge98_mid1_fu_720_p2;
wire   [8:0] shl_ln162_mid1_fu_734_p3;
wire  signed [13:0] sext_ln162_4_fu_742_p1;
wire   [13:0] select_ln153_5_fu_574_p3;
wire   [4:0] select_ln153_7_fu_614_p3;
wire   [4:0] add_ln163_4_fu_752_p2;
wire   [4:0] select_ln155_3_fu_758_p3;
wire   [2:0] select_ln155_fu_656_p3;
wire   [13:0] add_ln162_1_fu_608_p2;
wire   [13:0] add_ln162_fu_412_p2;
wire   [10:0] tmp_s_fu_780_p4;
wire   [10:0] tmp_1_fu_790_p4;
wire   [13:0] add_ln162_2_fu_746_p2;
wire   [10:0] select_ln153_9_fu_800_p3;
wire   [10:0] tmp_2_fu_808_p4;
wire   [10:0] select_ln155_4_fu_818_p3;
wire   [1:0] trunc_ln162_fu_770_p1;
wire   [12:0] trunc_ln_fu_826_p3;
wire  signed [13:0] sext_ln162_5_fu_834_p1;
wire   [4:0] add_ln163_5_fu_843_p3;
wire  signed [5:0] sext_ln153_fu_516_p1;
wire   [5:0] zext_ln163_fu_851_p1;
wire   [5:0] add_ln163_fu_855_p2;
wire   [5:0] zext_ln155_1_fu_672_p1;
wire   [5:0] add_ln163_1_fu_861_p2;
wire   [2:0] shl_ln162_fu_774_p2;
wire   [2:0] or_ln162_fu_872_p2;
wire   [1:0] tmp_3_fu_878_p4;
wire   [12:0] trunc_ln162_1_fu_888_p3;
wire  signed [13:0] sext_ln162_6_fu_896_p1;
wire   [4:0] or_ln163_fu_905_p2;
wire   [5:0] or_ln2_fu_911_p3;
wire  signed [5:0] sext_ln155_fu_766_p1;
wire   [3:0] add_ln155_1_fu_931_p2;
wire  signed [15:0] val_V_9_fu_970_p3;
wire  signed [25:0] tmp_4_fu_1014_p1;
wire   [25:0] grp_fu_1049_p3;
wire   [15:0] tmp_4_fu_1014_p4;
wire  signed [25:0] s_V_fu_1031_p1;
wire   [25:0] grp_fu_1058_p3;
wire   [25:0] grp_fu_1049_p2;
wire   [25:0] grp_fu_1058_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

denoiser_top_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_conv_out_kernel_V_ROM_bkb #(
    .DataWidth( 11 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
conv_out_kernel_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv_out_kernel_V_address0),
    .ce0(conv_out_kernel_V_ce0),
    .q0(conv_out_kernel_V_q0)
);

denoiser_top_mac_muladd_11s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_11s_16s_26ns_26_4_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv_out_kernel_V_q0),
    .din1(val_V_9_fu_970_p3),
    .din2(grp_fu_1049_p2),
    .ce(1'b1),
    .dout(grp_fu_1049_p3)
);

denoiser_top_mac_muladd_11s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_11s_16s_26ns_26_4_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv_out_kernel_V_q0),
    .din1(val_V_10_reg_1150),
    .din2(grp_fu_1058_p2),
    .ce(1'b1),
    .dout(grp_fu_1058_p3)
);

denoiser_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln153_fu_424_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_140 <= select_ln153_8_fu_642_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_140 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln153_fu_424_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten328_fu_136 <= select_ln155_5_fu_937_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten328_fu_136 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln153_fu_424_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten386_fu_144 <= add_ln153_1_fu_430_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten386_fu_144 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln153_fu_424_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_132 <= select_ln155_1_fu_664_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_132 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln153_fu_424_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_128 <= add_ln157_fu_925_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_128 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        lhs_fu_124 <= 16'd65335;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        lhs_fu_124 <= {{s_V_fu_1031_p1[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln153_fu_424_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln163_3_reg_1135 <= add_ln163_3_fu_919_p2;
        select_ln155_2_reg_1114 <= select_ln155_2_fu_726_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln153_reg_1110 <= icmp_ln153_fu_424_p2;
        icmp_ln153_reg_1110_pp0_iter1_reg <= icmp_ln153_reg_1110;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln153_reg_1110 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        val_V_10_reg_1150 <= val_V_10_fu_985_p3;
    end
end

always @ (*) begin
    if (((icmp_ln153_reg_1110 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_140;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten328_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten328_load = indvar_flatten328_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten386_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten386_load = indvar_flatten386_fu_144;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_2 = 2'd0;
    end else begin
        ap_sig_allocacmp_j_2 = j_fu_132;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_load = 3'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_lhs_load_2 = {{s_V_fu_1031_p1[25:10]}};
    end else begin
        ap_sig_allocacmp_lhs_load_2 = lhs_fu_124;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            conv_out_kernel_V_address0 = zext_ln1271_2_fu_992_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            conv_out_kernel_V_address0 = zext_ln1271_fu_867_p1;
        end else begin
            conv_out_kernel_V_address0 = 'bx;
        end
    end else begin
        conv_out_kernel_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        conv_out_kernel_V_ce0 = 1'b1;
    end else begin
        conv_out_kernel_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_ce0 = 1'b1;
    end else begin
        d_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_ce1 = 1'b1;
    end else begin
        d_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln153_reg_1110_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s_V_18_out_ap_vld = 1'b1;
    end else begin
        s_V_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln153_1_fu_430_p2 = (ap_sig_allocacmp_indvar_flatten386_load + 5'd1);

assign add_ln153_fu_442_p2 = (ap_sig_allocacmp_i_1 + 2'd1);

assign add_ln155_1_fu_931_p2 = (ap_sig_allocacmp_indvar_flatten328_load + 4'd1);

assign add_ln155_fu_650_p2 = (select_ln153_fu_454_p3 + 2'd1);

assign add_ln157_fu_925_p2 = (select_ln155_fu_656_p3 + 3'd2);

assign add_ln162_1_fu_608_p2 = ($signed(sext_ln162_1_cast_fu_231_p1) + $signed(sub_ln162_1_fu_568_p2));

assign add_ln162_2_fu_746_p2 = ($signed(sext_ln162_4_fu_742_p1) + $signed(select_ln153_5_fu_574_p3));

assign add_ln162_fu_412_p2 = ($signed(sext_ln162_2_fu_408_p1) + $signed(sub_ln162_fu_344_p2));

assign add_ln163_1_fu_861_p2 = (add_ln163_fu_855_p2 + zext_ln155_1_fu_672_p1);

assign add_ln163_2_fu_418_p2 = (empty_65_fu_306_p2 + zext_ln155_fu_350_p1);

assign add_ln163_3_fu_919_p2 = ($signed(or_ln2_fu_911_p3) + $signed(sext_ln155_fu_766_p1));

assign add_ln163_4_fu_752_p2 = ($signed(select_ln153_2_fu_508_p3) + $signed(zext_ln155_2_fu_676_p1));

assign add_ln163_5_fu_843_p3 = {{trunc_ln162_fu_770_p1}, {select_ln155_fu_656_p3}};

assign add_ln163_fu_855_p2 = ($signed(sext_ln153_fu_516_p1) + $signed(zext_ln163_fu_851_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign brmerge98_fu_394_p2 = (tmp60_fu_388_p2 | tmp59_fu_382_p2);

assign brmerge98_mid1372_fu_594_p2 = (tmp60_mid1370_fu_588_p2 | tmp59_mid1368_fu_582_p2);

assign brmerge98_mid1_fu_720_p2 = (tmp60_mid1_fu_714_p2 | tmp59_mid1_fu_708_p2);

assign cmp20_i68_not_fu_312_p2 = ((empty_fu_278_p2 == 5'd0) ? 1'b1 : 1'b0);

assign cmp20_i68_not_mid1_fu_520_p2 = ((p_mid1346_fu_474_p2 == 5'd0) ? 1'b1 : 1'b0);

assign cmp21_i70_not_fu_318_p2 = (($signed(empty_64_fu_288_p2) > $signed(6'd27)) ? 1'b1 : 1'b0);

assign cmp21_i70_not_mid1_fu_534_p2 = (($signed(p_mid1348_fu_484_p2) > $signed(6'd27)) ? 1'b1 : 1'b0);

assign cmp23_i72_not_fu_370_p2 = ((empty_66_fu_354_p2 == 5'd0) ? 1'b1 : 1'b0);

assign cmp23_i72_not_mid1_fu_696_p2 = ((p_mid1324_fu_680_p2 == 5'd0) ? 1'b1 : 1'b0);

assign cmp25_i74_not_fu_376_p2 = (($signed(empty_67_fu_364_p2) > $signed(6'd27)) ? 1'b1 : 1'b0);

assign cmp25_i74_not_mid1_fu_702_p2 = (($signed(p_mid1326_fu_690_p2) > $signed(6'd27)) ? 1'b1 : 1'b0);

assign d_address0 = zext_ln162_1_fu_900_p1;

assign d_address1 = zext_ln162_fu_838_p1;

assign empty_64_fu_288_p2 = ($signed(p_cast114_fu_284_p1) + $signed(6'd63));

assign empty_65_fu_306_p2 = (p_shl30_cast_fu_302_p1 - zext_ln153_fu_274_p1);

assign empty_66_fu_354_p2 = (zext_ln155_fu_350_p1 + select_ln147);

assign empty_67_fu_364_p2 = ($signed(p_cast125_fu_360_p1) + $signed(6'd63));

assign empty_fu_278_p2 = (zext_ln153_fu_274_p1 + select_ln147_1);

assign grp_fu_1049_p2 = {{ap_sig_allocacmp_lhs_load_2}, {10'd0}};

assign grp_fu_1058_p2 = {{tmp_4_fu_1014_p4}, {10'd0}};

assign icmp_ln153_fu_424_p2 = ((ap_sig_allocacmp_indvar_flatten386_load == 5'd18) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_448_p2 = ((ap_sig_allocacmp_indvar_flatten328_load == 4'd6) ? 1'b1 : 1'b0);

assign or_ln153_fu_636_p2 = (xor_ln157_fu_630_p2 | icmp_ln155_fu_448_p2);

assign or_ln162_fu_872_p2 = (shl_ln162_fu_774_p2 | 3'd2);

assign or_ln163_fu_905_p2 = (5'd9 | add_ln163_5_fu_843_p3);

assign or_ln2_fu_911_p3 = {{1'd0}, {or_ln163_fu_905_p2}};

assign p_cast114_fu_284_p1 = empty_fu_278_p2;

assign p_cast114_mid1_fu_480_p1 = p_mid1346_fu_474_p2;

assign p_cast125_fu_360_p1 = empty_66_fu_354_p2;

assign p_cast125_mid1_fu_686_p1 = p_mid1324_fu_680_p2;

assign p_mid1324_fu_680_p2 = (zext_ln155_2_fu_676_p1 + select_ln147);

assign p_mid1326_fu_690_p2 = ($signed(p_cast125_mid1_fu_686_p1) + $signed(6'd63));

assign p_mid1346_fu_474_p2 = (zext_ln153_1_fu_470_p1 + select_ln147_1);

assign p_mid1348_fu_484_p2 = ($signed(p_cast114_mid1_fu_480_p1) + $signed(6'd63));

assign p_mid1350_fu_502_p2 = (p_shl30_cast_mid1_fu_498_p1 - zext_ln153_1_fu_470_p1);

assign p_shl2_fu_294_p3 = {{ap_sig_allocacmp_i_1}, {2'd0}};

assign p_shl30_cast_fu_302_p1 = p_shl2_fu_294_p3;

assign p_shl30_cast_mid1_fu_498_p1 = p_shl30_mid1_fu_490_p3;

assign p_shl30_mid1_fu_490_p3 = {{add_ln153_fu_442_p2}, {2'd0}};

assign s_V_18_out = lhs_fu_124;

assign s_V_fu_1031_p1 = grp_fu_1058_p3;

assign select_ln153_1_fu_462_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_k_load);

assign select_ln153_2_fu_508_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? p_mid1350_fu_502_p2 : empty_65_fu_306_p2);

assign select_ln153_3_fu_526_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? cmp20_i68_not_mid1_fu_520_p2 : cmp20_i68_not_fu_312_p2);

assign select_ln153_4_fu_540_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? cmp21_i70_not_mid1_fu_534_p2 : cmp21_i70_not_fu_318_p2);

assign select_ln153_5_fu_574_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? sub_ln162_1_fu_568_p2 : sub_ln162_fu_344_p2);

assign select_ln153_6_fu_600_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? brmerge98_mid1372_fu_594_p2 : brmerge98_fu_394_p2);

assign select_ln153_7_fu_614_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? p_mid1350_fu_502_p2 : add_ln163_2_fu_418_p2);

assign select_ln153_8_fu_642_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? add_ln153_fu_442_p2 : ap_sig_allocacmp_i_1);

assign select_ln153_9_fu_800_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? tmp_s_fu_780_p4 : tmp_1_fu_790_p4);

assign select_ln153_fu_454_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j_2);

assign select_ln155_1_fu_664_p3 = ((or_ln153_fu_636_p2[0:0] == 1'b1) ? select_ln153_fu_454_p3 : add_ln155_fu_650_p2);

assign select_ln155_2_fu_726_p3 = ((or_ln153_fu_636_p2[0:0] == 1'b1) ? select_ln153_6_fu_600_p3 : brmerge98_mid1_fu_720_p2);

assign select_ln155_3_fu_758_p3 = ((or_ln153_fu_636_p2[0:0] == 1'b1) ? select_ln153_7_fu_614_p3 : add_ln163_4_fu_752_p2);

assign select_ln155_4_fu_818_p3 = ((or_ln153_fu_636_p2[0:0] == 1'b1) ? select_ln153_9_fu_800_p3 : tmp_2_fu_808_p4);

assign select_ln155_5_fu_937_p3 = ((icmp_ln155_fu_448_p2[0:0] == 1'b1) ? 4'd1 : add_ln155_1_fu_931_p2);

assign select_ln155_fu_656_p3 = ((or_ln153_fu_636_p2[0:0] == 1'b1) ? select_ln153_1_fu_462_p3 : 3'd0);

assign sext_ln153_fu_516_p1 = select_ln153_2_fu_508_p3;

assign sext_ln155_fu_766_p1 = $signed(select_ln155_3_fu_758_p3);

assign sext_ln162_1_cast_fu_231_p1 = $signed(sext_ln162_1);

assign sext_ln162_2_fu_408_p1 = $signed(shl_ln4_fu_400_p3);

assign sext_ln162_3_fu_564_p1 = $signed(shl_ln162_2_mid1_fu_556_p3);

assign sext_ln162_4_fu_742_p1 = $signed(shl_ln162_mid1_fu_734_p3);

assign sext_ln162_5_fu_834_p1 = $signed(trunc_ln_fu_826_p3);

assign sext_ln162_6_fu_896_p1 = $signed(trunc_ln162_1_fu_888_p3);

assign sext_ln162_fu_340_p1 = $signed(shl_ln162_2_fu_332_p3);

assign shl_ln162_1_fu_324_p3 = {{empty_64_fu_288_p2}, {8'd0}};

assign shl_ln162_1_mid1_fu_548_p3 = {{p_mid1348_fu_484_p2}, {8'd0}};

assign shl_ln162_2_fu_332_p3 = {{empty_64_fu_288_p2}, {5'd0}};

assign shl_ln162_2_mid1_fu_556_p3 = {{p_mid1348_fu_484_p2}, {5'd0}};

assign shl_ln162_fu_774_p2 = select_ln155_fu_656_p3 << 3'd1;

assign shl_ln162_mid1_fu_734_p3 = {{p_mid1326_fu_690_p2}, {3'd0}};

assign shl_ln4_fu_400_p3 = {{empty_67_fu_364_p2}, {3'd0}};

assign sub_ln162_1_fu_568_p2 = ($signed(shl_ln162_1_mid1_fu_548_p3) - $signed(sext_ln162_3_fu_564_p1));

assign sub_ln162_fu_344_p2 = ($signed(shl_ln162_1_fu_324_p3) - $signed(sext_ln162_fu_340_p1));

assign tmp59_fu_382_p2 = (cmp23_i72_not_fu_370_p2 | cmp21_i70_not_fu_318_p2);

assign tmp59_mid1368_fu_582_p2 = (cmp23_i72_not_mid1364 | cmp21_i70_not_mid1_fu_534_p2);

assign tmp59_mid1_fu_708_p2 = (select_ln153_4_fu_540_p3 | cmp23_i72_not_mid1_fu_696_p2);

assign tmp60_fu_388_p2 = (cmp25_i74_not_fu_376_p2 | cmp20_i68_not_fu_312_p2);

assign tmp60_mid1370_fu_588_p2 = (cmp25_i74_not_mid1366 | cmp20_i68_not_mid1_fu_520_p2);

assign tmp60_mid1_fu_714_p2 = (select_ln153_3_fu_526_p3 | cmp25_i74_not_mid1_fu_702_p2);

assign tmp_1_fu_790_p4 = {{add_ln162_fu_412_p2[13:3]}};

assign tmp_2_fu_808_p4 = {{add_ln162_2_fu_746_p2[13:3]}};

assign tmp_3_fu_878_p4 = {{or_ln162_fu_872_p2[2:1]}};

assign tmp_4_fu_1014_p1 = grp_fu_1049_p3;

assign tmp_4_fu_1014_p4 = {{tmp_4_fu_1014_p1[25:10]}};

assign tmp_fu_622_p3 = ap_sig_allocacmp_k_load[32'd2];

assign tmp_s_fu_780_p4 = {{add_ln162_1_fu_608_p2[13:3]}};

assign trunc_ln162_1_fu_888_p3 = {{select_ln155_4_fu_818_p3}, {tmp_3_fu_878_p4}};

assign trunc_ln162_fu_770_p1 = select_ln155_fu_656_p3[1:0];

assign trunc_ln_fu_826_p3 = {{select_ln155_4_fu_818_p3}, {trunc_ln162_fu_770_p1}};

assign val_V_10_fu_985_p3 = ((select_ln155_2_reg_1114[0:0] == 1'b1) ? 16'd0 : d_q0);

assign val_V_9_fu_970_p3 = ((select_ln155_2_reg_1114[0:0] == 1'b1) ? 16'd0 : d_q1);

assign xor_ln157_fu_630_p2 = (tmp_fu_622_p3 ^ 1'd1);

assign zext_ln1271_2_fu_992_p1 = add_ln163_3_reg_1135;

assign zext_ln1271_fu_867_p1 = add_ln163_1_fu_861_p2;

assign zext_ln153_1_fu_470_p1 = add_ln153_fu_442_p2;

assign zext_ln153_fu_274_p1 = ap_sig_allocacmp_i_1;

assign zext_ln155_1_fu_672_p1 = select_ln155_1_fu_664_p3;

assign zext_ln155_2_fu_676_p1 = add_ln155_fu_650_p2;

assign zext_ln155_fu_350_p1 = ap_sig_allocacmp_j_2;

assign zext_ln162_1_fu_900_p1 = $unsigned(sext_ln162_6_fu_896_p1);

assign zext_ln162_fu_838_p1 = $unsigned(sext_ln162_5_fu_834_p1);

assign zext_ln163_fu_851_p1 = add_ln163_5_fu_843_p3;

endmodule //denoiser_top_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out
