// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module denoiser_top_inference (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d_address0,
        d_ce0,
        d_we0,
        d_d0,
        d_q0,
        d_address1,
        d_ce1,
        d_q1,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        input_r_address1,
        input_r_ce1,
        input_r_q1,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 58'd1;
parameter    ap_ST_fsm_state2 = 58'd2;
parameter    ap_ST_fsm_state3 = 58'd4;
parameter    ap_ST_fsm_state4 = 58'd8;
parameter    ap_ST_fsm_state5 = 58'd16;
parameter    ap_ST_fsm_state6 = 58'd32;
parameter    ap_ST_fsm_state7 = 58'd64;
parameter    ap_ST_fsm_state8 = 58'd128;
parameter    ap_ST_fsm_state9 = 58'd256;
parameter    ap_ST_fsm_state10 = 58'd512;
parameter    ap_ST_fsm_state11 = 58'd1024;
parameter    ap_ST_fsm_state12 = 58'd2048;
parameter    ap_ST_fsm_state13 = 58'd4096;
parameter    ap_ST_fsm_state14 = 58'd8192;
parameter    ap_ST_fsm_state15 = 58'd16384;
parameter    ap_ST_fsm_state16 = 58'd32768;
parameter    ap_ST_fsm_state17 = 58'd65536;
parameter    ap_ST_fsm_state18 = 58'd131072;
parameter    ap_ST_fsm_state19 = 58'd262144;
parameter    ap_ST_fsm_state20 = 58'd524288;
parameter    ap_ST_fsm_state21 = 58'd1048576;
parameter    ap_ST_fsm_state22 = 58'd2097152;
parameter    ap_ST_fsm_state23 = 58'd4194304;
parameter    ap_ST_fsm_state24 = 58'd8388608;
parameter    ap_ST_fsm_state25 = 58'd16777216;
parameter    ap_ST_fsm_state26 = 58'd33554432;
parameter    ap_ST_fsm_state27 = 58'd67108864;
parameter    ap_ST_fsm_state28 = 58'd134217728;
parameter    ap_ST_fsm_state29 = 58'd268435456;
parameter    ap_ST_fsm_state30 = 58'd536870912;
parameter    ap_ST_fsm_state31 = 58'd1073741824;
parameter    ap_ST_fsm_state32 = 58'd2147483648;
parameter    ap_ST_fsm_state33 = 58'd4294967296;
parameter    ap_ST_fsm_state34 = 58'd8589934592;
parameter    ap_ST_fsm_state35 = 58'd17179869184;
parameter    ap_ST_fsm_state36 = 58'd34359738368;
parameter    ap_ST_fsm_state37 = 58'd68719476736;
parameter    ap_ST_fsm_state38 = 58'd137438953472;
parameter    ap_ST_fsm_state39 = 58'd274877906944;
parameter    ap_ST_fsm_state40 = 58'd549755813888;
parameter    ap_ST_fsm_state41 = 58'd1099511627776;
parameter    ap_ST_fsm_state42 = 58'd2199023255552;
parameter    ap_ST_fsm_state43 = 58'd4398046511104;
parameter    ap_ST_fsm_state44 = 58'd8796093022208;
parameter    ap_ST_fsm_state45 = 58'd17592186044416;
parameter    ap_ST_fsm_state46 = 58'd35184372088832;
parameter    ap_ST_fsm_state47 = 58'd70368744177664;
parameter    ap_ST_fsm_state48 = 58'd140737488355328;
parameter    ap_ST_fsm_state49 = 58'd281474976710656;
parameter    ap_ST_fsm_state50 = 58'd562949953421312;
parameter    ap_ST_fsm_state51 = 58'd1125899906842624;
parameter    ap_ST_fsm_state52 = 58'd2251799813685248;
parameter    ap_ST_fsm_state53 = 58'd4503599627370496;
parameter    ap_ST_fsm_state54 = 58'd9007199254740992;
parameter    ap_ST_fsm_state55 = 58'd18014398509481984;
parameter    ap_ST_fsm_state56 = 58'd36028797018963968;
parameter    ap_ST_fsm_state57 = 58'd72057594037927936;
parameter    ap_ST_fsm_state58 = 58'd144115188075855872;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] d_address0;
output   d_ce0;
output  [1:0] d_we0;
output  [15:0] d_d0;
input  [15:0] d_q0;
output  [13:0] d_address1;
output   d_ce1;
input  [15:0] d_q1;
output  [9:0] input_r_address0;
output   input_r_ce0;
input  [15:0] input_r_q0;
output  [9:0] input_r_address1;
output   input_r_ce1;
input  [15:0] input_r_q1;
output  [9:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [15:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] d_address0;
reg d_ce0;
reg[1:0] d_we0;
reg[15:0] d_d0;
reg[13:0] d_address1;
reg d_ce1;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [57:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] conv2_bias_V_address0;
reg    conv2_bias_V_ce0;
wire   [9:0] conv2_bias_V_q0;
wire   [7:0] f_x_msb_2_table_V_address0;
reg    f_x_msb_2_table_V_ce0;
wire   [45:0] f_x_msb_2_table_V_q0;
wire   [7:0] exp_x_msb_1_table_V_address0;
reg    exp_x_msb_1_table_V_ce0;
wire   [49:0] exp_x_msb_1_table_V_q0;
wire   [11:0] add_ln17_1_fu_642_p2;
reg   [11:0] add_ln17_1_reg_2405;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln19_fu_657_p2;
reg   [0:0] icmp_ln19_reg_2410;
wire   [0:0] icmp_ln17_fu_636_p2;
wire   [2:0] select_ln17_1_fu_671_p3;
reg   [2:0] select_ln17_1_reg_2415;
wire   [4:0] zext_ln17_fu_679_p1;
reg   [4:0] zext_ln17_reg_2420;
wire   [1:0] trunc_ln17_fu_687_p1;
reg   [1:0] trunc_ln17_reg_2425;
wire   [5:0] zext_ln17_1_fu_699_p1;
reg   [5:0] zext_ln17_1_reg_2430;
wire   [15:0] select_ln17_2_fu_717_p3;
wire   [4:0] select_ln19_fu_763_p3;
reg   [4:0] select_ln19_reg_2440;
wire   [13:0] select_ln19_1_fu_801_p3;
reg   [13:0] select_ln19_1_reg_2447;
wire   [4:0] select_ln19_2_fu_809_p3;
reg   [4:0] select_ln19_2_reg_2452;
wire   [5:0] add_ln30_fu_821_p2;
reg   [5:0] add_ln30_reg_2458;
wire   [1:0] add_ln25_fu_858_p2;
reg   [1:0] add_ln25_reg_2501;
wire    ap_CS_fsm_state3;
wire   [9:0] sub_ln32_fu_907_p2;
reg   [9:0] sub_ln32_reg_2506;
wire   [0:0] icmp_ln25_fu_852_p2;
wire   [5:0] empty_85_fu_941_p2;
reg   [5:0] empty_85_reg_2511;
wire   [0:0] brmerge_not_fu_959_p2;
reg   [0:0] brmerge_not_reg_2516;
wire   [0:0] grp_inference_Pipeline_loop_kw_1_fu_481_ap_return;
reg   [0:0] targetBlock_reg_2521;
wire    ap_CS_fsm_state4;
wire   [15:0] s_V_3_fu_1071_p3;
wire    ap_CS_fsm_state5;
wire   [7:0] select_ln66_1_fu_1183_p3;
reg   [7:0] select_ln66_1_reg_2534;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln66_fu_1131_p2;
wire   [3:0] select_ln68_fu_1246_p3;
reg   [3:0] select_ln68_reg_2544;
wire   [3:0] select_ln68_2_fu_1292_p3;
reg   [3:0] select_ln68_2_reg_2551;
reg   [11:0] trunc_ln7_reg_2556;
reg   [9:0] conv2_bias_V_load_reg_2596;
wire    ap_CS_fsm_state8;
wire   [0:0] cmp27_i_not_mid1115_fu_1409_p2;
reg   [0:0] cmp27_i_not_mid1115_reg_2601;
wire   [0:0] cmp29_i_not_mid1117_fu_1415_p2;
reg   [0:0] cmp29_i_not_mid1117_reg_2606;
wire   [12:0] add_ln83_2_fu_1434_p2;
reg   [12:0] add_ln83_2_reg_2611;
wire   [7:0] select_ln115_1_fu_1598_p3;
reg   [7:0] select_ln115_1_reg_2619;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln115_fu_1544_p2;
wire   [15:0] select_ln115_2_fu_1620_p3;
reg   [15:0] select_ln115_2_reg_2624;
wire   [4:0] select_ln117_fu_1678_p3;
reg   [4:0] select_ln117_reg_2629;
wire   [4:0] select_ln117_2_fu_1724_p3;
reg   [4:0] select_ln117_2_reg_2636;
reg   [12:0] trunc_ln8_reg_2641;
wire   [0:0] cmp27_i431_not_mid1258_fu_1831_p2;
reg   [0:0] cmp27_i431_not_mid1258_reg_2667;
wire    ap_CS_fsm_state13;
wire   [0:0] cmp29_i433_not_mid1260_fu_1837_p2;
reg   [0:0] cmp29_i433_not_mid1260_reg_2672;
wire   [12:0] add_ln132_2_fu_1856_p2;
reg   [12:0] add_ln132_2_reg_2677;
wire   [0:0] icmp_ln149_fu_1915_p2;
reg   [0:0] icmp_ln149_reg_2685;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln147_fu_1900_p2;
wire   [4:0] select_ln147_fu_1921_p3;
reg   [4:0] select_ln147_reg_2690;
wire   [4:0] select_ln147_1_fu_1954_p3;
reg   [4:0] select_ln147_1_reg_2698;
wire    ap_CS_fsm_state17;
wire   [0:0] cmp23_i72_not_mid1364_fu_1971_p2;
reg   [0:0] cmp23_i72_not_mid1364_reg_2705;
wire   [0:0] cmp25_i74_not_mid1366_fu_1977_p2;
reg   [0:0] cmp25_i74_not_mid1366_reg_2710;
wire   [8:0] shl_ln162_mid_fu_1984_p3;
reg   [8:0] shl_ln162_mid_reg_2715;
wire   [7:0] tmp_15_fu_2079_p4;
reg   [7:0] tmp_15_reg_2720;
wire    ap_CS_fsm_state19;
reg   [49:0] exp_x_msb_1_V_reg_2735;
wire    ap_CS_fsm_state20;
reg   [47:0] trunc_ln813_1_reg_2740;
wire    ap_CS_fsm_state21;
wire    grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_start;
wire    grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_done;
wire    grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_idle;
wire    grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_ready;
wire   [13:0] grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_ce0;
wire   [1:0] grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_we0;
wire   [15:0] grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_d0;
wire   [13:0] grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_ce1;
wire    grp_inference_Pipeline_loop_kw_1_fu_481_ap_start;
wire    grp_inference_Pipeline_loop_kw_1_fu_481_ap_done;
wire    grp_inference_Pipeline_loop_kw_1_fu_481_ap_idle;
wire    grp_inference_Pipeline_loop_kw_1_fu_481_ap_ready;
wire   [9:0] grp_inference_Pipeline_loop_kw_1_fu_481_input_r_address0;
wire    grp_inference_Pipeline_loop_kw_1_fu_481_input_r_ce0;
wire   [9:0] grp_inference_Pipeline_loop_kw_1_fu_481_input_r_address1;
wire    grp_inference_Pipeline_loop_kw_1_fu_481_input_r_ce1;
wire   [15:0] grp_inference_Pipeline_loop_kw_1_fu_481_s_V_13_out;
wire    grp_inference_Pipeline_loop_kw_1_fu_481_s_V_13_out_ap_vld;
wire   [15:0] grp_inference_Pipeline_loop_kw_1_fu_481_s_V_14_out;
wire    grp_inference_Pipeline_loop_kw_1_fu_481_s_V_14_out_ap_vld;
wire    grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_start;
wire    grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_done;
wire    grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_idle;
wire    grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_ready;
wire   [13:0] grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_ce0;
wire   [1:0] grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_we0;
wire   [15:0] grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_d0;
wire    grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_start;
wire    grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_done;
wire    grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_idle;
wire    grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_ready;
wire   [13:0] grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_address0;
wire    grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_ce0;
wire   [13:0] grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_address1;
wire    grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_ce1;
wire   [15:0] grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_s_V_15_out;
wire    grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_s_V_15_out_ap_vld;
wire    grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_start;
wire    grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_done;
wire    grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_idle;
wire    grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_ready;
wire   [13:0] grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_address0;
wire    grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_ce0;
wire   [13:0] grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_address1;
wire    grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_ce1;
wire   [15:0] grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_s_V_16_out;
wire    grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_s_V_16_out_ap_vld;
wire    grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_start;
wire    grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_done;
wire    grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_idle;
wire    grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_ready;
wire   [13:0] grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_address0;
wire    grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_ce0;
wire   [13:0] grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_address1;
wire    grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_ce1;
wire   [15:0] grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_s_V_18_out;
wire    grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_s_V_18_out_ap_vld;
reg   [1:0] i_reg_454;
reg   [15:0] s_V_1_reg_465;
reg    grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_inference_Pipeline_loop_kw_1_fu_481_ap_start_reg;
reg   [15:0] s_V_13_loc_fu_320;
reg   [15:0] s_V_14_loc_fu_316;
reg    grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_start_reg;
wire    ap_CS_fsm_state18;
wire   [63:0] zext_ln36_6_fu_1020_p1;
wire   [63:0] zext_ln66_fu_1199_p1;
wire   [63:0] zext_ln88_6_fu_1470_p1;
wire    ap_CS_fsm_state10;
wire   [63:0] zext_ln137_6_fu_1892_p1;
wire    ap_CS_fsm_state15;
wire   [63:0] zext_ln541_fu_2089_p1;
wire   [63:0] zext_ln541_1_fu_2094_p1;
wire   [63:0] zext_ln167_2_fu_2321_p1;
wire    ap_CS_fsm_state58;
reg   [4:0] y_fu_284;
wire   [4:0] add_ln21_fu_1025_p2;
reg   [4:0] x_fu_288;
reg   [9:0] indvar_flatten_fu_292;
wire   [9:0] select_ln19_3_fu_1036_p3;
reg   [2:0] n_fu_296;
reg   [11:0] indvar_flatten25_fu_300;
reg   [3:0] y_1_fu_324;
wire   [3:0] add_ln70_fu_1330_p2;
reg   [3:0] x_1_fu_328;
reg   [7:0] indvar_flatten144_fu_332;
wire   [7:0] select_ln68_3_fu_1342_p3;
reg   [3:0] n_1_fu_336;
wire   [3:0] select_ln66_2_fu_1191_p3;
reg   [10:0] indvar_flatten171_fu_340;
wire   [10:0] add_ln66_1_fu_1137_p2;
reg   [4:0] y_3_fu_344;
wire   [4:0] add_ln119_fu_1762_p2;
reg   [4:0] x_3_fu_348;
reg   [9:0] indvar_flatten289_fu_352;
wire   [9:0] select_ln117_3_fu_1774_p3;
reg   [2:0] n_2_fu_356;
wire   [2:0] select_ln115_3_fu_1628_p3;
reg   [11:0] indvar_flatten315_fu_360;
wire   [11:0] add_ln115_1_fu_1550_p2;
reg   [4:0] y_2_fu_364;
wire   [4:0] add_ln149_fu_1929_p2;
reg   [4:0] x_2_fu_368;
reg   [9:0] indvar_flatten393_fu_372;
wire   [9:0] add_ln147_1_fu_1906_p2;
wire   [15:0] zext_ln36_2_fu_984_p1;
wire   [15:0] zext_ln88_2_fu_1462_p1;
wire   [15:0] zext_ln137_2_fu_1884_p1;
wire   [1:0] s_V_fu_592_p5;
wire   [12:0] shl_ln36_1_fu_606_p3;
wire   [9:0] shl_ln36_2_fu_618_p3;
wire   [13:0] zext_ln36_fu_614_p1;
wire   [13:0] zext_ln36_1_fu_626_p1;
wire   [2:0] add_ln17_fu_651_p2;
wire   [4:0] p_shl_cast_mid2_v_fu_691_p3;
wire   [1:0] s_V_mid1_fu_703_p5;
wire   [15:0] s_V_mid1_fu_703_p6;
wire   [15:0] s_V_fu_592_p6;
wire   [13:0] sub_ln36_fu_630_p2;
wire   [0:0] icmp_ln21_fu_739_p2;
wire   [0:0] xor_ln17_fu_733_p2;
wire   [4:0] select_ln17_fu_663_p3;
wire   [0:0] and_ln17_fu_745_p2;
wire   [0:0] or_ln19_fu_757_p2;
wire   [4:0] add_ln19_fu_751_p2;
wire   [12:0] shl_ln36_1_mid1_fu_771_p3;
wire   [9:0] shl_ln36_2_mid1_fu_783_p3;
wire   [13:0] zext_ln36_4_fu_779_p1;
wire   [13:0] zext_ln36_5_fu_791_p1;
wire   [13:0] sub_ln36_1_fu_795_p2;
wire   [13:0] select_ln17_3_fu_725_p3;
wire   [5:0] zext_ln21_fu_817_p1;
wire   [4:0] zext_ln25_fu_864_p1;
wire   [4:0] empty_82_fu_868_p2;
wire   [5:0] p_cast78_fu_873_p1;
wire   [5:0] empty_83_fu_877_p2;
wire   [4:0] trunc_ln32_fu_883_p1;
wire   [7:0] tmp_13_fu_895_p3;
wire   [9:0] tmp_12_fu_887_p3;
wire   [9:0] zext_ln32_fu_903_p1;
wire   [3:0] p_shl3_fu_914_p3;
wire   [4:0] p_shl3_cast_fu_922_p1;
wire   [4:0] empty_84_fu_926_p2;
wire   [4:0] tmp3_fu_932_p2;
wire  signed [5:0] tmp3_cast_fu_937_p1;
wire   [0:0] notrhs_fu_953_p2;
wire   [0:0] notlhs_fu_947_p2;
wire   [0:0] icmp_ln1649_3_fu_970_p2;
wire   [14:0] trunc_ln25_fu_966_p1;
wire   [14:0] select_ln65_fu_976_p3;
wire   [7:0] tmp2_fu_989_p4;
wire   [13:0] zext_ln36_3_fu_997_p1;
wire   [13:0] add_ln36_fu_1001_p2;
wire   [12:0] trunc_ln5_fu_1006_p4;
wire  signed [13:0] sext_ln36_fu_1016_p1;
wire   [9:0] add_ln19_1_fu_1030_p2;
wire   [2:0] empty_88_fu_1087_p1;
wire   [11:0] shl_ln88_1_fu_1101_p3;
wire   [8:0] shl_ln88_2_fu_1113_p3;
wire   [12:0] zext_ln88_fu_1109_p1;
wire   [12:0] zext_ln88_1_fu_1121_p1;
wire   [0:0] icmp_ln68_fu_1155_p2;
wire   [3:0] add_ln66_fu_1149_p2;
wire   [2:0] empty_87_fu_1169_p1;
wire   [7:0] tmp_5_mid1_fu_1173_p4;
wire   [7:0] tmp_5_fu_1091_p4;
wire   [12:0] sub_ln88_fu_1125_p2;
wire   [0:0] icmp_ln70_fu_1222_p2;
wire   [0:0] xor_ln66_fu_1216_p2;
wire   [3:0] select_ln66_fu_1161_p3;
wire   [0:0] and_ln66_fu_1228_p2;
wire   [0:0] or_ln68_fu_1240_p2;
wire   [3:0] add_ln68_fu_1234_p2;
wire   [11:0] shl_ln88_1_mid1_fu_1254_p3;
wire   [8:0] shl_ln88_2_mid1_fu_1266_p3;
wire   [12:0] zext_ln88_4_fu_1262_p1;
wire   [12:0] zext_ln88_5_fu_1274_p1;
wire   [12:0] sub_ln88_1_fu_1278_p2;
wire   [12:0] select_ln66_3_fu_1208_p3;
wire   [2:0] trunc_ln66_fu_1204_p1;
wire   [7:0] tmp4_fu_1300_p4;
wire   [12:0] zext_ln88_3_fu_1310_p1;
wire   [12:0] select_ln68_1_fu_1284_p3;
wire   [12:0] add_ln88_fu_1314_p2;
wire   [7:0] add_ln68_1_fu_1336_p2;
wire   [4:0] p_cast123_mid1109_fu_1400_p1;
wire   [4:0] p_mid1111_fu_1403_p2;
wire   [7:0] shl_ln83_mid_fu_1422_p3;
wire  signed [12:0] sext_ln83_3_fu_1430_p1;
wire   [0:0] icmp_ln1649_fu_1448_p2;
wire   [14:0] trunc_ln74_fu_1444_p1;
wire   [14:0] select_ln65_1_fu_1454_p3;
wire  signed [13:0] sext_ln88_fu_1467_p1;
wire   [1:0] empty_91_fu_1484_p1;
wire   [12:0] shl_ln137_1_fu_1514_p3;
wire   [9:0] shl_ln137_2_fu_1526_p3;
wire   [13:0] zext_ln137_fu_1522_p1;
wire   [13:0] zext_ln137_1_fu_1534_p1;
wire   [0:0] icmp_ln117_fu_1568_p2;
wire   [2:0] add_ln115_fu_1562_p2;
wire   [1:0] empty_90_fu_1582_p1;
wire   [7:0] tmp_11_mid1_fu_1586_p5;
wire   [7:0] tmp_11_fu_1488_p5;
wire   [15:0] s_V_8_mid1_fu_1606_p6;
wire   [15:0] s_V_4_fu_1500_p6;
wire   [13:0] sub_ln137_fu_1538_p2;
wire   [0:0] icmp_ln119_fu_1654_p2;
wire   [0:0] xor_ln115_fu_1648_p2;
wire   [4:0] select_ln115_fu_1574_p3;
wire   [0:0] and_ln115_fu_1660_p2;
wire   [0:0] or_ln117_fu_1672_p2;
wire   [4:0] add_ln117_fu_1666_p2;
wire   [12:0] shl_ln137_1_mid1_fu_1686_p3;
wire   [9:0] shl_ln137_2_mid1_fu_1698_p3;
wire   [13:0] zext_ln137_4_fu_1694_p1;
wire   [13:0] zext_ln137_5_fu_1706_p1;
wire   [13:0] sub_ln137_1_fu_1710_p2;
wire   [13:0] select_ln115_4_fu_1640_p3;
wire   [1:0] trunc_ln115_fu_1636_p1;
wire   [7:0] tmp5_fu_1732_p4;
wire   [13:0] zext_ln137_3_fu_1742_p1;
wire   [13:0] select_ln117_1_fu_1716_p3;
wire   [13:0] add_ln137_fu_1746_p2;
wire   [9:0] add_ln117_1_fu_1768_p2;
wire   [5:0] p_cast127_mid1252_fu_1822_p1;
wire   [5:0] p_mid1254_fu_1825_p2;
wire   [9:0] shl_ln132_mid_fu_1844_p3;
wire  signed [12:0] sext_ln132_3_fu_1852_p1;
wire   [0:0] icmp_ln1649_4_fu_1870_p2;
wire   [14:0] trunc_ln123_fu_1866_p1;
wire   [14:0] select_ln65_2_fu_1876_p3;
wire  signed [13:0] sext_ln137_fu_1889_p1;
wire   [4:0] add_ln147_fu_1948_p2;
wire   [5:0] p_cast125_mid1358_fu_1962_p1;
wire   [5:0] p_mid1360_fu_1965_p2;
wire   [0:0] icmp_ln1649_5_fu_2001_p2;
wire   [0:0] icmp_ln1650_fu_2007_p2;
wire   [0:0] or_ln69_fu_2013_p2;
wire   [13:0] select_ln69_fu_2019_p3;
wire   [13:0] trunc_ln838_fu_2027_p1;
wire   [13:0] select_ln69_1_fu_2031_p3;
wire   [19:0] x_wide_fu_2039_p3;
wire   [19:0] r_V_fu_2047_p2;
wire   [0:0] p_Result_s_fu_2053_p3;
wire   [6:0] tmp_fu_2061_p4;
wire   [7:0] p_Result_6_fu_2071_p3;
wire   [4:0] f_x_msb_2_h_V_fu_2099_p4;
wire   [8:0] zext_ln813_2_fu_2113_p1;
wire   [8:0] zext_ln813_fu_2109_p1;
wire   [8:0] ret_V_6_fu_2116_p2;
wire   [40:0] trunc_ln594_fu_2122_p1;
wire   [55:0] rhs_fu_2126_p4;
wire   [55:0] ret_V_fu_2136_p2;
wire   [49:0] exp_x_msb_2_3_4_lsb_m_1_V_fu_2142_p4;
wire   [49:0] r_V_10_fu_2160_p0;
wire   [49:0] r_V_10_fu_2160_p1;
wire   [99:0] r_V_10_fu_2160_p2;
wire   [49:0] zext_ln813_1_fu_2176_p1;
wire   [49:0] y_l_V_fu_2179_p2;
wire   [1:0] tmp_8_fu_2184_p4;
wire   [0:0] overf_fu_2194_p2;
wire   [0:0] p_Result_5_fu_2208_p3;
wire   [0:0] or_ln533_fu_2216_p2;
wire   [0:0] p_Result_4_fu_2200_p3;
wire   [2:0] tmp_14_fu_2228_p4;
wire   [0:0] icmp_ln533_fu_2238_p2;
wire   [0:0] or_ln533_1_fu_2222_p2;
wire   [0:0] overf_1_fu_2244_p2;
wire   [31:0] tmp_20_fu_2250_p4;
wire   [31:0] exp_val_fu_2260_p3;
wire  signed [32:0] sext_ln813_fu_2268_p1;
wire  signed [32:0] ret_V_5_fu_2272_p2;
wire   [6:0] tmp_18_fu_2295_p3;
wire   [9:0] tmp_s_fu_2288_p3;
wire   [9:0] zext_ln167_fu_2302_p1;
wire   [9:0] sub_ln167_fu_2306_p2;
wire   [9:0] zext_ln167_1_fu_2312_p1;
wire   [9:0] add_ln167_fu_2315_p2;
wire   [33:0] grp_fu_2282_p2;
reg    grp_fu_2282_ap_start;
wire    grp_fu_2282_ap_done;
reg   [57:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire   [99:0] r_V_10_fu_2160_p00;
wire   [99:0] r_V_10_fu_2160_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 58'd1;
#0 grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_start_reg = 1'b0;
#0 grp_inference_Pipeline_loop_kw_1_fu_481_ap_start_reg = 1'b0;
#0 grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_start_reg = 1'b0;
#0 grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_start_reg = 1'b0;
#0 grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_start_reg = 1'b0;
#0 grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_start_reg = 1'b0;
end

denoiser_top_inference_conv2_bias_V_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
conv2_bias_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv2_bias_V_address0),
    .ce0(conv2_bias_V_ce0),
    .q0(conv2_bias_V_q0)
);

denoiser_top_inference_f_x_msb_2_table_V_ROM_AUTO_1R #(
    .DataWidth( 46 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
f_x_msb_2_table_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(f_x_msb_2_table_V_address0),
    .ce0(f_x_msb_2_table_V_ce0),
    .q0(f_x_msb_2_table_V_q0)
);

denoiser_top_inference_exp_x_msb_1_table_V_ROM_AUTO_1R #(
    .DataWidth( 50 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
exp_x_msb_1_table_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_x_msb_1_table_V_address0),
    .ce0(exp_x_msb_1_table_V_ce0),
    .q0(exp_x_msb_1_table_V_q0)
);

denoiser_top_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3 grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_start),
    .ap_done(grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_done),
    .ap_idle(grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_idle),
    .ap_ready(grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_ready),
    .d_address0(grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_address0),
    .d_ce0(grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_ce0),
    .d_we0(grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_we0),
    .d_d0(grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_d0),
    .d_q0(d_q0),
    .d_address1(grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_address1),
    .d_ce1(grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_ce1),
    .d_q1(d_q1)
);

denoiser_top_inference_Pipeline_loop_kw_1 grp_inference_Pipeline_loop_kw_1_fu_481(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_inference_Pipeline_loop_kw_1_fu_481_ap_start),
    .ap_done(grp_inference_Pipeline_loop_kw_1_fu_481_ap_done),
    .ap_idle(grp_inference_Pipeline_loop_kw_1_fu_481_ap_idle),
    .ap_ready(grp_inference_Pipeline_loop_kw_1_fu_481_ap_ready),
    .s_V_1(s_V_1_reg_465),
    .add_ln30(add_ln30_reg_2458),
    .sub_ln32(sub_ln32_reg_2506),
    .input_r_address0(grp_inference_Pipeline_loop_kw_1_fu_481_input_r_address0),
    .input_r_ce0(grp_inference_Pipeline_loop_kw_1_fu_481_input_r_ce0),
    .input_r_q0(input_r_q0),
    .input_r_address1(grp_inference_Pipeline_loop_kw_1_fu_481_input_r_address1),
    .input_r_ce1(grp_inference_Pipeline_loop_kw_1_fu_481_input_r_ce1),
    .input_r_q1(input_r_q1),
    .brmerge_not(brmerge_not_reg_2516),
    .empty(empty_85_reg_2511),
    .zext_ln21(select_ln19_reg_2440),
    .s_V_13_out(grp_inference_Pipeline_loop_kw_1_fu_481_s_V_13_out),
    .s_V_13_out_ap_vld(grp_inference_Pipeline_loop_kw_1_fu_481_s_V_13_out_ap_vld),
    .s_V_14_out(grp_inference_Pipeline_loop_kw_1_fu_481_s_V_14_out),
    .s_V_14_out_ap_vld(grp_inference_Pipeline_loop_kw_1_fu_481_s_V_14_out_ap_vld),
    .ap_return(grp_inference_Pipeline_loop_kw_1_fu_481_ap_return)
);

denoiser_top_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3 grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_start),
    .ap_done(grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_done),
    .ap_idle(grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_idle),
    .ap_ready(grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_ready),
    .d_address0(grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_address0),
    .d_ce0(grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_ce0),
    .d_we0(grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_we0),
    .d_d0(grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_d0),
    .d_q0(d_q0)
);

denoiser_top_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2 grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_start),
    .ap_done(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_done),
    .ap_idle(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_idle),
    .ap_ready(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_ready),
    .sext_ln66(conv2_bias_V_load_reg_2596),
    .select_ln68_2(select_ln68_2_reg_2551),
    .select_ln68(select_ln68_reg_2544),
    .zext_ln66(select_ln66_1_reg_2534),
    .cmp27_i_not_mid1115(cmp27_i_not_mid1115_reg_2601),
    .cmp29_i_not_mid1117(cmp29_i_not_mid1117_reg_2606),
    .sext_ln83_4(add_ln83_2_reg_2611),
    .d_address0(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_address0),
    .d_ce0(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_ce0),
    .d_q0(d_q0),
    .d_address1(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_address1),
    .d_ce1(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_ce1),
    .d_q1(d_q1),
    .s_V_15_out(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_s_V_15_out),
    .s_V_15_out_ap_vld(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_s_V_15_out_ap_vld)
);

denoiser_top_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3 grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_start),
    .ap_done(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_done),
    .ap_idle(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_idle),
    .ap_ready(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_ready),
    .select_ln115_2(select_ln115_2_reg_2624),
    .select_ln117_2(select_ln117_2_reg_2636),
    .select_ln117(select_ln117_reg_2629),
    .zext_ln115(select_ln115_1_reg_2619),
    .cmp27_i431_not_mid1258(cmp27_i431_not_mid1258_reg_2667),
    .cmp29_i433_not_mid1260(cmp29_i433_not_mid1260_reg_2672),
    .zext_ln132_3(add_ln132_2_reg_2677),
    .d_address0(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_address0),
    .d_ce0(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_ce0),
    .d_q0(d_q0),
    .d_address1(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_address1),
    .d_ce1(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_ce1),
    .d_q1(d_q1),
    .s_V_16_out(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_s_V_16_out),
    .s_V_16_out_ap_vld(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_s_V_16_out_ap_vld)
);

denoiser_top_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_start),
    .ap_done(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_done),
    .ap_idle(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_idle),
    .ap_ready(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_ready),
    .select_ln147_1(select_ln147_1_reg_2698),
    .select_ln147(select_ln147_reg_2690),
    .cmp23_i72_not_mid1364(cmp23_i72_not_mid1364_reg_2705),
    .cmp25_i74_not_mid1366(cmp25_i74_not_mid1366_reg_2710),
    .sext_ln162_1(shl_ln162_mid_reg_2715),
    .d_address0(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_address0),
    .d_ce0(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_ce0),
    .d_q0(d_q0),
    .d_address1(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_address1),
    .d_ce1(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_ce1),
    .d_q1(d_q1),
    .s_V_18_out(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_s_V_18_out),
    .s_V_18_out_ap_vld(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_s_V_18_out_ap_vld)
);

denoiser_top_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U55(
    .din0(16'd761),
    .din1(16'd211),
    .din2(16'd65364),
    .din3(16'd64954),
    .din4(s_V_fu_592_p5),
    .dout(s_V_fu_592_p6)
);

denoiser_top_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U56(
    .din0(16'd761),
    .din1(16'd211),
    .din2(16'd65364),
    .din3(16'd64954),
    .din4(s_V_mid1_fu_703_p5),
    .dout(s_V_mid1_fu_703_p6)
);

denoiser_top_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U57(
    .din0(16'd140),
    .din1(16'd65514),
    .din2(16'd6),
    .din3(16'd40),
    .din4(empty_91_fu_1484_p1),
    .dout(s_V_4_fu_1500_p6)
);

denoiser_top_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U58(
    .din0(16'd140),
    .din1(16'd65514),
    .din2(16'd6),
    .din3(16'd40),
    .din4(empty_90_fu_1582_p1),
    .dout(s_V_8_mid1_fu_1606_p6)
);

denoiser_top_mul_50ns_50ns_100_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 100 ))
mul_50ns_50ns_100_1_1_U59(
    .din0(r_V_10_fu_2160_p0),
    .din1(r_V_10_fu_2160_p1),
    .dout(r_V_10_fu_2160_p2)
);

denoiser_top_sdiv_34ns_33s_34_38_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 38 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 33 ),
    .dout_WIDTH( 34 ))
sdiv_34ns_33s_34_38_seq_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_2282_ap_start),
    .done(grp_fu_2282_ap_done),
    .din0(34'd4294967296),
    .din1(ret_V_5_fu_2272_p2),
    .ce(1'b1),
    .dout(grp_fu_2282_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln17_fu_636_p2 == 1'd1))) begin
            grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_start_reg <= 1'b1;
        end else if ((grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_ready == 1'b1)) begin
            grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd1))) begin
            grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_start_reg <= 1'b1;
        end else if ((grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_ready == 1'b1)) begin
            grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_start_reg <= 1'b1;
        end else if ((grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_ready == 1'b1)) begin
            grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_start_reg <= 1'b1;
        end else if ((grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_ready == 1'b1)) begin
            grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_start_reg <= 1'b1;
        end else if ((grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_ready == 1'b1)) begin
            grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_inference_Pipeline_loop_kw_1_fu_481_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln25_fu_852_p2 == 1'd0))) begin
            grp_inference_Pipeline_loop_kw_1_fu_481_ap_start_reg <= 1'b1;
        end else if ((grp_inference_Pipeline_loop_kw_1_fu_481_ap_ready == 1'b1)) begin
            grp_inference_Pipeline_loop_kw_1_fu_481_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_reg_454 <= add_ln25_reg_2501;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln17_fu_636_p2 == 1'd0))) begin
        i_reg_454 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln17_fu_636_p2 == 1'd1))) begin
        indvar_flatten144_fu_332 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd0))) begin
        indvar_flatten144_fu_332 <= select_ln68_3_fu_1342_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln17_fu_636_p2 == 1'd1))) begin
        indvar_flatten171_fu_340 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd0))) begin
        indvar_flatten171_fu_340 <= add_ln66_1_fu_1137_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten25_fu_300 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln25_fu_852_p2 == 1'd1))) begin
        indvar_flatten25_fu_300 <= add_ln17_1_reg_2405;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd1))) begin
        indvar_flatten289_fu_352 <= 10'd0;
    end else if (((icmp_ln115_fu_1544_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        indvar_flatten289_fu_352 <= select_ln117_3_fu_1774_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd1))) begin
        indvar_flatten315_fu_360 <= 12'd0;
    end else if (((icmp_ln115_fu_1544_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        indvar_flatten315_fu_360 <= add_ln115_1_fu_1550_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln115_fu_1544_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        indvar_flatten393_fu_372 <= 10'd0;
    end else if (((icmp_ln147_fu_1900_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        indvar_flatten393_fu_372 <= add_ln147_1_fu_1906_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_292 <= 10'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln25_fu_852_p2 == 1'd1))) begin
        indvar_flatten_fu_292 <= select_ln19_3_fu_1036_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln17_fu_636_p2 == 1'd1))) begin
        n_1_fu_336 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd0))) begin
        n_1_fu_336 <= select_ln66_2_fu_1191_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd1))) begin
        n_2_fu_356 <= 3'd0;
    end else if (((icmp_ln115_fu_1544_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        n_2_fu_356 <= select_ln115_3_fu_1628_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        n_fu_296 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln25_fu_852_p2 == 1'd1))) begin
        n_fu_296 <= select_ln17_1_reg_2415;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_V_1_reg_465 <= s_V_3_fu_1071_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln17_fu_636_p2 == 1'd0))) begin
        s_V_1_reg_465 <= select_ln17_2_fu_717_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln17_fu_636_p2 == 1'd1))) begin
        x_1_fu_328 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd0))) begin
        x_1_fu_328 <= select_ln68_2_fu_1292_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln115_fu_1544_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        x_2_fu_368 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        x_2_fu_368 <= select_ln147_1_fu_1954_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd1))) begin
        x_3_fu_348 <= 5'd0;
    end else if (((icmp_ln115_fu_1544_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        x_3_fu_348 <= select_ln117_2_fu_1724_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_fu_288 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln25_fu_852_p2 == 1'd1))) begin
        x_fu_288 <= select_ln19_2_reg_2452;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln17_fu_636_p2 == 1'd1))) begin
        y_1_fu_324 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd0))) begin
        y_1_fu_324 <= add_ln70_fu_1330_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln115_fu_1544_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        y_2_fu_364 <= 5'd0;
    end else if (((icmp_ln147_fu_1900_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        y_2_fu_364 <= add_ln149_fu_1929_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd1))) begin
        y_3_fu_344 <= 5'd0;
    end else if (((icmp_ln115_fu_1544_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        y_3_fu_344 <= add_ln119_fu_1762_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_284 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln25_fu_852_p2 == 1'd1))) begin
        y_fu_284 <= add_ln21_fu_1025_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln132_2_reg_2677[12 : 4] <= add_ln132_2_fu_1856_p2[12 : 4];
        cmp27_i431_not_mid1258_reg_2667 <= cmp27_i431_not_mid1258_fu_1831_p2;
        cmp29_i433_not_mid1260_reg_2672 <= cmp29_i433_not_mid1260_fu_1837_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln17_1_reg_2405 <= add_ln17_1_fu_642_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln25_reg_2501 <= add_ln25_fu_858_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln17_fu_636_p2 == 1'd0))) begin
        add_ln30_reg_2458 <= add_ln30_fu_821_p2;
        icmp_ln19_reg_2410 <= icmp_ln19_fu_657_p2;
        select_ln17_1_reg_2415 <= select_ln17_1_fu_671_p3;
        select_ln19_1_reg_2447[13 : 5] <= select_ln19_1_fu_801_p3[13 : 5];
        select_ln19_2_reg_2452 <= select_ln19_2_fu_809_p3;
        select_ln19_reg_2440 <= select_ln19_fu_763_p3;
        trunc_ln17_reg_2425 <= trunc_ln17_fu_687_p1;
        zext_ln17_1_reg_2430[4 : 3] <= zext_ln17_1_fu_699_p1[4 : 3];
        zext_ln17_reg_2420[2 : 0] <= zext_ln17_fu_679_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln83_2_reg_2611[12 : 3] <= add_ln83_2_fu_1434_p2[12 : 3];
        cmp27_i_not_mid1115_reg_2601 <= cmp27_i_not_mid1115_fu_1409_p2;
        cmp29_i_not_mid1117_reg_2606 <= cmp29_i_not_mid1117_fu_1415_p2;
        conv2_bias_V_load_reg_2596 <= conv2_bias_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln25_fu_852_p2 == 1'd0))) begin
        brmerge_not_reg_2516 <= brmerge_not_fu_959_p2;
        empty_85_reg_2511 <= empty_85_fu_941_p2;
        sub_ln32_reg_2506[9 : 2] <= sub_ln32_fu_907_p2[9 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        cmp23_i72_not_mid1364_reg_2705 <= cmp23_i72_not_mid1364_fu_1971_p2;
        cmp25_i74_not_mid1366_reg_2710 <= cmp25_i74_not_mid1366_fu_1977_p2;
        select_ln147_1_reg_2698 <= select_ln147_1_fu_1954_p3;
        shl_ln162_mid_reg_2715[8 : 3] <= shl_ln162_mid_fu_1984_p3[8 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        exp_x_msb_1_V_reg_2735 <= exp_x_msb_1_table_V_q0;
        trunc_ln813_1_reg_2740 <= {{r_V_10_fu_2160_p2[99:52]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln147_fu_1900_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        icmp_ln149_reg_2685 <= icmp_ln149_fu_1915_p2;
        select_ln147_reg_2690 <= select_ln147_fu_1921_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_inference_Pipeline_loop_kw_1_fu_481_s_V_13_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        s_V_13_loc_fu_320 <= grp_inference_Pipeline_loop_kw_1_fu_481_s_V_13_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_inference_Pipeline_loop_kw_1_fu_481_s_V_14_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        s_V_14_loc_fu_316 <= grp_inference_Pipeline_loop_kw_1_fu_481_s_V_14_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln115_fu_1544_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        select_ln115_1_reg_2619[4 : 3] <= select_ln115_1_fu_1598_p3[4 : 3];
select_ln115_1_reg_2619[7 : 6] <= select_ln115_1_fu_1598_p3[7 : 6];
        select_ln115_2_reg_2624 <= select_ln115_2_fu_1620_p3;
        select_ln117_2_reg_2636 <= select_ln117_2_fu_1724_p3;
        select_ln117_reg_2629 <= select_ln117_fu_1678_p3;
        trunc_ln8_reg_2641 <= {{add_ln137_fu_1746_p2[13:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd0))) begin
        select_ln66_1_reg_2534[7 : 2] <= select_ln66_1_fu_1183_p3[7 : 2];
        select_ln68_2_reg_2551 <= select_ln68_2_fu_1292_p3;
        select_ln68_reg_2544 <= select_ln68_fu_1246_p3;
        trunc_ln7_reg_2556 <= {{add_ln88_fu_1314_p2[12:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        targetBlock_reg_2521 <= grp_inference_Pipeline_loop_kw_1_fu_481_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        tmp_15_reg_2720 <= {{r_V_fu_2047_p2[12:5]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

always @ (*) begin
    if ((grp_inference_Pipeline_loop_kw_1_fu_481_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln147_fu_1900_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln147_fu_1900_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        conv2_bias_V_ce0 = 1'b1;
    end else begin
        conv2_bias_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        d_address0 = zext_ln137_6_fu_1892_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        d_address0 = zext_ln88_6_fu_1470_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_address0 = zext_ln36_6_fu_1020_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        d_address0 = grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_address0 = grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_address0 = grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_address0 = grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_address0 = grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_address0;
    end else begin
        d_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        d_address1 = grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_address1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_address1 = grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_address1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_address1 = grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_address1 = grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_address1;
    end else begin
        d_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state3))) begin
        d_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        d_ce0 = grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_ce0 = grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_ce0 = grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_ce0 = grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_ce0 = grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_ce0;
    end else begin
        d_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        d_ce1 = grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_d_ce1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        d_ce1 = grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_d_ce1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        d_ce1 = grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_d_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_ce1 = grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_ce1;
    end else begin
        d_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        d_d0 = zext_ln137_2_fu_1884_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        d_d0 = zext_ln88_2_fu_1462_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_d0 = zext_ln36_2_fu_984_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_d0 = grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_d0 = grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_d0;
    end else begin
        d_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln25_fu_852_p2 == 1'd1)))) begin
        d_we0 = 2'd3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        d_we0 = grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_d_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_we0 = grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_d_we0;
    end else begin
        d_we0 = 2'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        exp_x_msb_1_table_V_ce0 = 1'b1;
    end else begin
        exp_x_msb_1_table_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        f_x_msb_2_table_V_ce0 = 1'b1;
    end else begin
        f_x_msb_2_table_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_2282_ap_start = 1'b1;
    end else begin
        grp_fu_2282_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln17_fu_636_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln25_fu_852_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_inference_Pipeline_loop_kw_1_fu_481_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln66_fu_1131_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln115_fu_1544_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln147_fu_1900_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln115_1_fu_1550_p2 = (indvar_flatten315_fu_360 + 12'd1);

assign add_ln115_fu_1562_p2 = (n_2_fu_356 + 3'd1);

assign add_ln117_1_fu_1768_p2 = (indvar_flatten289_fu_352 + 10'd1);

assign add_ln117_fu_1666_p2 = (select_ln115_fu_1574_p3 + 5'd1);

assign add_ln119_fu_1762_p2 = (select_ln117_fu_1678_p3 + 5'd1);

assign add_ln132_2_fu_1856_p2 = ($signed(sext_ln132_3_fu_1852_p1) + $signed(13'd4352));

assign add_ln137_fu_1746_p2 = (zext_ln137_3_fu_1742_p1 + select_ln117_1_fu_1716_p3);

assign add_ln147_1_fu_1906_p2 = (indvar_flatten393_fu_372 + 10'd1);

assign add_ln147_fu_1948_p2 = (x_2_fu_368 + 5'd1);

assign add_ln149_fu_1929_p2 = (select_ln147_fu_1921_p3 + 5'd1);

assign add_ln167_fu_2315_p2 = (sub_ln167_fu_2306_p2 + zext_ln167_1_fu_2312_p1);

assign add_ln17_1_fu_642_p2 = (indvar_flatten25_fu_300 + 12'd1);

assign add_ln17_fu_651_p2 = (n_fu_296 + 3'd1);

assign add_ln19_1_fu_1030_p2 = (indvar_flatten_fu_292 + 10'd1);

assign add_ln19_fu_751_p2 = (select_ln17_fu_663_p3 + 5'd1);

assign add_ln21_fu_1025_p2 = (select_ln19_reg_2440 + 5'd1);

assign add_ln25_fu_858_p2 = (i_reg_454 + 2'd1);

assign add_ln30_fu_821_p2 = ($signed(zext_ln21_fu_817_p1) + $signed(6'd63));

assign add_ln36_fu_1001_p2 = (zext_ln36_3_fu_997_p1 + select_ln19_1_reg_2447);

assign add_ln66_1_fu_1137_p2 = (indvar_flatten171_fu_340 + 11'd1);

assign add_ln66_fu_1149_p2 = (n_1_fu_336 + 4'd1);

assign add_ln68_1_fu_1336_p2 = (indvar_flatten144_fu_332 + 8'd1);

assign add_ln68_fu_1234_p2 = (select_ln66_fu_1161_p3 + 4'd1);

assign add_ln70_fu_1330_p2 = (select_ln68_fu_1246_p3 + 4'd1);

assign add_ln83_2_fu_1434_p2 = ($signed(sext_ln83_3_fu_1430_p1) + $signed(13'd4352));

assign add_ln88_fu_1314_p2 = (zext_ln88_3_fu_1310_p1 + select_ln68_1_fu_1284_p3);

assign and_ln115_fu_1660_p2 = (xor_ln115_fu_1648_p2 & icmp_ln119_fu_1654_p2);

assign and_ln17_fu_745_p2 = (xor_ln17_fu_733_p2 & icmp_ln21_fu_739_p2);

assign and_ln66_fu_1228_p2 = (xor_ln66_fu_1216_p2 & icmp_ln70_fu_1222_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign brmerge_not_fu_959_p2 = (notrhs_fu_953_p2 & notlhs_fu_947_p2);

assign cmp23_i72_not_mid1364_fu_1971_p2 = ((select_ln147_reg_2690 == 5'd0) ? 1'b1 : 1'b0);

assign cmp25_i74_not_mid1366_fu_1977_p2 = (($signed(p_mid1360_fu_1965_p2) > $signed(6'd27)) ? 1'b1 : 1'b0);

assign cmp27_i431_not_mid1258_fu_1831_p2 = ((select_ln117_reg_2629 == 5'd0) ? 1'b1 : 1'b0);

assign cmp27_i_not_mid1115_fu_1409_p2 = ((select_ln68_reg_2544 == 4'd0) ? 1'b1 : 1'b0);

assign cmp29_i433_not_mid1260_fu_1837_p2 = (($signed(p_mid1254_fu_1825_p2) > $signed(6'd27)) ? 1'b1 : 1'b0);

assign cmp29_i_not_mid1117_fu_1415_p2 = (($signed(p_mid1111_fu_1403_p2) > $signed(5'd13)) ? 1'b1 : 1'b0);

assign conv2_bias_V_address0 = zext_ln66_fu_1199_p1;

assign empty_82_fu_868_p2 = (zext_ln25_fu_864_p1 + select_ln19_2_reg_2452);

assign empty_83_fu_877_p2 = ($signed(p_cast78_fu_873_p1) + $signed(6'd63));

assign empty_84_fu_926_p2 = (p_shl3_cast_fu_922_p1 - zext_ln25_fu_864_p1);

assign empty_85_fu_941_p2 = ($signed(tmp3_cast_fu_937_p1) + $signed(zext_ln17_1_reg_2430));

assign empty_87_fu_1169_p1 = add_ln66_fu_1149_p2[2:0];

assign empty_88_fu_1087_p1 = n_1_fu_336[2:0];

assign empty_90_fu_1582_p1 = add_ln115_fu_1562_p2[1:0];

assign empty_91_fu_1484_p1 = n_2_fu_356[1:0];

assign exp_val_fu_2260_p3 = ((overf_1_fu_2244_p2[0:0] == 1'b1) ? 32'd4294967295 : tmp_20_fu_2250_p4);

assign exp_x_msb_1_table_V_address0 = zext_ln541_1_fu_2094_p1;

assign exp_x_msb_2_3_4_lsb_m_1_V_fu_2142_p4 = {{ret_V_fu_2136_p2[55:6]}};

assign f_x_msb_2_h_V_fu_2099_p4 = {{f_x_msb_2_table_V_q0[45:41]}};

assign f_x_msb_2_table_V_address0 = zext_ln541_fu_2089_p1;

assign grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_start = grp_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3_fu_475_ap_start_reg;

assign grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_start = grp_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3_fu_498_ap_start_reg;

assign grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_start = grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_ap_start_reg;

assign grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_start = grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_ap_start_reg;

assign grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_start = grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_ap_start_reg;

assign grp_inference_Pipeline_loop_kw_1_fu_481_ap_start = grp_inference_Pipeline_loop_kw_1_fu_481_ap_start_reg;

assign icmp_ln115_fu_1544_p2 = ((indvar_flatten315_fu_360 == 12'd3136) ? 1'b1 : 1'b0);

assign icmp_ln117_fu_1568_p2 = ((indvar_flatten289_fu_352 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_1654_p2 = ((y_3_fu_344 == 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln147_fu_1900_p2 = ((indvar_flatten393_fu_372 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln149_fu_1915_p2 = ((y_2_fu_364 == 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln1649_3_fu_970_p2 = (($signed(s_V_1_reg_465) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_4_fu_1870_p2 = (($signed(grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_s_V_16_out) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_5_fu_2001_p2 = (($signed(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_s_V_18_out) > $signed(16'd7168)) ? 1'b1 : 1'b0);

assign icmp_ln1649_fu_1448_p2 = (($signed(grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_s_V_15_out) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1650_fu_2007_p2 = (($signed(grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_s_V_18_out) < $signed(16'd58368)) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_636_p2 = ((indvar_flatten25_fu_300 == 12'd3136) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_657_p2 = ((indvar_flatten_fu_292 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_739_p2 = ((y_fu_284 == 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_852_p2 = ((i_reg_454 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln533_fu_2238_p2 = ((tmp_14_fu_2228_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_1131_p2 = ((indvar_flatten171_fu_340 == 11'd1568) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_1155_p2 = ((indvar_flatten144_fu_332 == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_1222_p2 = ((y_1_fu_324 == 4'd14) ? 1'b1 : 1'b0);

assign input_r_address0 = grp_inference_Pipeline_loop_kw_1_fu_481_input_r_address0;

assign input_r_address1 = grp_inference_Pipeline_loop_kw_1_fu_481_input_r_address1;

assign input_r_ce0 = grp_inference_Pipeline_loop_kw_1_fu_481_input_r_ce0;

assign input_r_ce1 = grp_inference_Pipeline_loop_kw_1_fu_481_input_r_ce1;

assign notlhs_fu_947_p2 = ((empty_82_fu_868_p2 != 5'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_953_p2 = (($signed(empty_83_fu_877_p2) < $signed(6'd28)) ? 1'b1 : 1'b0);

assign or_ln117_fu_1672_p2 = (icmp_ln117_fu_1568_p2 | and_ln115_fu_1660_p2);

assign or_ln19_fu_757_p2 = (icmp_ln19_fu_657_p2 | and_ln17_fu_745_p2);

assign or_ln533_1_fu_2222_p2 = (p_Result_4_fu_2200_p3 | or_ln533_fu_2216_p2);

assign or_ln533_fu_2216_p2 = (p_Result_5_fu_2208_p3 | overf_fu_2194_p2);

assign or_ln68_fu_1240_p2 = (icmp_ln68_fu_1155_p2 | and_ln66_fu_1228_p2);

assign or_ln69_fu_2013_p2 = (icmp_ln1650_fu_2007_p2 | icmp_ln1649_5_fu_2001_p2);

assign output_r_address0 = zext_ln167_2_fu_2321_p1;

assign output_r_d0 = {{grp_fu_2282_p2[21:6]}};

assign overf_1_fu_2244_p2 = (or_ln533_1_fu_2222_p2 | icmp_ln533_fu_2238_p2);

assign overf_fu_2194_p2 = ((tmp_8_fu_2184_p4 != 2'd0) ? 1'b1 : 1'b0);

assign p_Result_4_fu_2200_p3 = y_l_V_fu_2179_p2[32'd47];

assign p_Result_5_fu_2208_p3 = y_l_V_fu_2179_p2[32'd46];

assign p_Result_6_fu_2071_p3 = {{p_Result_s_fu_2053_p3}, {tmp_fu_2061_p4}};

assign p_Result_s_fu_2053_p3 = r_V_fu_2047_p2[32'd19];

assign p_cast123_mid1109_fu_1400_p1 = select_ln68_reg_2544;

assign p_cast125_mid1358_fu_1962_p1 = select_ln147_reg_2690;

assign p_cast127_mid1252_fu_1822_p1 = select_ln117_reg_2629;

assign p_cast78_fu_873_p1 = empty_82_fu_868_p2;

assign p_mid1111_fu_1403_p2 = ($signed(p_cast123_mid1109_fu_1400_p1) + $signed(5'd31));

assign p_mid1254_fu_1825_p2 = ($signed(p_cast127_mid1252_fu_1822_p1) + $signed(6'd63));

assign p_mid1360_fu_1965_p2 = ($signed(p_cast125_mid1358_fu_1962_p1) + $signed(6'd63));

assign p_shl3_cast_fu_922_p1 = p_shl3_fu_914_p3;

assign p_shl3_fu_914_p3 = {{i_reg_454}, {2'd0}};

assign p_shl_cast_mid2_v_fu_691_p3 = {{trunc_ln17_fu_687_p1}, {3'd0}};

assign r_V_10_fu_2160_p0 = r_V_10_fu_2160_p00;

assign r_V_10_fu_2160_p00 = exp_x_msb_2_3_4_lsb_m_1_V_fu_2142_p4;

assign r_V_10_fu_2160_p1 = r_V_10_fu_2160_p10;

assign r_V_10_fu_2160_p10 = exp_x_msb_1_table_V_q0;

assign r_V_fu_2047_p2 = (20'd0 - x_wide_fu_2039_p3);

assign ret_V_5_fu_2272_p2 = ($signed(sext_ln813_fu_2268_p1) + $signed(33'd65536));

assign ret_V_6_fu_2116_p2 = (zext_ln813_2_fu_2113_p1 + zext_ln813_fu_2109_p1);

assign ret_V_fu_2136_p2 = (rhs_fu_2126_p4 + 56'd0);

assign rhs_fu_2126_p4 = {{{ret_V_6_fu_2116_p2}, {trunc_ln594_fu_2122_p1}}, {6'd0}};

assign s_V_3_fu_1071_p3 = ((targetBlock_reg_2521[0:0] == 1'b1) ? s_V_13_loc_fu_320 : s_V_14_loc_fu_316);

assign s_V_fu_592_p5 = n_fu_296[1:0];

assign s_V_mid1_fu_703_p5 = add_ln17_fu_651_p2[1:0];

assign select_ln115_1_fu_1598_p3 = ((icmp_ln117_fu_1568_p2[0:0] == 1'b1) ? tmp_11_mid1_fu_1586_p5 : tmp_11_fu_1488_p5);

assign select_ln115_2_fu_1620_p3 = ((icmp_ln117_fu_1568_p2[0:0] == 1'b1) ? s_V_8_mid1_fu_1606_p6 : s_V_4_fu_1500_p6);

assign select_ln115_3_fu_1628_p3 = ((icmp_ln117_fu_1568_p2[0:0] == 1'b1) ? add_ln115_fu_1562_p2 : n_2_fu_356);

assign select_ln115_4_fu_1640_p3 = ((icmp_ln117_fu_1568_p2[0:0] == 1'b1) ? 14'd0 : sub_ln137_fu_1538_p2);

assign select_ln115_fu_1574_p3 = ((icmp_ln117_fu_1568_p2[0:0] == 1'b1) ? 5'd0 : x_3_fu_348);

assign select_ln117_1_fu_1716_p3 = ((and_ln115_fu_1660_p2[0:0] == 1'b1) ? sub_ln137_1_fu_1710_p2 : select_ln115_4_fu_1640_p3);

assign select_ln117_2_fu_1724_p3 = ((and_ln115_fu_1660_p2[0:0] == 1'b1) ? add_ln117_fu_1666_p2 : select_ln115_fu_1574_p3);

assign select_ln117_3_fu_1774_p3 = ((icmp_ln117_fu_1568_p2[0:0] == 1'b1) ? 10'd1 : add_ln117_1_fu_1768_p2);

assign select_ln117_fu_1678_p3 = ((or_ln117_fu_1672_p2[0:0] == 1'b1) ? 5'd0 : y_3_fu_344);

assign select_ln147_1_fu_1954_p3 = ((icmp_ln149_reg_2685[0:0] == 1'b1) ? add_ln147_fu_1948_p2 : x_2_fu_368);

assign select_ln147_fu_1921_p3 = ((icmp_ln149_fu_1915_p2[0:0] == 1'b1) ? 5'd0 : y_2_fu_364);

assign select_ln17_1_fu_671_p3 = ((icmp_ln19_fu_657_p2[0:0] == 1'b1) ? add_ln17_fu_651_p2 : n_fu_296);

assign select_ln17_2_fu_717_p3 = ((icmp_ln19_fu_657_p2[0:0] == 1'b1) ? s_V_mid1_fu_703_p6 : s_V_fu_592_p6);

assign select_ln17_3_fu_725_p3 = ((icmp_ln19_fu_657_p2[0:0] == 1'b1) ? 14'd0 : sub_ln36_fu_630_p2);

assign select_ln17_fu_663_p3 = ((icmp_ln19_fu_657_p2[0:0] == 1'b1) ? 5'd0 : x_fu_288);

assign select_ln19_1_fu_801_p3 = ((and_ln17_fu_745_p2[0:0] == 1'b1) ? sub_ln36_1_fu_795_p2 : select_ln17_3_fu_725_p3);

assign select_ln19_2_fu_809_p3 = ((and_ln17_fu_745_p2[0:0] == 1'b1) ? add_ln19_fu_751_p2 : select_ln17_fu_663_p3);

assign select_ln19_3_fu_1036_p3 = ((icmp_ln19_reg_2410[0:0] == 1'b1) ? 10'd1 : add_ln19_1_fu_1030_p2);

assign select_ln19_fu_763_p3 = ((or_ln19_fu_757_p2[0:0] == 1'b1) ? 5'd0 : y_fu_284);

assign select_ln65_1_fu_1454_p3 = ((icmp_ln1649_fu_1448_p2[0:0] == 1'b1) ? trunc_ln74_fu_1444_p1 : 15'd0);

assign select_ln65_2_fu_1876_p3 = ((icmp_ln1649_4_fu_1870_p2[0:0] == 1'b1) ? trunc_ln123_fu_1866_p1 : 15'd0);

assign select_ln65_fu_976_p3 = ((icmp_ln1649_3_fu_970_p2[0:0] == 1'b1) ? trunc_ln25_fu_966_p1 : 15'd0);

assign select_ln66_1_fu_1183_p3 = ((icmp_ln68_fu_1155_p2[0:0] == 1'b1) ? tmp_5_mid1_fu_1173_p4 : tmp_5_fu_1091_p4);

assign select_ln66_2_fu_1191_p3 = ((icmp_ln68_fu_1155_p2[0:0] == 1'b1) ? add_ln66_fu_1149_p2 : n_1_fu_336);

assign select_ln66_3_fu_1208_p3 = ((icmp_ln68_fu_1155_p2[0:0] == 1'b1) ? 13'd0 : sub_ln88_fu_1125_p2);

assign select_ln66_fu_1161_p3 = ((icmp_ln68_fu_1155_p2[0:0] == 1'b1) ? 4'd0 : x_1_fu_328);

assign select_ln68_1_fu_1284_p3 = ((and_ln66_fu_1228_p2[0:0] == 1'b1) ? sub_ln88_1_fu_1278_p2 : select_ln66_3_fu_1208_p3);

assign select_ln68_2_fu_1292_p3 = ((and_ln66_fu_1228_p2[0:0] == 1'b1) ? add_ln68_fu_1234_p2 : select_ln66_fu_1161_p3);

assign select_ln68_3_fu_1342_p3 = ((icmp_ln68_fu_1155_p2[0:0] == 1'b1) ? 8'd1 : add_ln68_1_fu_1336_p2);

assign select_ln68_fu_1246_p3 = ((or_ln68_fu_1240_p2[0:0] == 1'b1) ? 4'd0 : y_1_fu_324);

assign select_ln69_1_fu_2031_p3 = ((or_ln69_fu_2013_p2[0:0] == 1'b1) ? select_ln69_fu_2019_p3 : trunc_ln838_fu_2027_p1);

assign select_ln69_fu_2019_p3 = ((icmp_ln1649_5_fu_2001_p2[0:0] == 1'b1) ? 14'd7168 : 14'd9216);

assign sext_ln132_3_fu_1852_p1 = $signed(shl_ln132_mid_fu_1844_p3);

assign sext_ln137_fu_1889_p1 = $signed(trunc_ln8_reg_2641);

assign sext_ln36_fu_1016_p1 = $signed(trunc_ln5_fu_1006_p4);

assign sext_ln813_fu_2268_p1 = $signed(exp_val_fu_2260_p3);

assign sext_ln83_3_fu_1430_p1 = $signed(shl_ln83_mid_fu_1422_p3);

assign sext_ln88_fu_1467_p1 = $signed(trunc_ln7_reg_2556);

assign shl_ln132_mid_fu_1844_p3 = {{p_mid1254_fu_1825_p2}, {4'd0}};

assign shl_ln137_1_fu_1514_p3 = {{x_3_fu_348}, {8'd0}};

assign shl_ln137_1_mid1_fu_1686_p3 = {{add_ln117_fu_1666_p2}, {8'd0}};

assign shl_ln137_2_fu_1526_p3 = {{x_3_fu_348}, {5'd0}};

assign shl_ln137_2_mid1_fu_1698_p3 = {{add_ln117_fu_1666_p2}, {5'd0}};

assign shl_ln162_mid_fu_1984_p3 = {{p_mid1360_fu_1965_p2}, {3'd0}};

assign shl_ln36_1_fu_606_p3 = {{x_fu_288}, {8'd0}};

assign shl_ln36_1_mid1_fu_771_p3 = {{add_ln19_fu_751_p2}, {8'd0}};

assign shl_ln36_2_fu_618_p3 = {{x_fu_288}, {5'd0}};

assign shl_ln36_2_mid1_fu_783_p3 = {{add_ln19_fu_751_p2}, {5'd0}};

assign shl_ln83_mid_fu_1422_p3 = {{p_mid1111_fu_1403_p2}, {3'd0}};

assign shl_ln88_1_fu_1101_p3 = {{x_1_fu_328}, {8'd0}};

assign shl_ln88_1_mid1_fu_1254_p3 = {{add_ln68_fu_1234_p2}, {8'd0}};

assign shl_ln88_2_fu_1113_p3 = {{x_1_fu_328}, {5'd0}};

assign shl_ln88_2_mid1_fu_1266_p3 = {{add_ln68_fu_1234_p2}, {5'd0}};

assign sub_ln137_1_fu_1710_p2 = (zext_ln137_4_fu_1694_p1 - zext_ln137_5_fu_1706_p1);

assign sub_ln137_fu_1538_p2 = (zext_ln137_fu_1522_p1 - zext_ln137_1_fu_1534_p1);

assign sub_ln167_fu_2306_p2 = (tmp_s_fu_2288_p3 - zext_ln167_fu_2302_p1);

assign sub_ln32_fu_907_p2 = (tmp_12_fu_887_p3 - zext_ln32_fu_903_p1);

assign sub_ln36_1_fu_795_p2 = (zext_ln36_4_fu_779_p1 - zext_ln36_5_fu_791_p1);

assign sub_ln36_fu_630_p2 = (zext_ln36_fu_614_p1 - zext_ln36_1_fu_626_p1);

assign sub_ln88_1_fu_1278_p2 = (zext_ln88_4_fu_1262_p1 - zext_ln88_5_fu_1274_p1);

assign sub_ln88_fu_1125_p2 = (zext_ln88_fu_1109_p1 - zext_ln88_1_fu_1121_p1);

assign tmp2_fu_989_p4 = {{{select_ln19_reg_2440}, {trunc_ln17_reg_2425}}, {1'd0}};

assign tmp3_cast_fu_937_p1 = $signed(tmp3_fu_932_p2);

assign tmp3_fu_932_p2 = (zext_ln17_reg_2420 + empty_84_fu_926_p2);

assign tmp4_fu_1300_p4 = {{{select_ln68_fu_1246_p3}, {trunc_ln66_fu_1204_p1}}, {1'd0}};

assign tmp5_fu_1732_p4 = {{{select_ln117_fu_1678_p3}, {trunc_ln115_fu_1636_p1}}, {1'd0}};

assign tmp_11_fu_1488_p5 = {{{{empty_91_fu_1484_p1}, {1'd0}}, {empty_91_fu_1484_p1}}, {3'd0}};

assign tmp_11_mid1_fu_1586_p5 = {{{{empty_90_fu_1582_p1}, {1'd0}}, {empty_90_fu_1582_p1}}, {3'd0}};

assign tmp_12_fu_887_p3 = {{trunc_ln32_fu_883_p1}, {5'd0}};

assign tmp_13_fu_895_p3 = {{empty_83_fu_877_p2}, {2'd0}};

assign tmp_14_fu_2228_p4 = {{y_l_V_fu_2179_p2[45:43]}};

assign tmp_15_fu_2079_p4 = {{r_V_fu_2047_p2[12:5]}};

assign tmp_18_fu_2295_p3 = {{select_ln147_1_reg_2698}, {2'd0}};

assign tmp_20_fu_2250_p4 = {{y_l_V_fu_2179_p2[42:11]}};

assign tmp_5_fu_1091_p4 = {{{empty_88_fu_1087_p1}, {empty_88_fu_1087_p1}}, {2'd0}};

assign tmp_5_mid1_fu_1173_p4 = {{{empty_87_fu_1169_p1}, {empty_87_fu_1169_p1}}, {2'd0}};

assign tmp_8_fu_2184_p4 = {{y_l_V_fu_2179_p2[49:48]}};

assign tmp_fu_2061_p4 = {{r_V_fu_2047_p2[19:13]}};

assign tmp_s_fu_2288_p3 = {{select_ln147_1_reg_2698}, {5'd0}};

assign trunc_ln115_fu_1636_p1 = select_ln115_3_fu_1628_p3[1:0];

assign trunc_ln123_fu_1866_p1 = grp_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_fu_521_s_V_16_out[14:0];

assign trunc_ln17_fu_687_p1 = select_ln17_1_fu_671_p3[1:0];

assign trunc_ln25_fu_966_p1 = s_V_1_reg_465[14:0];

assign trunc_ln32_fu_883_p1 = empty_83_fu_877_p2[4:0];

assign trunc_ln594_fu_2122_p1 = f_x_msb_2_table_V_q0[40:0];

assign trunc_ln5_fu_1006_p4 = {{add_ln36_fu_1001_p2[13:1]}};

assign trunc_ln66_fu_1204_p1 = select_ln66_2_fu_1191_p3[2:0];

assign trunc_ln74_fu_1444_p1 = grp_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_fu_504_s_V_15_out[14:0];

assign trunc_ln838_fu_2027_p1 = grp_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_fu_537_s_V_18_out[13:0];

assign x_wide_fu_2039_p3 = {{select_ln69_1_fu_2031_p3}, {6'd0}};

assign xor_ln115_fu_1648_p2 = (icmp_ln117_fu_1568_p2 ^ 1'd1);

assign xor_ln17_fu_733_p2 = (icmp_ln19_fu_657_p2 ^ 1'd1);

assign xor_ln66_fu_1216_p2 = (icmp_ln68_fu_1155_p2 ^ 1'd1);

assign y_l_V_fu_2179_p2 = (exp_x_msb_1_V_reg_2735 + zext_ln813_1_fu_2176_p1);

assign zext_ln137_1_fu_1534_p1 = shl_ln137_2_fu_1526_p3;

assign zext_ln137_2_fu_1884_p1 = select_ln65_2_fu_1876_p3;

assign zext_ln137_3_fu_1742_p1 = tmp5_fu_1732_p4;

assign zext_ln137_4_fu_1694_p1 = shl_ln137_1_mid1_fu_1686_p3;

assign zext_ln137_5_fu_1706_p1 = shl_ln137_2_mid1_fu_1698_p3;

assign zext_ln137_6_fu_1892_p1 = $unsigned(sext_ln137_fu_1889_p1);

assign zext_ln137_fu_1522_p1 = shl_ln137_1_fu_1514_p3;

assign zext_ln167_1_fu_2312_p1 = select_ln147_reg_2690;

assign zext_ln167_2_fu_2321_p1 = add_ln167_fu_2315_p2;

assign zext_ln167_fu_2302_p1 = tmp_18_fu_2295_p3;

assign zext_ln17_1_fu_699_p1 = p_shl_cast_mid2_v_fu_691_p3;

assign zext_ln17_fu_679_p1 = select_ln17_1_fu_671_p3;

assign zext_ln21_fu_817_p1 = select_ln19_fu_763_p3;

assign zext_ln25_fu_864_p1 = i_reg_454;

assign zext_ln32_fu_903_p1 = tmp_13_fu_895_p3;

assign zext_ln36_1_fu_626_p1 = shl_ln36_2_fu_618_p3;

assign zext_ln36_2_fu_984_p1 = select_ln65_fu_976_p3;

assign zext_ln36_3_fu_997_p1 = tmp2_fu_989_p4;

assign zext_ln36_4_fu_779_p1 = shl_ln36_1_mid1_fu_771_p3;

assign zext_ln36_5_fu_791_p1 = shl_ln36_2_mid1_fu_783_p3;

assign zext_ln36_6_fu_1020_p1 = $unsigned(sext_ln36_fu_1016_p1);

assign zext_ln36_fu_614_p1 = shl_ln36_1_fu_606_p3;

assign zext_ln541_1_fu_2094_p1 = p_Result_6_fu_2071_p3;

assign zext_ln541_fu_2089_p1 = tmp_15_fu_2079_p4;

assign zext_ln66_fu_1199_p1 = select_ln66_2_fu_1191_p3;

assign zext_ln813_1_fu_2176_p1 = trunc_ln813_1_reg_2740;

assign zext_ln813_2_fu_2113_p1 = tmp_15_reg_2720;

assign zext_ln813_fu_2109_p1 = f_x_msb_2_h_V_fu_2099_p4;

assign zext_ln88_1_fu_1121_p1 = shl_ln88_2_fu_1113_p3;

assign zext_ln88_2_fu_1462_p1 = select_ln65_1_fu_1454_p3;

assign zext_ln88_3_fu_1310_p1 = tmp4_fu_1300_p4;

assign zext_ln88_4_fu_1262_p1 = shl_ln88_1_mid1_fu_1254_p3;

assign zext_ln88_5_fu_1274_p1 = shl_ln88_2_mid1_fu_1266_p3;

assign zext_ln88_6_fu_1470_p1 = $unsigned(sext_ln88_fu_1467_p1);

assign zext_ln88_fu_1109_p1 = shl_ln88_1_fu_1101_p3;

always @ (posedge ap_clk) begin
    zext_ln17_reg_2420[4:3] <= 2'b00;
    zext_ln17_1_reg_2430[2:0] <= 3'b000;
    zext_ln17_1_reg_2430[5] <= 1'b0;
    select_ln19_1_reg_2447[4:0] <= 5'b00000;
    sub_ln32_reg_2506[1:0] <= 2'b00;
    select_ln66_1_reg_2534[1:0] <= 2'b00;
    add_ln83_2_reg_2611[2:0] <= 3'b000;
    select_ln115_1_reg_2619[2:0] <= 3'b000;
    select_ln115_1_reg_2619[5] <= 1'b0;
    add_ln132_2_reg_2677[3:0] <= 4'b0000;
    shl_ln162_mid_reg_2715[2:0] <= 3'b000;
end

endmodule //denoiser_top_inference
