// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module denoiser_top_inference_Pipeline_loop_kw_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_V_1,
        add_ln30,
        sub_ln32,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        input_r_address1,
        input_r_ce1,
        input_r_q1,
        brmerge_not,
        empty,
        zext_ln21,
        s_V_13_out,
        s_V_13_out_ap_vld,
        s_V_14_out,
        s_V_14_out_ap_vld,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_pp0_stage0 = 5'd2;
parameter    ap_ST_fsm_pp0_stage1 = 5'd4;
parameter    ap_ST_fsm_state8 = 5'd8;
parameter    ap_ST_fsm_state9 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] s_V_1;
input  [5:0] add_ln30;
input  [9:0] sub_ln32;
output  [9:0] input_r_address0;
output   input_r_ce0;
input  [15:0] input_r_q0;
output  [9:0] input_r_address1;
output   input_r_ce1;
input  [15:0] input_r_q1;
input  [0:0] brmerge_not;
input  [5:0] empty;
input  [4:0] zext_ln21;
output  [15:0] s_V_13_out;
output   s_V_13_out_ap_vld;
output  [15:0] s_V_14_out;
output   s_V_14_out_ap_vld;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg input_r_ce1;
reg[15:0] s_V_13_out;
reg s_V_13_out_ap_vld;
reg s_V_14_out_ap_vld;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [5:0] conv1_kernel_V_address0;
reg    conv1_kernel_V_ce0;
wire  signed [9:0] conv1_kernel_V_q0;
wire   [5:0] zext_ln21_cast_fu_202_p1;
reg   [5:0] zext_ln21_cast_reg_478;
wire   [0:0] icmp_ln27_fu_219_p2;
reg   [0:0] icmp_ln27_reg_483;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln27_reg_483_pp0_iter1_reg;
reg   [0:0] icmp_ln27_reg_483_pp0_iter2_reg;
wire   [0:0] icmp_ln31_fu_267_p2;
reg   [0:0] icmp_ln31_reg_492;
wire   [0:0] icmp_ln27_1_fu_293_p2;
reg   [0:0] icmp_ln27_1_reg_502;
reg   [0:0] icmp_ln27_1_reg_502_pp0_iter1_reg;
reg   [0:0] icmp_ln27_1_reg_502_pp0_iter2_reg;
wire   [0:0] icmp_ln31_1_fu_318_p2;
reg   [0:0] icmp_ln31_1_reg_511;
wire   [5:0] add_ln33_1_fu_324_p2;
reg   [5:0] add_ln33_1_reg_516;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
wire    ap_block_state7_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
wire   [15:0] val_V_4_fu_364_p3;
reg  signed [15:0] val_V_4_reg_531;
reg   [15:0] grp_load_fu_198_p1;
reg   [15:0] lhs_load_reg_551;
reg    ap_enable_reg_pp0_iter1;
wire   [15:0] s_V_2_fu_391_p4;
reg   [15:0] s_V_2_reg_561;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage1_subdone;
reg    ap_predicate_tran6to8_state3;
reg    ap_condition_pp0_flush_enable;
wire    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_UnifiedRetVal_phi_fu_190_p4;
reg   [0:0] UnifiedRetVal_reg_186;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln32_fu_247_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1271_fu_278_p1;
wire   [63:0] zext_ln32_1_fu_313_p1;
wire   [63:0] zext_ln1271_1_fu_372_p1;
wire    ap_block_pp0_stage1;
reg   [15:0] lhs_fu_82;
reg   [15:0] ap_sig_allocacmp_lhs_load;
reg   [2:0] j_fu_86;
wire   [2:0] add_ln27_fu_329_p2;
wire   [5:0] j_cast87_fu_229_p1;
wire   [5:0] add_ln30_1_fu_233_p2;
wire  signed [9:0] sext_ln32_fu_238_p1;
wire   [9:0] add_ln32_fu_242_p2;
wire   [1:0] empty_63_fu_225_p1;
wire   [1:0] add_ln31_1_fu_252_p2;
wire  signed [5:0] sext_ln31_fu_258_p1;
wire   [5:0] add_ln31_fu_262_p2;
wire   [5:0] add_ln33_fu_273_p2;
wire   [1:0] or_ln27_fu_283_p2;
wire   [5:0] zext_ln23_fu_289_p1;
wire  signed [5:0] add_ln30_2_fu_299_p2;
wire  signed [9:0] sext_ln32_1_fu_304_p1;
wire   [9:0] add_ln32_1_fu_308_p2;
wire   [0:0] and_ln31_fu_340_p2;
wire  signed [15:0] val_V_5_fu_344_p3;
wire   [0:0] and_ln31_1_fu_360_p2;
wire  signed [25:0] s_V_2_fu_391_p1;
wire   [25:0] grp_fu_422_p3;
wire  signed [25:0] s_V_fu_408_p1;
wire   [25:0] grp_fu_431_p3;
wire   [25:0] grp_fu_422_p2;
wire   [25:0] grp_fu_431_p2;
reg   [0:0] ap_return_preg;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg   [1:0] ap_exit_tran_regpp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_return_preg = 1'd0;
end

denoiser_top_inference_Pipeline_loop_kw_1_conv1_kernel_V_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
conv1_kernel_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_kernel_V_address0),
    .ce0(conv1_kernel_V_ce0),
    .q0(conv1_kernel_V_q0)
);

denoiser_top_mac_muladd_10s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_10s_16s_26ns_26_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv1_kernel_V_q0),
    .din1(val_V_5_fu_344_p3),
    .din2(grp_fu_422_p2),
    .ce(1'b1),
    .dout(grp_fu_422_p3)
);

denoiser_top_mac_muladd_10s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_10s_16s_26ns_26_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv1_kernel_V_q0),
    .din1(val_V_4_reg_531),
    .din2(grp_fu_431_p2),
    .ce(1'b1),
    .dout(grp_fu_431_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_190_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_reg_483 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        UnifiedRetVal_reg_186 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        UnifiedRetVal_reg_186 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((icmp_ln27_reg_483 == 1'd0)) begin
                        ap_exit_tran_regpp0[0] <= 1'b1;
        end else if ((ap_predicate_tran6to8_state3 == 1'b1)) begin
                        ap_exit_tran_regpp0[0] <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_fu_86 <= 3'd0;
    end else if (((icmp_ln27_1_fu_293_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln27_fu_219_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_86 <= add_ln27_fu_329_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        lhs_fu_82 <= s_V_1;
    end else if (((icmp_ln27_1_reg_502_pp0_iter2_reg == 1'd0) & (icmp_ln27_reg_483_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lhs_fu_82 <= {{s_V_fu_408_p1[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_1_fu_293_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln27_fu_219_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln33_1_reg_516 <= add_ln33_1_fu_324_p2;
        icmp_ln31_1_reg_511 <= icmp_ln31_1_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln27_fu_219_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln27_1_reg_502 <= icmp_ln27_1_fu_293_p2;
        icmp_ln31_reg_492 <= icmp_ln31_fu_267_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln27_1_reg_502_pp0_iter1_reg <= icmp_ln27_1_reg_502;
        icmp_ln27_1_reg_502_pp0_iter2_reg <= icmp_ln27_1_reg_502_pp0_iter1_reg;
        icmp_ln27_reg_483_pp0_iter1_reg <= icmp_ln27_reg_483;
        icmp_ln27_reg_483_pp0_iter2_reg <= icmp_ln27_reg_483_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln27_reg_483 <= icmp_ln27_fu_219_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_reg_483_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        lhs_load_reg_551 <= grp_load_fu_198_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_reg_483_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        s_V_2_reg_561 <= {{s_V_2_fu_391_p1[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_1_reg_502 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln27_reg_483 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        val_V_4_reg_531 <= val_V_4_fu_364_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        zext_ln21_cast_reg_478[4 : 0] <= zext_ln21_cast_fu_202_p1[4 : 0];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & ((icmp_ln27_reg_483 == 1'd0) | (ap_predicate_tran6to8_state3 == 1'b1)))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_483 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_UnifiedRetVal_phi_fu_190_p4 = 1'd0;
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_190_p4 = UnifiedRetVal_reg_186;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_190_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((icmp_ln27_1_reg_502_pp0_iter2_reg == 1'd0) & (icmp_ln27_reg_483_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_lhs_load = {{s_V_fu_408_p1[25:10]}};
    end else begin
        ap_sig_allocacmp_lhs_load = lhs_fu_82;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            conv1_kernel_V_address0 = zext_ln1271_1_fu_372_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            conv1_kernel_V_address0 = zext_ln1271_fu_278_p1;
        end else begin
            conv1_kernel_V_address0 = 'bx;
        end
    end else begin
        conv1_kernel_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        conv1_kernel_V_ce0 = 1'b1;
    end else begin
        conv1_kernel_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_load_fu_198_p1 = lhs_fu_82;
    end else if (((icmp_ln27_reg_483_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        grp_load_fu_198_p1 = ap_sig_allocacmp_lhs_load;
    end else begin
        grp_load_fu_198_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce1 = 1'b1;
    end else begin
        input_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        s_V_13_out = grp_load_fu_198_p1;
    end else if (((icmp_ln27_reg_483 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        s_V_13_out = lhs_load_reg_551;
    end else begin
        s_V_13_out = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln27_reg_483 == 1'd1) & (1'b1 == ap_CS_fsm_state8)))) begin
        s_V_13_out_ap_vld = 1'b1;
    end else begin
        s_V_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_483 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        s_V_14_out_ap_vld = 1'b1;
    end else begin
        s_V_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_exit_tran_regpp0 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_exit_tran_regpp0 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln27_fu_329_p2 = (j_fu_86 + 3'd2);

assign add_ln30_1_fu_233_p2 = (j_cast87_fu_229_p1 + add_ln30);

assign add_ln30_2_fu_299_p2 = (zext_ln23_fu_289_p1 + add_ln30);

assign add_ln31_1_fu_252_p2 = ($signed(empty_63_fu_225_p1) + $signed(2'd3));

assign add_ln31_fu_262_p2 = ($signed(sext_ln31_fu_258_p1) + $signed(zext_ln21_cast_reg_478));

assign add_ln32_1_fu_308_p2 = ($signed(sub_ln32) + $signed(sext_ln32_1_fu_304_p1));

assign add_ln32_fu_242_p2 = ($signed(sub_ln32) + $signed(sext_ln32_fu_238_p1));

assign add_ln33_1_fu_324_p2 = (zext_ln23_fu_289_p1 + empty);

assign add_ln33_fu_273_p2 = (j_cast87_fu_229_p1 + empty);

assign and_ln31_1_fu_360_p2 = (icmp_ln31_1_reg_511 & brmerge_not);

assign and_ln31_fu_340_p2 = (icmp_ln31_reg_492 & brmerge_not);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_tran6to8_state3 = ((icmp_ln27_1_reg_502 == 1'd1) & (icmp_ln27_reg_483 == 1'd1));
end

assign empty_63_fu_225_p1 = j_fu_86[1:0];

assign grp_fu_422_p2 = {{grp_load_fu_198_p1}, {10'd0}};

assign grp_fu_431_p2 = {{s_V_2_fu_391_p4}, {10'd0}};

assign icmp_ln27_1_fu_293_p2 = ((or_ln27_fu_283_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_219_p2 = ((j_fu_86 < 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln31_1_fu_318_p2 = ((add_ln30_2_fu_299_p2 < 6'd28) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_267_p2 = ((add_ln31_fu_262_p2 < 6'd28) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln32_1_fu_313_p1;

assign input_r_address1 = zext_ln32_fu_247_p1;

assign j_cast87_fu_229_p1 = j_fu_86;

assign or_ln27_fu_283_p2 = (empty_63_fu_225_p1 | 2'd1);

assign s_V_14_out = s_V_2_reg_561;

assign s_V_2_fu_391_p1 = grp_fu_422_p3;

assign s_V_2_fu_391_p4 = {{s_V_2_fu_391_p1[25:10]}};

assign s_V_fu_408_p1 = grp_fu_431_p3;

assign sext_ln31_fu_258_p1 = $signed(add_ln31_1_fu_252_p2);

assign sext_ln32_1_fu_304_p1 = add_ln30_2_fu_299_p2;

assign sext_ln32_fu_238_p1 = $signed(add_ln30_1_fu_233_p2);

assign val_V_4_fu_364_p3 = ((and_ln31_1_fu_360_p2[0:0] == 1'b1) ? input_r_q0 : 16'd0);

assign val_V_5_fu_344_p3 = ((and_ln31_fu_340_p2[0:0] == 1'b1) ? input_r_q1 : 16'd0);

assign zext_ln1271_1_fu_372_p1 = add_ln33_1_reg_516;

assign zext_ln1271_fu_278_p1 = add_ln33_fu_273_p2;

assign zext_ln21_cast_fu_202_p1 = zext_ln21;

assign zext_ln23_fu_289_p1 = or_ln27_fu_283_p2;

assign zext_ln32_1_fu_313_p1 = add_ln32_1_fu_308_p2;

assign zext_ln32_fu_247_p1 = add_ln32_fu_242_p2;

always @ (posedge ap_clk) begin
    zext_ln21_cast_reg_478[5] <= 1'b0;
    ap_exit_tran_regpp0[1] <= 1'b0;
end

endmodule //denoiser_top_inference_Pipeline_loop_kw_1
