// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module denoiser_top_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        select_ln115_2,
        select_ln117_2,
        select_ln117,
        zext_ln115,
        cmp27_i431_not_mid1258,
        cmp29_i433_not_mid1260,
        zext_ln132_3,
        d_address0,
        d_ce0,
        d_q0,
        d_address1,
        d_ce1,
        d_q1,
        s_V_16_out,
        s_V_16_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] select_ln115_2;
input  [4:0] select_ln117_2;
input  [4:0] select_ln117;
input  [7:0] zext_ln115;
input  [0:0] cmp27_i431_not_mid1258;
input  [0:0] cmp29_i433_not_mid1260;
input  [12:0] zext_ln132_3;
output  [13:0] d_address0;
output   d_ce0;
input  [15:0] d_q0;
output  [13:0] d_address1;
output   d_ce1;
input  [15:0] d_q1;
output  [15:0] s_V_16_out;
output   s_V_16_out_ap_vld;

reg ap_idle;
reg d_ce0;
reg d_ce1;
reg s_V_16_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln123_reg_1148;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [8:0] conv3_kernel_V_address0;
reg    conv3_kernel_V_ce0;
wire  signed [11:0] conv3_kernel_V_q0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln123_fu_460_p2;
reg   [0:0] icmp_ln123_reg_1148_pp0_iter1_reg;
wire   [0:0] select_ln125_2_fu_760_p3;
reg   [0:0] select_ln125_2_reg_1152;
wire   [8:0] add_ln133_4_fu_957_p2;
reg   [8:0] add_ln133_4_reg_1173;
wire    ap_block_pp0_stage1_11001;
wire   [15:0] val_V_16_fu_1023_p3;
reg  signed [15:0] val_V_16_reg_1188;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln132_fu_864_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1271_fu_907_p1;
wire   [63:0] zext_ln132_1_fu_936_p1;
wire   [63:0] zext_ln1271_3_fu_1030_p1;
wire    ap_block_pp0_stage1;
reg   [15:0] lhs_fu_132;
reg   [15:0] ap_sig_allocacmp_lhs_load_3;
wire    ap_loop_init;
reg   [3:0] k_fu_136;
wire   [3:0] add_ln127_fu_963_p2;
reg   [3:0] ap_sig_allocacmp_k_load;
reg   [1:0] j_fu_140;
wire   [1:0] select_ln125_1_fu_698_p3;
reg   [1:0] ap_sig_allocacmp_j_3;
reg   [4:0] indvar_flatten222_fu_144;
wire   [4:0] select_ln125_4_fu_975_p3;
reg   [4:0] ap_sig_allocacmp_indvar_flatten222_load;
reg   [1:0] i_fu_148;
wire   [1:0] select_ln123_7_fu_676_p3;
reg   [1:0] ap_sig_allocacmp_i_2;
reg   [5:0] indvar_flatten282_fu_152;
wire   [5:0] add_ln123_2_fu_466_p2;
reg   [5:0] ap_sig_allocacmp_indvar_flatten282_load;
wire    ap_block_pp0_stage1_01001;
wire  signed [13:0] zext_ln132_3_cast_fu_251_p1;
wire   [4:0] zext_ln123_fu_302_p1;
wire   [4:0] empty_fu_306_p2;
wire   [5:0] p_cast119_fu_312_p1;
wire   [3:0] p_shl1_fu_322_p3;
wire   [4:0] p_shl26_cast_fu_330_p1;
wire   [5:0] empty_69_fu_316_p2;
wire   [11:0] shl_ln132_2_fu_360_p3;
wire   [14:0] shl_ln132_1_fu_352_p3;
wire  signed [14:0] sext_ln132_fu_368_p1;
wire   [4:0] zext_ln125_fu_378_p1;
wire   [4:0] empty_71_fu_382_p2;
wire   [5:0] p_cast127_fu_388_p1;
wire   [5:0] empty_72_fu_392_p2;
wire   [0:0] cmp25_i429_not_fu_346_p2;
wire   [0:0] cmp27_i431_not_fu_398_p2;
wire   [0:0] cmp24_i427_not_fu_340_p2;
wire   [0:0] cmp29_i433_not_fu_404_p2;
wire   [0:0] tmp29_fu_416_p2;
wire   [0:0] tmp28_fu_410_p2;
wire   [9:0] shl_ln3_fu_428_p3;
wire  signed [12:0] sext_ln132_1_fu_436_p1;
wire   [12:0] add_ln132_fu_440_p2;
wire  signed [13:0] sext_ln132_2_fu_446_p1;
wire   [14:0] zext_ln132_2_fu_450_p1;
wire   [14:0] sub_ln132_fu_372_p2;
wire   [0:0] icmp_ln125_fu_484_p2;
wire   [1:0] add_ln123_fu_478_p2;
wire   [4:0] zext_ln123_1_fu_506_p1;
wire   [4:0] p_mid1240_fu_510_p2;
wire   [5:0] p_cast119_mid1_fu_516_p1;
wire   [3:0] p_shl26_mid1_fu_526_p3;
wire   [4:0] p_shl26_cast_mid1_fu_534_p1;
wire   [0:0] cmp24_i427_not_mid1_fu_544_p2;
wire   [5:0] p_mid1242_fu_520_p2;
wire   [0:0] cmp25_i429_not_mid1_fu_558_p2;
wire   [11:0] shl_ln132_2_mid1_fu_580_p3;
wire   [14:0] shl_ln132_1_mid1_fu_572_p3;
wire  signed [14:0] sext_ln132_3_fu_588_p1;
wire   [14:0] sub_ln132_1_fu_592_p2;
wire   [4:0] p_mid1244_fu_538_p2;
wire   [4:0] empty_70_fu_334_p2;
wire   [4:0] select_ln123_5_fu_606_p3;
wire  signed [8:0] sext_ln123_fu_614_p1;
wire   [8:0] zext_ln115_cast_fu_259_p1;
wire   [0:0] tmp29_mid1264_fu_630_p2;
wire   [0:0] tmp28_mid1262_fu_624_p2;
wire   [0:0] brmerge88_mid1266_fu_636_p2;
wire   [0:0] brmerge88_fu_422_p2;
wire   [14:0] zext_ln132_3_cast_cast_fu_255_p1;
wire   [0:0] tmp_fu_656_p3;
wire   [0:0] xor_ln127_fu_664_p2;
wire   [1:0] select_ln123_fu_490_p3;
wire   [0:0] or_ln123_fu_670_p2;
wire   [3:0] select_ln123_1_fu_498_p3;
wire   [1:0] add_ln125_fu_684_p2;
wire   [4:0] zext_ln125_2_fu_710_p1;
wire   [4:0] p_mid1218_fu_714_p2;
wire   [5:0] p_cast127_mid1_fu_720_p1;
wire   [5:0] p_mid1220_fu_724_p2;
wire   [0:0] select_ln123_3_fu_564_p3;
wire   [0:0] cmp27_i431_not_mid1_fu_730_p2;
wire   [0:0] select_ln123_2_fu_550_p3;
wire   [0:0] cmp29_i433_not_mid1_fu_736_p2;
wire   [0:0] tmp29_mid1_fu_748_p2;
wire   [0:0] tmp28_mid1_fu_742_p2;
wire   [0:0] select_ln123_6_fu_642_p3;
wire   [0:0] brmerge88_mid1_fu_754_p2;
wire   [9:0] shl_ln132_mid1_fu_768_p3;
wire  signed [12:0] sext_ln132_4_fu_776_p1;
wire   [12:0] add_ln132_3_fu_780_p2;
wire  signed [13:0] sext_ln132_5_fu_786_p1;
wire   [14:0] zext_ln132_4_fu_790_p1;
wire   [14:0] select_ln123_4_fu_598_p3;
wire   [3:0] select_ln125_fu_690_p3;
wire   [14:0] add_ln132_2_fu_650_p2;
wire   [14:0] add_ln132_1_fu_454_p2;
wire   [10:0] tmp_s_fu_810_p4;
wire   [10:0] tmp_5_fu_820_p4;
wire   [14:0] add_ln132_4_fu_794_p2;
wire   [10:0] select_ln123_8_fu_830_p3;
wire   [10:0] tmp_6_fu_838_p4;
wire   [10:0] select_ln125_3_fu_848_p3;
wire   [2:0] trunc_ln132_fu_800_p1;
wire   [13:0] lshr_ln5_fu_856_p3;
wire   [1:0] tmp_7_fu_869_p4;
wire   [5:0] add_ln133_7_fu_879_p3;
wire   [6:0] zext_ln125_1_fu_706_p1;
wire   [6:0] zext_ln133_fu_887_p1;
wire   [6:0] add_ln133_fu_891_p2;
wire   [8:0] zext_ln133_1_fu_897_p1;
wire   [8:0] add_ln123_1_fu_618_p2;
wire   [8:0] add_ln133_1_fu_901_p2;
wire   [3:0] shl_ln132_fu_804_p2;
wire   [3:0] or_ln132_fu_912_p2;
wire   [2:0] tmp_8_fu_918_p4;
wire   [13:0] lshr_ln132_1_fu_928_p3;
wire   [6:0] add_ln133_2_fu_941_p2;
wire   [6:0] add_ln133_3_fu_947_p2;
wire   [8:0] zext_ln133_2_fu_953_p1;
wire   [4:0] add_ln125_1_fu_969_p2;
wire  signed [15:0] val_V_15_fu_1008_p3;
wire  signed [25:0] tmp_9_fu_1052_p1;
wire   [25:0] grp_fu_1087_p3;
wire   [15:0] tmp_9_fu_1052_p4;
wire  signed [25:0] s_V_fu_1069_p1;
wire   [25:0] grp_fu_1096_p3;
wire   [25:0] grp_fu_1087_p2;
wire   [25:0] grp_fu_1096_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

denoiser_top_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_conv3_kernel_V_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 288 ),
    .AddressWidth( 9 ))
conv3_kernel_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv3_kernel_V_address0),
    .ce0(conv3_kernel_V_ce0),
    .q0(conv3_kernel_V_q0)
);

denoiser_top_mac_muladd_12s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_12s_16s_26ns_26_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv3_kernel_V_q0),
    .din1(val_V_15_fu_1008_p3),
    .din2(grp_fu_1087_p2),
    .ce(1'b1),
    .dout(grp_fu_1087_p3)
);

denoiser_top_mac_muladd_12s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_12s_16s_26ns_26_4_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv3_kernel_V_q0),
    .din1(val_V_16_reg_1188),
    .din2(grp_fu_1096_p2),
    .ce(1'b1),
    .dout(grp_fu_1096_p3)
);

denoiser_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_460_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_148 <= select_ln123_7_fu_676_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_148 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_460_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten222_fu_144 <= select_ln125_4_fu_975_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten222_fu_144 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_460_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten282_fu_152 <= add_ln123_2_fu_466_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten282_fu_152 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_460_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_140 <= select_ln125_1_fu_698_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_140 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_460_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_136 <= add_ln127_fu_963_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_136 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        lhs_fu_132 <= select_ln115_2;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        lhs_fu_132 <= {{s_V_fu_1069_p1[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln123_fu_460_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln133_4_reg_1173 <= add_ln133_4_fu_957_p2;
        select_ln125_2_reg_1152 <= select_ln125_2_fu_760_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln123_reg_1148 <= icmp_ln123_fu_460_p2;
        icmp_ln123_reg_1148_pp0_iter1_reg <= icmp_ln123_reg_1148;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln123_reg_1148 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        val_V_16_reg_1188 <= val_V_16_fu_1023_p3;
    end
end

always @ (*) begin
    if (((icmp_ln123_reg_1148 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 2'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten222_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten222_load = indvar_flatten222_fu_144;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten282_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten282_load = indvar_flatten282_fu_152;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_3 = 2'd0;
    end else begin
        ap_sig_allocacmp_j_3 = j_fu_140;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_load = 4'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_lhs_load_3 = {{s_V_fu_1069_p1[25:10]}};
    end else begin
        ap_sig_allocacmp_lhs_load_3 = lhs_fu_132;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            conv3_kernel_V_address0 = zext_ln1271_3_fu_1030_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            conv3_kernel_V_address0 = zext_ln1271_fu_907_p1;
        end else begin
            conv3_kernel_V_address0 = 'bx;
        end
    end else begin
        conv3_kernel_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        conv3_kernel_V_ce0 = 1'b1;
    end else begin
        conv3_kernel_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_ce0 = 1'b1;
    end else begin
        d_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_ce1 = 1'b1;
    end else begin
        d_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln123_reg_1148_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s_V_16_out_ap_vld = 1'b1;
    end else begin
        s_V_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_1_fu_618_p2 = ($signed(sext_ln123_fu_614_p1) + $signed(zext_ln115_cast_fu_259_p1));

assign add_ln123_2_fu_466_p2 = (ap_sig_allocacmp_indvar_flatten282_load + 6'd1);

assign add_ln123_fu_478_p2 = (ap_sig_allocacmp_i_2 + 2'd1);

assign add_ln125_1_fu_969_p2 = (ap_sig_allocacmp_indvar_flatten222_load + 5'd1);

assign add_ln125_fu_684_p2 = (select_ln123_fu_490_p3 + 2'd1);

assign add_ln127_fu_963_p2 = (select_ln125_fu_690_p3 + 4'd2);

assign add_ln132_1_fu_454_p2 = (zext_ln132_2_fu_450_p1 + sub_ln132_fu_372_p2);

assign add_ln132_2_fu_650_p2 = (zext_ln132_3_cast_cast_fu_255_p1 + sub_ln132_1_fu_592_p2);

assign add_ln132_3_fu_780_p2 = ($signed(sext_ln132_4_fu_776_p1) + $signed(13'd4352));

assign add_ln132_4_fu_794_p2 = (zext_ln132_4_fu_790_p1 + select_ln123_4_fu_598_p3);

assign add_ln132_fu_440_p2 = ($signed(sext_ln132_1_fu_436_p1) + $signed(13'd4352));

assign add_ln133_1_fu_901_p2 = (zext_ln133_1_fu_897_p1 + add_ln123_1_fu_618_p2);

assign add_ln133_2_fu_941_p2 = (zext_ln133_fu_887_p1 + 7'd9);

assign add_ln133_3_fu_947_p2 = (add_ln133_2_fu_941_p2 + zext_ln125_1_fu_706_p1);

assign add_ln133_4_fu_957_p2 = (zext_ln133_2_fu_953_p1 + add_ln123_1_fu_618_p2);

assign add_ln133_7_fu_879_p3 = {{tmp_7_fu_869_p4}, {select_ln125_fu_690_p3}};

assign add_ln133_fu_891_p2 = (zext_ln125_1_fu_706_p1 + zext_ln133_fu_887_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign brmerge88_fu_422_p2 = (tmp29_fu_416_p2 | tmp28_fu_410_p2);

assign brmerge88_mid1266_fu_636_p2 = (tmp29_mid1264_fu_630_p2 | tmp28_mid1262_fu_624_p2);

assign brmerge88_mid1_fu_754_p2 = (tmp29_mid1_fu_748_p2 | tmp28_mid1_fu_742_p2);

assign cmp24_i427_not_fu_340_p2 = ((empty_fu_306_p2 == 5'd0) ? 1'b1 : 1'b0);

assign cmp24_i427_not_mid1_fu_544_p2 = ((p_mid1240_fu_510_p2 == 5'd0) ? 1'b1 : 1'b0);

assign cmp25_i429_not_fu_346_p2 = (($signed(empty_69_fu_316_p2) > $signed(6'd27)) ? 1'b1 : 1'b0);

assign cmp25_i429_not_mid1_fu_558_p2 = (($signed(p_mid1242_fu_520_p2) > $signed(6'd27)) ? 1'b1 : 1'b0);

assign cmp27_i431_not_fu_398_p2 = ((empty_71_fu_382_p2 == 5'd0) ? 1'b1 : 1'b0);

assign cmp27_i431_not_mid1_fu_730_p2 = ((p_mid1218_fu_714_p2 == 5'd0) ? 1'b1 : 1'b0);

assign cmp29_i433_not_fu_404_p2 = (($signed(empty_72_fu_392_p2) > $signed(6'd27)) ? 1'b1 : 1'b0);

assign cmp29_i433_not_mid1_fu_736_p2 = (($signed(p_mid1220_fu_724_p2) > $signed(6'd27)) ? 1'b1 : 1'b0);

assign d_address0 = zext_ln132_1_fu_936_p1;

assign d_address1 = zext_ln132_fu_864_p1;

assign empty_69_fu_316_p2 = ($signed(p_cast119_fu_312_p1) + $signed(6'd63));

assign empty_70_fu_334_p2 = (p_shl26_cast_fu_330_p1 - zext_ln123_fu_302_p1);

assign empty_71_fu_382_p2 = (zext_ln125_fu_378_p1 + select_ln117);

assign empty_72_fu_392_p2 = ($signed(p_cast127_fu_388_p1) + $signed(6'd63));

assign empty_fu_306_p2 = (zext_ln123_fu_302_p1 + select_ln117_2);

assign grp_fu_1087_p2 = {{ap_sig_allocacmp_lhs_load_3}, {10'd0}};

assign grp_fu_1096_p2 = {{tmp_9_fu_1052_p4}, {10'd0}};

assign icmp_ln123_fu_460_p2 = ((ap_sig_allocacmp_indvar_flatten282_load == 6'd36) ? 1'b1 : 1'b0);

assign icmp_ln125_fu_484_p2 = ((ap_sig_allocacmp_indvar_flatten222_load == 5'd12) ? 1'b1 : 1'b0);

assign lshr_ln132_1_fu_928_p3 = {{select_ln125_3_fu_848_p3}, {tmp_8_fu_918_p4}};

assign lshr_ln5_fu_856_p3 = {{select_ln125_3_fu_848_p3}, {trunc_ln132_fu_800_p1}};

assign or_ln123_fu_670_p2 = (xor_ln127_fu_664_p2 | icmp_ln125_fu_484_p2);

assign or_ln132_fu_912_p2 = (shl_ln132_fu_804_p2 | 4'd2);

assign p_cast119_fu_312_p1 = empty_fu_306_p2;

assign p_cast119_mid1_fu_516_p1 = p_mid1240_fu_510_p2;

assign p_cast127_fu_388_p1 = empty_71_fu_382_p2;

assign p_cast127_mid1_fu_720_p1 = p_mid1218_fu_714_p2;

assign p_mid1218_fu_714_p2 = (zext_ln125_2_fu_710_p1 + select_ln117);

assign p_mid1220_fu_724_p2 = ($signed(p_cast127_mid1_fu_720_p1) + $signed(6'd63));

assign p_mid1240_fu_510_p2 = (zext_ln123_1_fu_506_p1 + select_ln117_2);

assign p_mid1242_fu_520_p2 = ($signed(p_cast119_mid1_fu_516_p1) + $signed(6'd63));

assign p_mid1244_fu_538_p2 = (p_shl26_cast_mid1_fu_534_p1 - zext_ln123_1_fu_506_p1);

assign p_shl1_fu_322_p3 = {{ap_sig_allocacmp_i_2}, {2'd0}};

assign p_shl26_cast_fu_330_p1 = p_shl1_fu_322_p3;

assign p_shl26_cast_mid1_fu_534_p1 = p_shl26_mid1_fu_526_p3;

assign p_shl26_mid1_fu_526_p3 = {{add_ln123_fu_478_p2}, {2'd0}};

assign s_V_16_out = lhs_fu_132;

assign s_V_fu_1069_p1 = grp_fu_1096_p3;

assign select_ln123_1_fu_498_p3 = ((icmp_ln125_fu_484_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_k_load);

assign select_ln123_2_fu_550_p3 = ((icmp_ln125_fu_484_p2[0:0] == 1'b1) ? cmp24_i427_not_mid1_fu_544_p2 : cmp24_i427_not_fu_340_p2);

assign select_ln123_3_fu_564_p3 = ((icmp_ln125_fu_484_p2[0:0] == 1'b1) ? cmp25_i429_not_mid1_fu_558_p2 : cmp25_i429_not_fu_346_p2);

assign select_ln123_4_fu_598_p3 = ((icmp_ln125_fu_484_p2[0:0] == 1'b1) ? sub_ln132_1_fu_592_p2 : sub_ln132_fu_372_p2);

assign select_ln123_5_fu_606_p3 = ((icmp_ln125_fu_484_p2[0:0] == 1'b1) ? p_mid1244_fu_538_p2 : empty_70_fu_334_p2);

assign select_ln123_6_fu_642_p3 = ((icmp_ln125_fu_484_p2[0:0] == 1'b1) ? brmerge88_mid1266_fu_636_p2 : brmerge88_fu_422_p2);

assign select_ln123_7_fu_676_p3 = ((icmp_ln125_fu_484_p2[0:0] == 1'b1) ? add_ln123_fu_478_p2 : ap_sig_allocacmp_i_2);

assign select_ln123_8_fu_830_p3 = ((icmp_ln125_fu_484_p2[0:0] == 1'b1) ? tmp_s_fu_810_p4 : tmp_5_fu_820_p4);

assign select_ln123_fu_490_p3 = ((icmp_ln125_fu_484_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j_3);

assign select_ln125_1_fu_698_p3 = ((or_ln123_fu_670_p2[0:0] == 1'b1) ? select_ln123_fu_490_p3 : add_ln125_fu_684_p2);

assign select_ln125_2_fu_760_p3 = ((or_ln123_fu_670_p2[0:0] == 1'b1) ? select_ln123_6_fu_642_p3 : brmerge88_mid1_fu_754_p2);

assign select_ln125_3_fu_848_p3 = ((or_ln123_fu_670_p2[0:0] == 1'b1) ? select_ln123_8_fu_830_p3 : tmp_6_fu_838_p4);

assign select_ln125_4_fu_975_p3 = ((icmp_ln125_fu_484_p2[0:0] == 1'b1) ? 5'd1 : add_ln125_1_fu_969_p2);

assign select_ln125_fu_690_p3 = ((or_ln123_fu_670_p2[0:0] == 1'b1) ? select_ln123_1_fu_498_p3 : 4'd0);

assign sext_ln123_fu_614_p1 = $signed(select_ln123_5_fu_606_p3);

assign sext_ln132_1_fu_436_p1 = $signed(shl_ln3_fu_428_p3);

assign sext_ln132_2_fu_446_p1 = $signed(add_ln132_fu_440_p2);

assign sext_ln132_3_fu_588_p1 = $signed(shl_ln132_2_mid1_fu_580_p3);

assign sext_ln132_4_fu_776_p1 = $signed(shl_ln132_mid1_fu_768_p3);

assign sext_ln132_5_fu_786_p1 = $signed(add_ln132_3_fu_780_p2);

assign sext_ln132_fu_368_p1 = $signed(shl_ln132_2_fu_360_p3);

assign shl_ln132_1_fu_352_p3 = {{empty_69_fu_316_p2}, {9'd0}};

assign shl_ln132_1_mid1_fu_572_p3 = {{p_mid1242_fu_520_p2}, {9'd0}};

assign shl_ln132_2_fu_360_p3 = {{empty_69_fu_316_p2}, {6'd0}};

assign shl_ln132_2_mid1_fu_580_p3 = {{p_mid1242_fu_520_p2}, {6'd0}};

assign shl_ln132_fu_804_p2 = select_ln125_fu_690_p3 << 4'd1;

assign shl_ln132_mid1_fu_768_p3 = {{p_mid1220_fu_724_p2}, {4'd0}};

assign shl_ln3_fu_428_p3 = {{empty_72_fu_392_p2}, {4'd0}};

assign sub_ln132_1_fu_592_p2 = ($signed(shl_ln132_1_mid1_fu_572_p3) - $signed(sext_ln132_3_fu_588_p1));

assign sub_ln132_fu_372_p2 = ($signed(shl_ln132_1_fu_352_p3) - $signed(sext_ln132_fu_368_p1));

assign tmp28_fu_410_p2 = (cmp27_i431_not_fu_398_p2 | cmp25_i429_not_fu_346_p2);

assign tmp28_mid1262_fu_624_p2 = (cmp27_i431_not_mid1258 | cmp25_i429_not_mid1_fu_558_p2);

assign tmp28_mid1_fu_742_p2 = (select_ln123_3_fu_564_p3 | cmp27_i431_not_mid1_fu_730_p2);

assign tmp29_fu_416_p2 = (cmp29_i433_not_fu_404_p2 | cmp24_i427_not_fu_340_p2);

assign tmp29_mid1264_fu_630_p2 = (cmp29_i433_not_mid1260 | cmp24_i427_not_mid1_fu_544_p2);

assign tmp29_mid1_fu_748_p2 = (select_ln123_2_fu_550_p3 | cmp29_i433_not_mid1_fu_736_p2);

assign tmp_5_fu_820_p4 = {{add_ln132_1_fu_454_p2[14:4]}};

assign tmp_6_fu_838_p4 = {{add_ln132_4_fu_794_p2[14:4]}};

assign tmp_7_fu_869_p4 = {{select_ln125_fu_690_p3[2:1]}};

assign tmp_8_fu_918_p4 = {{or_ln132_fu_912_p2[3:1]}};

assign tmp_9_fu_1052_p1 = grp_fu_1087_p3;

assign tmp_9_fu_1052_p4 = {{tmp_9_fu_1052_p1[25:10]}};

assign tmp_fu_656_p3 = ap_sig_allocacmp_k_load[32'd3];

assign tmp_s_fu_810_p4 = {{add_ln132_2_fu_650_p2[14:4]}};

assign trunc_ln132_fu_800_p1 = select_ln125_fu_690_p3[2:0];

assign val_V_15_fu_1008_p3 = ((select_ln125_2_reg_1152[0:0] == 1'b1) ? 16'd0 : d_q1);

assign val_V_16_fu_1023_p3 = ((select_ln125_2_reg_1152[0:0] == 1'b1) ? 16'd0 : d_q0);

assign xor_ln127_fu_664_p2 = (tmp_fu_656_p3 ^ 1'd1);

assign zext_ln115_cast_fu_259_p1 = zext_ln115;

assign zext_ln123_1_fu_506_p1 = add_ln123_fu_478_p2;

assign zext_ln123_fu_302_p1 = ap_sig_allocacmp_i_2;

assign zext_ln125_1_fu_706_p1 = select_ln125_1_fu_698_p3;

assign zext_ln125_2_fu_710_p1 = add_ln125_fu_684_p2;

assign zext_ln125_fu_378_p1 = ap_sig_allocacmp_j_3;

assign zext_ln1271_3_fu_1030_p1 = add_ln133_4_reg_1173;

assign zext_ln1271_fu_907_p1 = add_ln133_1_fu_901_p2;

assign zext_ln132_1_fu_936_p1 = lshr_ln132_1_fu_928_p3;

assign zext_ln132_2_fu_450_p1 = $unsigned(sext_ln132_2_fu_446_p1);

assign zext_ln132_3_cast_cast_fu_255_p1 = $unsigned(zext_ln132_3_cast_fu_251_p1);

assign zext_ln132_3_cast_fu_251_p1 = $signed(zext_ln132_3);

assign zext_ln132_4_fu_790_p1 = $unsigned(sext_ln132_5_fu_786_p1);

assign zext_ln132_fu_864_p1 = lshr_ln5_fu_856_p3;

assign zext_ln133_1_fu_897_p1 = add_ln133_fu_891_p2;

assign zext_ln133_2_fu_953_p1 = add_ln133_3_fu_947_p2;

assign zext_ln133_fu_887_p1 = add_ln133_7_fu_879_p3;

endmodule //denoiser_top_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3
