-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity denoiser_top_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    d_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    d_ce0 : OUT STD_LOGIC;
    d_we0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    d_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    d_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of denoiser_top_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv9_10 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_const_lv11_620 : STD_LOGIC_VECTOR (10 downto 0) := "11000100000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_70 : STD_LOGIC_VECTOR (7 downto 0) := "01110000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv15_3100 : STD_LOGIC_VECTOR (14 downto 0) := "011000100000000";
    constant ap_const_lv15_32C0 : STD_LOGIC_VECTOR (14 downto 0) := "011001011000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln97_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal select_ln97_1_fu_371_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln97_1_reg_792 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln98_1_fu_457_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln98_1_reg_798 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln98_3_fu_491_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln98_3_reg_803 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln105_fu_507_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln105_reg_808 : STD_LOGIC_VECTOR (2 downto 0);
    signal d_load_reg_819 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal lshr_ln2_reg_824 : STD_LOGIC_VECTOR (13 downto 0);
    signal lshr_ln3_reg_829 : STD_LOGIC_VECTOR (13 downto 0);
    signal lshr_ln105_1_reg_834 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln105_6_fu_569_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln102_2_fu_670_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln103_fu_742_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln104_fu_746_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln105_fu_750_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_96 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln99_fu_574_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (3 downto 0);
    signal w_fu_100 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln98_4_fu_499_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_w_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten181_fu_104 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln98_5_fu_586_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten181_load : STD_LOGIC_VECTOR (7 downto 0);
    signal h_fu_108 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln97_5_fu_421_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_h_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten209_fu_112 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln97_3_fu_279_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten209_load : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal shl_ln105_1_fu_191_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln105_2_fu_203_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln105_1_fu_199_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln105_2_fu_211_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1_fu_221_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln102_1_fu_233_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln102_fu_229_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln102_1_fu_241_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_14_fu_251_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln98_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln97_fu_291_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln105_1_mid1_fu_311_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln105_2_mid1_fu_323_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln105_3_fu_319_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln105_4_fu_331_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln102_mid1_fu_341_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln102_1_mid1_fu_353_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln102_3_fu_349_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln102_4_fu_361_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln102_1_fu_365_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln102_fu_245_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln105_3_fu_259_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln103_fu_267_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln99_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln97_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln97_fu_303_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln97_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln98_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln98_fu_429_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_mid_fu_449_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln97_2_fu_379_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln105_3_mid1_fu_465_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln97_3_fu_387_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln98_2_fu_473_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln103_1_fu_485_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln97_4_fu_395_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln98_fu_441_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln105_1_fu_335_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln105_fu_215_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_15_fu_511_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_16_fu_521_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln97_6_fu_531_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_539_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln103_1_fu_481_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln105_fu_549_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln6_fu_555_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln105_fu_565_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln98_1_fu_580_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln97_1_fu_619_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_s_fu_635_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp1_fu_645_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln105_5_fu_629_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln102_fu_654_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal lshr_ln1_fu_660_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln98_3_cast_fu_632_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln103_fu_675_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln97_2_fu_624_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_17_fu_691_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp2_fu_701_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln104_fu_710_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln105_1_fu_726_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component denoiser_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component denoiser_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_start_int = ap_const_logic_1) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    c_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln97_fu_273_p2 = ap_const_lv1_0)) then 
                    c_fu_96 <= add_ln99_fu_574_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_96 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    h_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln97_fu_273_p2 = ap_const_lv1_0)) then 
                    h_fu_108 <= select_ln97_5_fu_421_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    h_fu_108 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten181_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln97_fu_273_p2 = ap_const_lv1_0)) then 
                    indvar_flatten181_fu_104 <= select_ln98_5_fu_586_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten181_fu_104 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten209_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln97_fu_273_p2 = ap_const_lv1_0)) then 
                    indvar_flatten209_fu_112 <= add_ln97_3_fu_279_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten209_fu_112 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    w_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln97_fu_273_p2 = ap_const_lv1_0)) then 
                    w_fu_100 <= select_ln98_4_fu_499_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_100 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                d_load_reg_819 <= d_q0;
                lshr_ln105_1_reg_834 <= add_ln105_1_fu_726_p2(14 downto 1);
                lshr_ln2_reg_824 <= add_ln103_fu_675_p2(14 downto 1);
                lshr_ln3_reg_829 <= add_ln104_fu_710_p2(14 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (icmp_ln97_fu_273_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    select_ln97_1_reg_792(14 downto 7) <= select_ln97_1_fu_371_p3(14 downto 7);
                    select_ln98_1_reg_798(8 downto 5) <= select_ln98_1_fu_457_p3(8 downto 5);
                    select_ln98_3_reg_803(8 downto 5) <= select_ln98_3_fu_491_p3(8 downto 5);
                trunc_ln105_reg_808 <= trunc_ln105_fu_507_p1;
            end if;
        end if;
    end process;
    select_ln97_1_reg_792(6 downto 0) <= "0000000";
    select_ln98_1_reg_798(4 downto 0) <= "00000";
    select_ln98_3_reg_803(4 downto 0) <= "10000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, icmp_ln97_fu_273_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start_int = ap_const_logic_1) and (icmp_ln97_fu_273_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln102_fu_654_p2 <= std_logic_vector(unsigned(tmp1_fu_645_p4) + unsigned(zext_ln105_5_fu_629_p1));
    add_ln103_fu_675_p2 <= std_logic_vector(unsigned(tmp1_fu_645_p4) + unsigned(select_ln98_3_cast_fu_632_p1));
    add_ln104_fu_710_p2 <= std_logic_vector(unsigned(tmp2_fu_701_p4) + unsigned(zext_ln105_5_fu_629_p1));
    add_ln105_1_fu_726_p2 <= std_logic_vector(unsigned(tmp2_fu_701_p4) + unsigned(select_ln98_3_cast_fu_632_p1));
    add_ln105_fu_549_p2 <= std_logic_vector(unsigned(tmp_fu_539_p4) + unsigned(zext_ln103_1_fu_481_p1));
    add_ln97_1_fu_619_p2 <= std_logic_vector(unsigned(select_ln97_1_reg_792) + unsigned(ap_const_lv15_3100));
    add_ln97_2_fu_624_p2 <= std_logic_vector(unsigned(select_ln97_1_reg_792) + unsigned(ap_const_lv15_32C0));
    add_ln97_3_fu_279_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten209_load) + unsigned(ap_const_lv11_1));
    add_ln97_fu_291_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_h_1) + unsigned(ap_const_lv4_1));
    add_ln98_1_fu_580_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten181_load) + unsigned(ap_const_lv8_1));
    add_ln98_fu_429_p2 <= std_logic_vector(unsigned(select_ln97_fu_303_p3) + unsigned(ap_const_lv4_1));
    add_ln99_fu_574_p2 <= std_logic_vector(unsigned(select_ln98_fu_441_p3) + unsigned(ap_const_lv4_1));
    and_ln97_fu_415_p2 <= (xor_ln97_fu_403_p2 and icmp_ln99_fu_409_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage3_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage4_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln97_fu_273_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln97_fu_273_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_state1, c_fu_96, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_96;
        end if; 
    end process;


    ap_sig_allocacmp_h_1_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, h_fu_108)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_h_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_h_1 <= h_fu_108;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten181_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, indvar_flatten181_fu_104)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_indvar_flatten181_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten181_load <= indvar_flatten181_fu_104;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten209_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, indvar_flatten209_fu_112)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_indvar_flatten209_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten209_load <= indvar_flatten209_fu_112;
        end if; 
    end process;


    ap_sig_allocacmp_w_1_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, w_fu_100)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_w_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_w_1 <= w_fu_100;
        end if; 
    end process;


    d_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln97_fu_273_p2, ap_CS_fsm_state5, ap_CS_fsm_state2, zext_ln105_6_fu_569_p1, zext_ln102_2_fu_670_p1, zext_ln103_fu_742_p1, ap_CS_fsm_state3, zext_ln104_fu_746_p1, ap_CS_fsm_state4, zext_ln105_fu_750_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            d_address0 <= zext_ln105_fu_750_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            d_address0 <= zext_ln104_fu_746_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            d_address0 <= zext_ln103_fu_742_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            d_address0 <= zext_ln102_2_fu_670_p1(14 - 1 downto 0);
        elsif (((icmp_ln97_fu_273_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            d_address0 <= zext_ln105_6_fu_569_p1(14 - 1 downto 0);
        else 
            d_address0 <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    d_ce0_assign_proc : process(ap_CS_fsm_state1, icmp_ln97_fu_273_p2, ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_start_int = ap_const_logic_1) and (icmp_ln97_fu_273_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            d_ce0 <= ap_const_logic_1;
        else 
            d_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    d_d0_assign_proc : process(ap_CS_fsm_state5, d_q0, d_load_reg_819, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            d_d0 <= d_load_reg_819;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            d_d0 <= d_q0;
        else 
            d_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    d_we0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            d_we0 <= ap_const_lv2_3;
        else 
            d_we0 <= ap_const_lv2_0;
        end if; 
    end process;

    icmp_ln97_fu_273_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten209_load = ap_const_lv11_620) else "0";
    icmp_ln98_fu_297_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten181_load = ap_const_lv8_70) else "0";
    icmp_ln99_fu_409_p2 <= "1" when (ap_sig_allocacmp_c_load = ap_const_lv4_8) else "0";
    lshr_ln1_fu_660_p4 <= add_ln102_fu_654_p2(14 downto 1);
    or_ln103_1_fu_485_p2 <= (p_mid_fu_449_p3 or ap_const_lv9_10);
    or_ln103_fu_267_p2 <= (tmp_14_fu_251_p3 or ap_const_lv9_10);
    or_ln98_fu_435_p2 <= (icmp_ln98_fu_297_p2 or and_ln97_fu_415_p2);
    p_mid_fu_449_p3 <= (add_ln98_fu_429_p2 & ap_const_lv5_0);
    select_ln97_1_fu_371_p3 <= 
        sub_ln102_1_fu_365_p2 when (icmp_ln98_fu_297_p2(0) = '1') else 
        sub_ln102_fu_245_p2;
    select_ln97_2_fu_379_p3 <= 
        ap_const_lv9_0 when (icmp_ln98_fu_297_p2(0) = '1') else 
        tmp_14_fu_251_p3;
    select_ln97_3_fu_387_p3 <= 
        ap_const_lv8_0 when (icmp_ln98_fu_297_p2(0) = '1') else 
        shl_ln105_3_fu_259_p3;
    select_ln97_4_fu_395_p3 <= 
        ap_const_lv9_10 when (icmp_ln98_fu_297_p2(0) = '1') else 
        or_ln103_fu_267_p2;
    select_ln97_5_fu_421_p3 <= 
        add_ln97_fu_291_p2 when (icmp_ln98_fu_297_p2(0) = '1') else 
        ap_sig_allocacmp_h_1;
    select_ln97_6_fu_531_p3 <= 
        tmp_15_fu_511_p4 when (icmp_ln98_fu_297_p2(0) = '1') else 
        tmp_16_fu_521_p4;
    select_ln97_fu_303_p3 <= 
        ap_const_lv4_0 when (icmp_ln98_fu_297_p2(0) = '1') else 
        ap_sig_allocacmp_w_1;
    select_ln98_1_fu_457_p3 <= 
        p_mid_fu_449_p3 when (and_ln97_fu_415_p2(0) = '1') else 
        select_ln97_2_fu_379_p3;
    select_ln98_2_fu_473_p3 <= 
        shl_ln105_3_mid1_fu_465_p3 when (and_ln97_fu_415_p2(0) = '1') else 
        select_ln97_3_fu_387_p3;
    select_ln98_3_cast_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln98_3_reg_803),15));
    select_ln98_3_fu_491_p3 <= 
        or_ln103_1_fu_485_p2 when (and_ln97_fu_415_p2(0) = '1') else 
        select_ln97_4_fu_395_p3;
    select_ln98_4_fu_499_p3 <= 
        add_ln98_fu_429_p2 when (and_ln97_fu_415_p2(0) = '1') else 
        select_ln97_fu_303_p3;
    select_ln98_5_fu_586_p3 <= 
        ap_const_lv8_1 when (icmp_ln98_fu_297_p2(0) = '1') else 
        add_ln98_1_fu_580_p2;
    select_ln98_fu_441_p3 <= 
        ap_const_lv4_0 when (or_ln98_fu_435_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
        sext_ln105_fu_565_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln6_fu_555_p4),14));

    shl_ln102_1_fu_233_p3 <= (ap_sig_allocacmp_h_1 & ap_const_lv7_0);
    shl_ln102_1_mid1_fu_353_p3 <= (add_ln97_fu_291_p2 & ap_const_lv7_0);
    shl_ln102_mid1_fu_341_p3 <= (add_ln97_fu_291_p2 & ap_const_lv10_0);
    shl_ln105_1_fu_191_p3 <= (ap_sig_allocacmp_h_1 & ap_const_lv8_0);
    shl_ln105_1_mid1_fu_311_p3 <= (add_ln97_fu_291_p2 & ap_const_lv8_0);
    shl_ln105_2_fu_203_p3 <= (ap_sig_allocacmp_h_1 & ap_const_lv5_0);
    shl_ln105_2_mid1_fu_323_p3 <= (add_ln97_fu_291_p2 & ap_const_lv5_0);
    shl_ln105_3_fu_259_p3 <= (ap_sig_allocacmp_w_1 & ap_const_lv4_0);
    shl_ln105_3_mid1_fu_465_p3 <= (add_ln98_fu_429_p2 & ap_const_lv4_0);
    shl_ln1_fu_221_p3 <= (ap_sig_allocacmp_h_1 & ap_const_lv10_0);
    sub_ln102_1_fu_365_p2 <= std_logic_vector(unsigned(zext_ln102_3_fu_349_p1) - unsigned(zext_ln102_4_fu_361_p1));
    sub_ln102_fu_245_p2 <= std_logic_vector(unsigned(zext_ln102_fu_229_p1) - unsigned(zext_ln102_1_fu_241_p1));
    sub_ln105_1_fu_335_p2 <= std_logic_vector(unsigned(zext_ln105_3_fu_319_p1) - unsigned(zext_ln105_4_fu_331_p1));
    sub_ln105_fu_215_p2 <= std_logic_vector(unsigned(zext_ln105_1_fu_199_p1) - unsigned(zext_ln105_2_fu_211_p1));
    tmp1_fu_645_p4 <= ((tmp_s_fu_635_p4 & trunc_ln105_reg_808) & ap_const_lv1_0);
    tmp2_fu_701_p4 <= ((tmp_17_fu_691_p4 & trunc_ln105_reg_808) & ap_const_lv1_0);
    tmp_14_fu_251_p3 <= (ap_sig_allocacmp_w_1 & ap_const_lv5_0);
    tmp_15_fu_511_p4 <= sub_ln105_1_fu_335_p2(12 downto 4);
    tmp_16_fu_521_p4 <= sub_ln105_fu_215_p2(12 downto 4);
    tmp_17_fu_691_p4 <= add_ln97_2_fu_624_p2(14 downto 4);
    tmp_fu_539_p4 <= ((select_ln97_6_fu_531_p3 & trunc_ln105_fu_507_p1) & ap_const_lv1_0);
    tmp_s_fu_635_p4 <= add_ln97_1_fu_619_p2(14 downto 4);
    trunc_ln105_fu_507_p1 <= select_ln98_fu_441_p3(3 - 1 downto 0);
    trunc_ln6_fu_555_p4 <= add_ln105_fu_549_p2(12 downto 1);
    xor_ln97_fu_403_p2 <= (icmp_ln98_fu_297_p2 xor ap_const_lv1_1);
    zext_ln102_1_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln102_1_fu_233_p3),15));
    zext_ln102_2_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_660_p4),64));
    zext_ln102_3_fu_349_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln102_mid1_fu_341_p3),15));
    zext_ln102_4_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln102_1_mid1_fu_353_p3),15));
    zext_ln102_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_221_p3),15));
    zext_ln103_1_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln98_2_fu_473_p3),13));
    zext_ln103_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_reg_824),64));
    zext_ln104_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln3_reg_829),64));
    zext_ln105_1_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln105_1_fu_191_p3),13));
    zext_ln105_2_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln105_2_fu_203_p3),13));
    zext_ln105_3_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln105_1_mid1_fu_311_p3),13));
    zext_ln105_4_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln105_2_mid1_fu_323_p3),13));
    zext_ln105_5_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln98_1_reg_798),15));
    zext_ln105_6_fu_569_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln105_fu_565_p1),64));
    zext_ln105_fu_750_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln105_1_reg_834),64));
end behav;
