# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.runs/design_1_denoiser_top_0_0_synth_1/.Xil/Vivado-18332-MSI/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xck26-sfvc784-2LV-c
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ip/design_1_denoiser_top_0_0/hdl/verilog {
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ip/design_1_denoiser_top_0_0/hdl/verilog {
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_control_s_axi.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_d_RAM_AUTO_1R1W.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_denoiser_top_Pipeline_VITIS_LOOP_18_1.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_denoiser_top_Pipeline_VITIS_LOOP_25_2.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_flow_control_loop_pipe_sequential_init.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_gmem0_m_axi.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_gmem1_m_axi.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_in_buf_V_RAM_AUTO_1R1W.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_conv2_bias_V_ROM_AUTO_1R.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_exp_x_msb_1_table_V_ROM_AUTO_1R.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_f_x_msb_2_table_V_ROM_AUTO_1R.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_conv2_kernel_V_ROM_AUTO_1R.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_conv3_kernel_V_ROM_AUTO_1R.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_conv_out_kernel_V_ROM_bkb.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_Pipeline_loop_kw_1.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_Pipeline_loop_kw_1_conv1_kernel_V_ROM_AUTO_1R.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_46_2_VITIS_LOOP_47_3.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_inference_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2_VITIS_LOOP_99_3.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_mac_muladd_10s_16s_26ns_26_4_1.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_mac_muladd_11s_16s_26ns_26_4_1.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_mac_muladd_12s_16s_26ns_26_4_1.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_mul_50ns_50ns_100_1_1.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_mux_42_16_1_1.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_out_buf8_RAM_AUTO_1R1W.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top_sdiv_34ns_33s_34_38_seq_1.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ipshared/26fe/hdl/verilog/denoiser_top.v
      c:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.gen/sources_1/bd/design_1/ip/design_1_denoiser_top_0_0/synth/design_1_denoiser_top_0_0.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_denoiser_top_0_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Nam_3_HK2_2025_2026/Do_an_1/autoencoder/denoiser/denoiser.runs/design_1_denoiser_top_0_0_synth_1/.Xil/Vivado-18332-MSI/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
