-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity denoiser_top_inference_Pipeline_loop_kw_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_V_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    add_ln30 : IN STD_LOGIC_VECTOR (5 downto 0);
    sub_ln32 : IN STD_LOGIC_VECTOR (9 downto 0);
    input_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_r_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    input_r_ce1 : OUT STD_LOGIC;
    input_r_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    brmerge_not : IN STD_LOGIC_VECTOR (0 downto 0);
    empty : IN STD_LOGIC_VECTOR (5 downto 0);
    zext_ln21 : IN STD_LOGIC_VECTOR (4 downto 0);
    s_V_13_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    s_V_13_out_ap_vld : OUT STD_LOGIC;
    s_V_14_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    s_V_14_out_ap_vld : OUT STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of denoiser_top_inference_Pipeline_loop_kw_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal conv1_kernel_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal conv1_kernel_V_ce0 : STD_LOGIC;
    signal conv1_kernel_V_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln21_cast_fu_202_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln21_cast_reg_478 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln27_fu_219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_483 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln27_reg_483_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_483_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln31_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln31_reg_492 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_1_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_1_reg_502 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_1_reg_502_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_1_reg_502_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln31_1_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln31_1_reg_511 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln33_1_fu_324_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_1_reg_516 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state7_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal val_V_4_fu_364_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal val_V_4_reg_531 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_load_fu_198_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_load_reg_551 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal s_V_2_fu_391_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal s_V_2_reg_561 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_predicate_tran6to8_state3 : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_UnifiedRetVal_phi_fu_190_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal UnifiedRetVal_reg_186 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal zext_ln32_fu_247_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln1271_fu_278_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_1_fu_313_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1271_1_fu_372_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal lhs_fu_82 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_lhs_load : STD_LOGIC_VECTOR (15 downto 0);
    signal j_fu_86 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln27_fu_329_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_cast87_fu_229_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln30_1_fu_233_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln32_fu_238_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln32_fu_242_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_63_fu_225_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln31_1_fu_252_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln31_fu_258_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln31_fu_262_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_fu_273_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln27_fu_283_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln23_fu_289_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln30_2_fu_299_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln32_1_fu_304_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln32_1_fu_308_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln31_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_5_fu_344_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln31_1_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal s_V_2_fu_391_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_422_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal s_V_fu_408_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_431_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_422_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_431_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_exit_tran_regpp0 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component denoiser_top_mac_muladd_10s_16s_26ns_26_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (25 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component denoiser_top_inference_Pipeline_loop_kw_1_conv1_kernel_V_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    conv1_kernel_V_U : component denoiser_top_inference_Pipeline_loop_kw_1_conv1_kernel_V_ROM_AUTO_1R
    generic map (
        DataWidth => 10,
        AddressRange => 36,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => conv1_kernel_V_address0,
        ce0 => conv1_kernel_V_ce0,
        q0 => conv1_kernel_V_q0);

    mac_muladd_10s_16s_26ns_26_4_1_U4 : component denoiser_top_mac_muladd_10s_16s_26ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 10,
        din1_WIDTH => 16,
        din2_WIDTH => 26,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => conv1_kernel_V_q0,
        din1 => val_V_5_fu_344_p3,
        din2 => grp_fu_422_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_422_p3);

    mac_muladd_10s_16s_26ns_26_4_1_U5 : component denoiser_top_mac_muladd_10s_16s_26ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 10,
        din1_WIDTH => 16,
        din2_WIDTH => 26,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => conv1_kernel_V_q0,
        din1 => val_V_4_reg_531,
        din2 => grp_fu_431_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_431_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_190_p4;
                end if; 
            end if;
        end if;
    end process;


    UnifiedRetVal_reg_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln27_reg_483 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                UnifiedRetVal_reg_186 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                UnifiedRetVal_reg_186 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    ap_exit_tran_regpp0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((icmp_ln27_reg_483 = ap_const_lv1_0)) then 
                    ap_exit_tran_regpp0(0) <= '1';
                elsif ((ap_predicate_tran6to8_state3 = ap_const_boolean_1)) then 
                    ap_exit_tran_regpp0(0) <= '0';
                end if;
            end if; 
        end if;
    end process;

    j_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                j_fu_86 <= ap_const_lv3_0;
            elsif (((icmp_ln27_1_fu_293_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln27_fu_219_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_fu_86 <= add_ln27_fu_329_p2;
            end if; 
        end if;
    end process;

    lhs_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                lhs_fu_82 <= s_V_1;
            elsif (((icmp_ln27_1_reg_502_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln27_reg_483_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                lhs_fu_82 <= s_V_fu_408_p1(25 downto 10);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln27_1_fu_293_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln27_fu_219_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln33_1_reg_516 <= add_ln33_1_fu_324_p2;
                icmp_ln31_1_reg_511 <= icmp_ln31_1_fu_318_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln27_fu_219_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln27_1_reg_502 <= icmp_ln27_1_fu_293_p2;
                icmp_ln31_reg_492 <= icmp_ln31_fu_267_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln27_1_reg_502_pp0_iter1_reg <= icmp_ln27_1_reg_502;
                icmp_ln27_1_reg_502_pp0_iter2_reg <= icmp_ln27_1_reg_502_pp0_iter1_reg;
                icmp_ln27_reg_483_pp0_iter1_reg <= icmp_ln27_reg_483;
                icmp_ln27_reg_483_pp0_iter2_reg <= icmp_ln27_reg_483_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln27_reg_483 <= icmp_ln27_fu_219_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln27_reg_483_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                lhs_load_reg_551 <= grp_load_fu_198_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln27_reg_483_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                s_V_2_reg_561 <= s_V_2_fu_391_p1(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln27_1_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln27_reg_483 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                val_V_4_reg_531 <= val_V_4_fu_364_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    zext_ln21_cast_reg_478(4 downto 0) <= zext_ln21_cast_fu_202_p1(4 downto 0);
            end if;
        end if;
    end process;
    zext_ln21_cast_reg_478(5) <= '0';
    ap_exit_tran_regpp0(1) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_exit_tran_regpp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_exit_tran_regpp0 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_exit_tran_regpp0 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln27_fu_329_p2 <= std_logic_vector(unsigned(j_fu_86) + unsigned(ap_const_lv3_2));
    add_ln30_1_fu_233_p2 <= std_logic_vector(unsigned(j_cast87_fu_229_p1) + unsigned(add_ln30));
    add_ln30_2_fu_299_p2 <= std_logic_vector(unsigned(zext_ln23_fu_289_p1) + unsigned(add_ln30));
    add_ln31_1_fu_252_p2 <= std_logic_vector(unsigned(empty_63_fu_225_p1) + unsigned(ap_const_lv2_3));
    add_ln31_fu_262_p2 <= std_logic_vector(signed(sext_ln31_fu_258_p1) + signed(zext_ln21_cast_reg_478));
    add_ln32_1_fu_308_p2 <= std_logic_vector(unsigned(sub_ln32) + unsigned(sext_ln32_1_fu_304_p1));
    add_ln32_fu_242_p2 <= std_logic_vector(unsigned(sub_ln32) + unsigned(sext_ln32_fu_238_p1));
    add_ln33_1_fu_324_p2 <= std_logic_vector(unsigned(zext_ln23_fu_289_p1) + unsigned(empty));
    add_ln33_fu_273_p2 <= std_logic_vector(unsigned(j_cast87_fu_229_p1) + unsigned(empty));
    and_ln31_1_fu_360_p2 <= (icmp_ln31_1_reg_511 and brmerge_not);
    and_ln31_fu_340_p2 <= (icmp_ln31_reg_492 and brmerge_not);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state8 <= ap_CS_fsm(3);
    ap_CS_fsm_state9 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_flush_enable_assign_proc : process(icmp_ln27_reg_483, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_predicate_tran6to8_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and ((icmp_ln27_reg_483 = ap_const_lv1_0) or (ap_predicate_tran6to8_state3 = ap_const_boolean_1)))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_UnifiedRetVal_phi_fu_190_p4_assign_proc : process(icmp_ln27_reg_483, UnifiedRetVal_reg_186, ap_CS_fsm_state8)
    begin
        if (((icmp_ln27_reg_483 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_phi_mux_UnifiedRetVal_phi_fu_190_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_UnifiedRetVal_phi_fu_190_p4 <= UnifiedRetVal_reg_186;
        end if; 
    end process;


    ap_predicate_tran6to8_state3_assign_proc : process(icmp_ln27_reg_483, icmp_ln27_1_reg_502)
    begin
                ap_predicate_tran6to8_state3 <= ((icmp_ln27_1_reg_502 = ap_const_lv1_1) and (icmp_ln27_reg_483 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_UnifiedRetVal_phi_fu_190_p4, ap_CS_fsm_state8, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_return <= ap_phi_mux_UnifiedRetVal_phi_fu_190_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;


    ap_sig_allocacmp_lhs_load_assign_proc : process(icmp_ln27_reg_483_pp0_iter2_reg, icmp_ln27_1_reg_502_pp0_iter2_reg, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage1, lhs_fu_82, s_V_fu_408_p1)
    begin
        if (((icmp_ln27_1_reg_502_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln27_reg_483_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_sig_allocacmp_lhs_load <= s_V_fu_408_p1(25 downto 10);
        else 
            ap_sig_allocacmp_lhs_load <= lhs_fu_82;
        end if; 
    end process;


    conv1_kernel_V_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln1271_fu_278_p1, zext_ln1271_1_fu_372_p1, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                conv1_kernel_V_address0 <= zext_ln1271_1_fu_372_p1(6 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                conv1_kernel_V_address0 <= zext_ln1271_fu_278_p1(6 - 1 downto 0);
            else 
                conv1_kernel_V_address0 <= "XXXXXX";
            end if;
        else 
            conv1_kernel_V_address0 <= "XXXXXX";
        end if; 
    end process;


    conv1_kernel_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            conv1_kernel_V_ce0 <= ap_const_logic_1;
        else 
            conv1_kernel_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    empty_63_fu_225_p1 <= j_fu_86(2 - 1 downto 0);
    grp_fu_422_p2 <= (grp_load_fu_198_p1 & ap_const_lv10_0);
    grp_fu_431_p2 <= (s_V_2_fu_391_p4 & ap_const_lv10_0);

    grp_load_fu_198_p1_assign_proc : process(icmp_ln27_reg_483_pp0_iter1_reg, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, ap_CS_fsm_state9, ap_block_pp0_stage1, lhs_fu_82, ap_sig_allocacmp_lhs_load)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_load_fu_198_p1 <= lhs_fu_82;
        elsif (((icmp_ln27_reg_483_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            grp_load_fu_198_p1 <= ap_sig_allocacmp_lhs_load;
        else 
            grp_load_fu_198_p1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln27_1_fu_293_p2 <= "1" when (or_ln27_fu_283_p2 = ap_const_lv2_3) else "0";
    icmp_ln27_fu_219_p2 <= "1" when (unsigned(j_fu_86) < unsigned(ap_const_lv3_3)) else "0";
    icmp_ln31_1_fu_318_p2 <= "1" when (unsigned(add_ln30_2_fu_299_p2) < unsigned(ap_const_lv6_1C)) else "0";
    icmp_ln31_fu_267_p2 <= "1" when (unsigned(add_ln31_fu_262_p2) < unsigned(ap_const_lv6_1C)) else "0";
    input_r_address0 <= zext_ln32_1_fu_313_p1(10 - 1 downto 0);
    input_r_address1 <= zext_ln32_fu_247_p1(10 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_r_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce1 <= ap_const_logic_1;
        else 
            input_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    j_cast87_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_86),6));
    or_ln27_fu_283_p2 <= (empty_63_fu_225_p1 or ap_const_lv2_1);

    s_V_13_out_assign_proc : process(icmp_ln27_reg_483, grp_load_fu_198_p1, lhs_load_reg_551, ap_CS_fsm_state9, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            s_V_13_out <= grp_load_fu_198_p1;
        elsif (((icmp_ln27_reg_483 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            s_V_13_out <= lhs_load_reg_551;
        else 
            s_V_13_out <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    s_V_13_out_ap_vld_assign_proc : process(icmp_ln27_reg_483, ap_CS_fsm_state9, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((icmp_ln27_reg_483 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8)))) then 
            s_V_13_out_ap_vld <= ap_const_logic_1;
        else 
            s_V_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    s_V_14_out <= s_V_2_reg_561;

    s_V_14_out_ap_vld_assign_proc : process(icmp_ln27_reg_483, ap_CS_fsm_state8)
    begin
        if (((icmp_ln27_reg_483 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            s_V_14_out_ap_vld <= ap_const_logic_1;
        else 
            s_V_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    s_V_2_fu_391_p1 <= grp_fu_422_p3;
    s_V_2_fu_391_p4 <= s_V_2_fu_391_p1(25 downto 10);
    s_V_fu_408_p1 <= grp_fu_431_p3;
        sext_ln31_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln31_1_fu_252_p2),6));

        sext_ln32_1_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln30_2_fu_299_p2),10));

        sext_ln32_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln30_1_fu_233_p2),10));

    val_V_4_fu_364_p3 <= 
        input_r_q0 when (and_ln31_1_fu_360_p2(0) = '1') else 
        ap_const_lv16_0;
    val_V_5_fu_344_p3 <= 
        input_r_q1 when (and_ln31_fu_340_p2(0) = '1') else 
        ap_const_lv16_0;
    zext_ln1271_1_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln33_1_reg_516),64));
    zext_ln1271_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln33_fu_273_p2),64));
    zext_ln21_cast_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln21),6));
    zext_ln23_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln27_fu_283_p2),6));
    zext_ln32_1_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln32_1_fu_308_p2),64));
    zext_ln32_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln32_fu_242_p2),64));
end behav;
