-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity denoiser_top_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    select_ln147_1 : IN STD_LOGIC_VECTOR (4 downto 0);
    select_ln147 : IN STD_LOGIC_VECTOR (4 downto 0);
    cmp23_i72_not_mid1364 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp25_i74_not_mid1366 : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln162_1 : IN STD_LOGIC_VECTOR (8 downto 0);
    d_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    d_ce0 : OUT STD_LOGIC;
    d_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    d_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    d_ce1 : OUT STD_LOGIC;
    d_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    s_V_18_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    s_V_18_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of denoiser_top_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_FF37 : STD_LOGIC_VECTOR (15 downto 0) := "1111111100110111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln153_reg_1110 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal conv_out_kernel_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal conv_out_kernel_V_ce0 : STD_LOGIC;
    signal conv_out_kernel_V_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln153_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln153_reg_1110_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln155_2_fu_726_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln155_2_reg_1114 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln163_3_fu_919_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln163_3_reg_1135 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal val_V_10_fu_985_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal val_V_10_reg_1150 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln162_fu_838_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln1271_fu_867_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln162_1_fu_900_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1271_2_fu_992_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal lhs_fu_124 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_lhs_load_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal k_fu_128 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln157_fu_925_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_k_load : STD_LOGIC_VECTOR (2 downto 0);
    signal j_fu_132 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln155_1_fu_664_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_j_2 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten328_fu_136 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln155_5_fu_937_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten328_load : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_140 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln153_8_fu_642_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten386_fu_144 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln153_1_fu_430_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten386_load : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal zext_ln153_fu_274_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_fu_278_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast114_fu_284_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl2_fu_294_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl30_cast_fu_302_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_64_fu_288_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln162_2_fu_332_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln162_1_fu_324_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln162_fu_340_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln155_fu_350_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_66_fu_354_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast125_fu_360_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_67_fu_364_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal cmp21_i70_not_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp23_i72_not_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp20_i68_not_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp25_i74_not_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp60_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp59_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln4_fu_400_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln162_2_fu_408_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln162_fu_344_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal empty_65_fu_306_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln155_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln153_fu_442_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln153_1_fu_470_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_mid1346_fu_474_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast114_mid1_fu_480_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl30_mid1_fu_490_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl30_cast_mid1_fu_498_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_mid1350_fu_502_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln153_2_fu_508_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal cmp20_i68_not_mid1_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mid1348_fu_484_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal cmp21_i70_not_mid1_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln162_2_mid1_fu_556_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln162_1_mid1_fu_548_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln162_3_fu_564_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln162_1_fu_568_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp60_mid1370_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp59_mid1368_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge98_mid1372_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge98_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln162_1_cast_fu_231_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln163_2_fu_418_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_622_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln157_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln153_fu_454_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln153_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln153_1_fu_462_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln155_fu_650_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln155_2_fu_676_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_mid1324_fu_680_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast125_mid1_fu_686_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_mid1326_fu_690_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln153_4_fu_540_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp23_i72_not_mid1_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln153_3_fu_526_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp25_i74_not_mid1_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp60_mid1_fu_714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp59_mid1_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln153_6_fu_600_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge98_mid1_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln162_mid1_fu_734_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln162_4_fu_742_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln153_5_fu_574_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln153_7_fu_614_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln163_4_fu_752_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln155_3_fu_758_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln155_fu_656_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln162_1_fu_608_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln162_fu_412_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_s_fu_780_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_790_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln162_2_fu_746_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln153_9_fu_800_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_808_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln155_4_fu_818_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln162_fu_770_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln_fu_826_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln162_5_fu_834_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln163_5_fu_843_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln153_fu_516_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln163_fu_851_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln163_fu_855_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln155_1_fu_672_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln163_1_fu_861_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln162_fu_774_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln162_fu_872_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_878_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln162_1_fu_888_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln162_6_fu_896_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal or_ln163_fu_905_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln2_fu_911_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln155_fu_766_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln155_1_fu_931_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_V_9_fu_970_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_1014_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1049_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_4_fu_1014_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal s_V_fu_1031_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1058_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1049_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1058_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component denoiser_top_mac_muladd_11s_16s_26ns_26_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (25 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component denoiser_top_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_conv_out_kernel_V_ROM_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component denoiser_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    conv_out_kernel_V_U : component denoiser_top_inference_Pipeline_loop_kh_out_loop_kw_out_loop_ic_out_conv_out_kernel_V_ROM_bkb
    generic map (
        DataWidth => 11,
        AddressRange => 36,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => conv_out_kernel_V_address0,
        ce0 => conv_out_kernel_V_ce0,
        q0 => conv_out_kernel_V_q0);

    mac_muladd_11s_16s_26ns_26_4_1_U45 : component denoiser_top_mac_muladd_11s_16s_26ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 11,
        din1_WIDTH => 16,
        din2_WIDTH => 26,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => conv_out_kernel_V_q0,
        din1 => val_V_9_fu_970_p3,
        din2 => grp_fu_1049_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1049_p3);

    mac_muladd_11s_16s_26ns_26_4_1_U46 : component denoiser_top_mac_muladd_11s_16s_26ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 11,
        din1_WIDTH => 16,
        din2_WIDTH => 26,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => conv_out_kernel_V_q0,
        din1 => val_V_10_reg_1150,
        din2 => grp_fu_1058_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1058_p3);

    flow_control_loop_pipe_sequential_init_U : component denoiser_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln153_fu_424_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_140 <= select_ln153_8_fu_642_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_140 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten328_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln153_fu_424_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten328_fu_136 <= select_ln155_5_fu_937_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten328_fu_136 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten386_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln153_fu_424_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten386_fu_144 <= add_ln153_1_fu_430_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten386_fu_144 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln153_fu_424_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_132 <= select_ln155_1_fu_664_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_132 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln153_fu_424_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_128 <= add_ln157_fu_925_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_128 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                lhs_fu_124 <= ap_const_lv16_FF37;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                lhs_fu_124 <= s_V_fu_1031_p1(25 downto 10);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln153_fu_424_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln163_3_reg_1135 <= add_ln163_3_fu_919_p2;
                select_ln155_2_reg_1114 <= select_ln155_2_fu_726_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln153_reg_1110 <= icmp_ln153_fu_424_p2;
                icmp_ln153_reg_1110_pp0_iter1_reg <= icmp_ln153_reg_1110;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln153_reg_1110 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                val_V_10_reg_1150 <= val_V_10_fu_985_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln153_1_fu_430_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten386_load) + unsigned(ap_const_lv5_1));
    add_ln153_fu_442_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv2_1));
    add_ln155_1_fu_931_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten328_load) + unsigned(ap_const_lv4_1));
    add_ln155_fu_650_p2 <= std_logic_vector(unsigned(select_ln153_fu_454_p3) + unsigned(ap_const_lv2_1));
    add_ln157_fu_925_p2 <= std_logic_vector(unsigned(select_ln155_fu_656_p3) + unsigned(ap_const_lv3_2));
    add_ln162_1_fu_608_p2 <= std_logic_vector(signed(sext_ln162_1_cast_fu_231_p1) + signed(sub_ln162_1_fu_568_p2));
    add_ln162_2_fu_746_p2 <= std_logic_vector(signed(sext_ln162_4_fu_742_p1) + signed(select_ln153_5_fu_574_p3));
    add_ln162_fu_412_p2 <= std_logic_vector(signed(sext_ln162_2_fu_408_p1) + signed(sub_ln162_fu_344_p2));
    add_ln163_1_fu_861_p2 <= std_logic_vector(unsigned(add_ln163_fu_855_p2) + unsigned(zext_ln155_1_fu_672_p1));
    add_ln163_2_fu_418_p2 <= std_logic_vector(unsigned(empty_65_fu_306_p2) + unsigned(zext_ln155_fu_350_p1));
    add_ln163_3_fu_919_p2 <= std_logic_vector(unsigned(or_ln2_fu_911_p3) + unsigned(sext_ln155_fu_766_p1));
    add_ln163_4_fu_752_p2 <= std_logic_vector(signed(select_ln153_2_fu_508_p3) + signed(zext_ln155_2_fu_676_p1));
    add_ln163_5_fu_843_p3 <= (trunc_ln162_fu_770_p1 & select_ln155_fu_656_p3);
    add_ln163_fu_855_p2 <= std_logic_vector(signed(sext_ln153_fu_516_p1) + signed(zext_ln163_fu_851_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln153_reg_1110)
    begin
        if (((icmp_ln153_reg_1110 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_140)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_140;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten328_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten328_fu_136)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten328_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten328_load <= indvar_flatten328_fu_136;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten386_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten386_fu_144)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten386_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten386_load <= indvar_flatten386_fu_144;
        end if; 
    end process;


    ap_sig_allocacmp_j_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_fu_132)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_2 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_j_2 <= j_fu_132;
        end if; 
    end process;


    ap_sig_allocacmp_k_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_128)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_k_load <= k_fu_128;
        end if; 
    end process;


    ap_sig_allocacmp_lhs_load_2_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, lhs_fu_124, s_V_fu_1031_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_sig_allocacmp_lhs_load_2 <= s_V_fu_1031_p1(25 downto 10);
        else 
            ap_sig_allocacmp_lhs_load_2 <= lhs_fu_124;
        end if; 
    end process;

    brmerge98_fu_394_p2 <= (tmp60_fu_388_p2 or tmp59_fu_382_p2);
    brmerge98_mid1372_fu_594_p2 <= (tmp60_mid1370_fu_588_p2 or tmp59_mid1368_fu_582_p2);
    brmerge98_mid1_fu_720_p2 <= (tmp60_mid1_fu_714_p2 or tmp59_mid1_fu_708_p2);
    cmp20_i68_not_fu_312_p2 <= "1" when (empty_fu_278_p2 = ap_const_lv5_0) else "0";
    cmp20_i68_not_mid1_fu_520_p2 <= "1" when (p_mid1346_fu_474_p2 = ap_const_lv5_0) else "0";
    cmp21_i70_not_fu_318_p2 <= "1" when (signed(empty_64_fu_288_p2) > signed(ap_const_lv6_1B)) else "0";
    cmp21_i70_not_mid1_fu_534_p2 <= "1" when (signed(p_mid1348_fu_484_p2) > signed(ap_const_lv6_1B)) else "0";
    cmp23_i72_not_fu_370_p2 <= "1" when (empty_66_fu_354_p2 = ap_const_lv5_0) else "0";
    cmp23_i72_not_mid1_fu_696_p2 <= "1" when (p_mid1324_fu_680_p2 = ap_const_lv5_0) else "0";
    cmp25_i74_not_fu_376_p2 <= "1" when (signed(empty_67_fu_364_p2) > signed(ap_const_lv6_1B)) else "0";
    cmp25_i74_not_mid1_fu_702_p2 <= "1" when (signed(p_mid1326_fu_690_p2) > signed(ap_const_lv6_1B)) else "0";

    conv_out_kernel_V_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln1271_fu_867_p1, zext_ln1271_2_fu_992_p1, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                conv_out_kernel_V_address0 <= zext_ln1271_2_fu_992_p1(6 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                conv_out_kernel_V_address0 <= zext_ln1271_fu_867_p1(6 - 1 downto 0);
            else 
                conv_out_kernel_V_address0 <= "XXXXXX";
            end if;
        else 
            conv_out_kernel_V_address0 <= "XXXXXX";
        end if; 
    end process;


    conv_out_kernel_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            conv_out_kernel_V_ce0 <= ap_const_logic_1;
        else 
            conv_out_kernel_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    d_address0 <= zext_ln162_1_fu_900_p1(14 - 1 downto 0);
    d_address1 <= zext_ln162_fu_838_p1(14 - 1 downto 0);

    d_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            d_ce0 <= ap_const_logic_1;
        else 
            d_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    d_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            d_ce1 <= ap_const_logic_1;
        else 
            d_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    empty_64_fu_288_p2 <= std_logic_vector(unsigned(p_cast114_fu_284_p1) + unsigned(ap_const_lv6_3F));
    empty_65_fu_306_p2 <= std_logic_vector(unsigned(p_shl30_cast_fu_302_p1) - unsigned(zext_ln153_fu_274_p1));
    empty_66_fu_354_p2 <= std_logic_vector(unsigned(zext_ln155_fu_350_p1) + unsigned(select_ln147));
    empty_67_fu_364_p2 <= std_logic_vector(unsigned(p_cast125_fu_360_p1) + unsigned(ap_const_lv6_3F));
    empty_fu_278_p2 <= std_logic_vector(unsigned(zext_ln153_fu_274_p1) + unsigned(select_ln147_1));
    grp_fu_1049_p2 <= (ap_sig_allocacmp_lhs_load_2 & ap_const_lv10_0);
    grp_fu_1058_p2 <= (tmp_4_fu_1014_p4 & ap_const_lv10_0);
    icmp_ln153_fu_424_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten386_load = ap_const_lv5_12) else "0";
    icmp_ln155_fu_448_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten328_load = ap_const_lv4_6) else "0";
    or_ln153_fu_636_p2 <= (xor_ln157_fu_630_p2 or icmp_ln155_fu_448_p2);
    or_ln162_fu_872_p2 <= (shl_ln162_fu_774_p2 or ap_const_lv3_2);
    or_ln163_fu_905_p2 <= (ap_const_lv5_9 or add_ln163_5_fu_843_p3);
    or_ln2_fu_911_p3 <= (ap_const_lv1_0 & or_ln163_fu_905_p2);
    p_cast114_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_278_p2),6));
    p_cast114_mid1_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid1346_fu_474_p2),6));
    p_cast125_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_66_fu_354_p2),6));
    p_cast125_mid1_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid1324_fu_680_p2),6));
    p_mid1324_fu_680_p2 <= std_logic_vector(unsigned(zext_ln155_2_fu_676_p1) + unsigned(select_ln147));
    p_mid1326_fu_690_p2 <= std_logic_vector(unsigned(p_cast125_mid1_fu_686_p1) + unsigned(ap_const_lv6_3F));
    p_mid1346_fu_474_p2 <= std_logic_vector(unsigned(zext_ln153_1_fu_470_p1) + unsigned(select_ln147_1));
    p_mid1348_fu_484_p2 <= std_logic_vector(unsigned(p_cast114_mid1_fu_480_p1) + unsigned(ap_const_lv6_3F));
    p_mid1350_fu_502_p2 <= std_logic_vector(unsigned(p_shl30_cast_mid1_fu_498_p1) - unsigned(zext_ln153_1_fu_470_p1));
    p_shl2_fu_294_p3 <= (ap_sig_allocacmp_i_1 & ap_const_lv2_0);
    p_shl30_cast_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl2_fu_294_p3),5));
    p_shl30_cast_mid1_fu_498_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl30_mid1_fu_490_p3),5));
    p_shl30_mid1_fu_490_p3 <= (add_ln153_fu_442_p2 & ap_const_lv2_0);
    s_V_18_out <= lhs_fu_124;

    s_V_18_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln153_reg_1110_pp0_iter1_reg, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln153_reg_1110_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            s_V_18_out_ap_vld <= ap_const_logic_1;
        else 
            s_V_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    s_V_fu_1031_p1 <= grp_fu_1058_p3;
    select_ln153_1_fu_462_p3 <= 
        ap_const_lv3_0 when (icmp_ln155_fu_448_p2(0) = '1') else 
        ap_sig_allocacmp_k_load;
    select_ln153_2_fu_508_p3 <= 
        p_mid1350_fu_502_p2 when (icmp_ln155_fu_448_p2(0) = '1') else 
        empty_65_fu_306_p2;
    select_ln153_3_fu_526_p3 <= 
        cmp20_i68_not_mid1_fu_520_p2 when (icmp_ln155_fu_448_p2(0) = '1') else 
        cmp20_i68_not_fu_312_p2;
    select_ln153_4_fu_540_p3 <= 
        cmp21_i70_not_mid1_fu_534_p2 when (icmp_ln155_fu_448_p2(0) = '1') else 
        cmp21_i70_not_fu_318_p2;
    select_ln153_5_fu_574_p3 <= 
        sub_ln162_1_fu_568_p2 when (icmp_ln155_fu_448_p2(0) = '1') else 
        sub_ln162_fu_344_p2;
    select_ln153_6_fu_600_p3 <= 
        brmerge98_mid1372_fu_594_p2 when (icmp_ln155_fu_448_p2(0) = '1') else 
        brmerge98_fu_394_p2;
    select_ln153_7_fu_614_p3 <= 
        p_mid1350_fu_502_p2 when (icmp_ln155_fu_448_p2(0) = '1') else 
        add_ln163_2_fu_418_p2;
    select_ln153_8_fu_642_p3 <= 
        add_ln153_fu_442_p2 when (icmp_ln155_fu_448_p2(0) = '1') else 
        ap_sig_allocacmp_i_1;
    select_ln153_9_fu_800_p3 <= 
        tmp_s_fu_780_p4 when (icmp_ln155_fu_448_p2(0) = '1') else 
        tmp_1_fu_790_p4;
    select_ln153_fu_454_p3 <= 
        ap_const_lv2_0 when (icmp_ln155_fu_448_p2(0) = '1') else 
        ap_sig_allocacmp_j_2;
    select_ln155_1_fu_664_p3 <= 
        select_ln153_fu_454_p3 when (or_ln153_fu_636_p2(0) = '1') else 
        add_ln155_fu_650_p2;
    select_ln155_2_fu_726_p3 <= 
        select_ln153_6_fu_600_p3 when (or_ln153_fu_636_p2(0) = '1') else 
        brmerge98_mid1_fu_720_p2;
    select_ln155_3_fu_758_p3 <= 
        select_ln153_7_fu_614_p3 when (or_ln153_fu_636_p2(0) = '1') else 
        add_ln163_4_fu_752_p2;
    select_ln155_4_fu_818_p3 <= 
        select_ln153_9_fu_800_p3 when (or_ln153_fu_636_p2(0) = '1') else 
        tmp_2_fu_808_p4;
    select_ln155_5_fu_937_p3 <= 
        ap_const_lv4_1 when (icmp_ln155_fu_448_p2(0) = '1') else 
        add_ln155_1_fu_931_p2;
    select_ln155_fu_656_p3 <= 
        select_ln153_1_fu_462_p3 when (or_ln153_fu_636_p2(0) = '1') else 
        ap_const_lv3_0;
        sext_ln153_fu_516_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln153_2_fu_508_p3),6));

        sext_ln155_fu_766_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln155_3_fu_758_p3),6));

        sext_ln162_1_cast_fu_231_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln162_1),14));

        sext_ln162_2_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln4_fu_400_p3),14));

        sext_ln162_3_fu_564_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln162_2_mid1_fu_556_p3),14));

        sext_ln162_4_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln162_mid1_fu_734_p3),14));

        sext_ln162_5_fu_834_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_826_p3),14));

        sext_ln162_6_fu_896_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln162_1_fu_888_p3),14));

        sext_ln162_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln162_2_fu_332_p3),14));

    shl_ln162_1_fu_324_p3 <= (empty_64_fu_288_p2 & ap_const_lv8_0);
    shl_ln162_1_mid1_fu_548_p3 <= (p_mid1348_fu_484_p2 & ap_const_lv8_0);
    shl_ln162_2_fu_332_p3 <= (empty_64_fu_288_p2 & ap_const_lv5_0);
    shl_ln162_2_mid1_fu_556_p3 <= (p_mid1348_fu_484_p2 & ap_const_lv5_0);
    shl_ln162_fu_774_p2 <= std_logic_vector(shift_left(unsigned(select_ln155_fu_656_p3),to_integer(unsigned('0' & ap_const_lv3_1(3-1 downto 0)))));
    shl_ln162_mid1_fu_734_p3 <= (p_mid1326_fu_690_p2 & ap_const_lv3_0);
    shl_ln4_fu_400_p3 <= (empty_67_fu_364_p2 & ap_const_lv3_0);
    sub_ln162_1_fu_568_p2 <= std_logic_vector(unsigned(shl_ln162_1_mid1_fu_548_p3) - unsigned(sext_ln162_3_fu_564_p1));
    sub_ln162_fu_344_p2 <= std_logic_vector(unsigned(shl_ln162_1_fu_324_p3) - unsigned(sext_ln162_fu_340_p1));
    tmp59_fu_382_p2 <= (cmp23_i72_not_fu_370_p2 or cmp21_i70_not_fu_318_p2);
    tmp59_mid1368_fu_582_p2 <= (cmp23_i72_not_mid1364 or cmp21_i70_not_mid1_fu_534_p2);
    tmp59_mid1_fu_708_p2 <= (select_ln153_4_fu_540_p3 or cmp23_i72_not_mid1_fu_696_p2);
    tmp60_fu_388_p2 <= (cmp25_i74_not_fu_376_p2 or cmp20_i68_not_fu_312_p2);
    tmp60_mid1370_fu_588_p2 <= (cmp25_i74_not_mid1366 or cmp20_i68_not_mid1_fu_520_p2);
    tmp60_mid1_fu_714_p2 <= (select_ln153_3_fu_526_p3 or cmp25_i74_not_mid1_fu_702_p2);
    tmp_1_fu_790_p4 <= add_ln162_fu_412_p2(13 downto 3);
    tmp_2_fu_808_p4 <= add_ln162_2_fu_746_p2(13 downto 3);
    tmp_3_fu_878_p4 <= or_ln162_fu_872_p2(2 downto 1);
    tmp_4_fu_1014_p1 <= grp_fu_1049_p3;
    tmp_4_fu_1014_p4 <= tmp_4_fu_1014_p1(25 downto 10);
    tmp_fu_622_p3 <= ap_sig_allocacmp_k_load(2 downto 2);
    tmp_s_fu_780_p4 <= add_ln162_1_fu_608_p2(13 downto 3);
    trunc_ln162_1_fu_888_p3 <= (select_ln155_4_fu_818_p3 & tmp_3_fu_878_p4);
    trunc_ln162_fu_770_p1 <= select_ln155_fu_656_p3(2 - 1 downto 0);
    trunc_ln_fu_826_p3 <= (select_ln155_4_fu_818_p3 & trunc_ln162_fu_770_p1);
    val_V_10_fu_985_p3 <= 
        ap_const_lv16_0 when (select_ln155_2_reg_1114(0) = '1') else 
        d_q0;
    val_V_9_fu_970_p3 <= 
        ap_const_lv16_0 when (select_ln155_2_reg_1114(0) = '1') else 
        d_q1;
    xor_ln157_fu_630_p2 <= (tmp_fu_622_p3 xor ap_const_lv1_1);
    zext_ln1271_2_fu_992_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln163_3_reg_1135),64));
    zext_ln1271_fu_867_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln163_1_fu_861_p2),64));
    zext_ln153_1_fu_470_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln153_fu_442_p2),5));
    zext_ln153_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),5));
    zext_ln155_1_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln155_1_fu_664_p3),6));
    zext_ln155_2_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln155_fu_650_p2),5));
    zext_ln155_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_2),5));
    zext_ln162_1_fu_900_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln162_6_fu_896_p1),64));
    zext_ln162_fu_838_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln162_5_fu_834_p1),64));
    zext_ln163_fu_851_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln163_5_fu_843_p3),6));
end behav;
