-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity denoiser_top_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln66 : IN STD_LOGIC_VECTOR (9 downto 0);
    select_ln68_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    select_ln68 : IN STD_LOGIC_VECTOR (3 downto 0);
    zext_ln66 : IN STD_LOGIC_VECTOR (7 downto 0);
    cmp27_i_not_mid1115 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp29_i_not_mid1117 : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln83_4 : IN STD_LOGIC_VECTOR (12 downto 0);
    d_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    d_ce0 : OUT STD_LOGIC;
    d_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    d_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    d_ce1 : OUT STD_LOGIC;
    d_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    s_V_15_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    s_V_15_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of denoiser_top_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv13_1100 : STD_LOGIC_VECTOR (12 downto 0) := "1000100000000";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln74_reg_1158 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal conv2_kernel_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal conv2_kernel_V_ce0 : STD_LOGIC;
    signal conv2_kernel_V_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln74_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_reg_1158_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln76_2_fu_780_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln76_2_reg_1162 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln84_3_fu_967_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln84_3_reg_1183 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal val_V_21_fu_1033_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal val_V_21_reg_1198 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln83_fu_880_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln1271_3_fu_909_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln83_1_fu_938_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1271_fu_1040_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal lhs_fu_132 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln66_cast_fu_259_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_lhs_load_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal k_fu_136 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln78_fu_973_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_k_load : STD_LOGIC_VECTOR (2 downto 0);
    signal j_1_fu_140 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln76_1_fu_714_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_j : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten77_fu_144 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln76_4_fu_985_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten77_load : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_fu_148 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln74_7_fu_692_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten137_fu_152 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln74_2_fu_470_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten137_load : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal zext_ln74_1_fu_306_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_fu_310_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_cast82_fu_316_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl_fu_326_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl14_cast_fu_334_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln74_fu_302_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_74_fu_320_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln83_2_fu_364_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln83_1_fu_356_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln83_fu_372_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln83_fu_376_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln76_fu_386_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_76_fu_390_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_cast123_fu_396_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_77_fu_400_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal cmp25_i228_not_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp27_i_not_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp24_i_not_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp29_i_not_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp14_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp13_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln2_fu_436_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln83_1_fu_444_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln83_fu_448_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln83_2_fu_454_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln76_fu_382_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln76_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln74_fu_482_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln74_3_fu_514_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_mid195_fu_518_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_cast82_mid1_fu_524_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl14_mid1_fu_534_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl14_cast_mid1_fu_542_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln74_2_fu_510_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal cmp24_i_not_mid1_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mid197_fu_528_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal cmp25_i228_not_mid1_fu_566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln83_2_mid1_fu_588_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln83_1_mid1_fu_580_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln83_3_fu_596_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln83_1_fu_600_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln74_4_fu_610_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_mid199_fu_546_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_75_fu_338_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln74_5_fu_622_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln74_1_fu_630_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln66_cast_fu_255_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp14_mid1121_fu_646_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp13_mid1119_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge78_mid1123_fu_652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge78_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln83_4_cast_fu_251_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln76_1_fu_606_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_672_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln78_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_fu_494_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln74_fu_686_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_1_fu_502_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln76_fu_700_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln76_3_fu_730_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_mid173_fu_734_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_cast123_mid1_fu_740_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_mid175_fu_744_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln74_3_fu_572_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp27_i_not_mid1_fu_750_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_2_fu_558_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp29_i_not_mid1_fu_756_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp14_mid1_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp13_mid1_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln74_6_fu_658_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge78_mid1_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln83_mid1_fu_788_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln83_5_fu_796_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln83_3_fu_800_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln83_6_fu_806_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln74_fu_618_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln76_fu_706_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln83_2_fu_666_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln83_1_fu_458_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_s_fu_826_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_836_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln83_4_fu_810_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln74_8_fu_846_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_11_fu_854_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln76_3_fu_864_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln83_fu_816_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln4_fu_872_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln76_2_fu_726_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln84_7_fu_885_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln84_fu_893_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln84_fu_899_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln74_1_fu_634_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln84_1_fu_903_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln83_fu_820_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln83_fu_914_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_12_fu_920_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln83_1_fu_930_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln84_fu_943_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln1_fu_949_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln76_1_fu_722_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln84_2_fu_957_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln84_1_fu_963_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln76_1_fu_979_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_V_20_fu_1018_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_13_fu_1062_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1097_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_13_fu_1062_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal s_V_fu_1079_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1106_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1097_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1106_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component denoiser_top_mac_muladd_11s_16s_26ns_26_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (25 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component denoiser_top_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_conv2_kernel_V_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component denoiser_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    conv2_kernel_V_U : component denoiser_top_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_conv2_kernel_V_ROM_AUTO_1R
    generic map (
        DataWidth => 11,
        AddressRange => 288,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => conv2_kernel_V_address0,
        ce0 => conv2_kernel_V_ce0,
        q0 => conv2_kernel_V_q0);

    mac_muladd_11s_16s_26ns_26_4_1_U18 : component denoiser_top_mac_muladd_11s_16s_26ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 11,
        din1_WIDTH => 16,
        din2_WIDTH => 26,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => conv2_kernel_V_q0,
        din1 => val_V_20_fu_1018_p3,
        din2 => grp_fu_1097_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1097_p3);

    mac_muladd_11s_16s_26ns_26_4_1_U19 : component denoiser_top_mac_muladd_11s_16s_26ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 11,
        din1_WIDTH => 16,
        din2_WIDTH => 26,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => conv2_kernel_V_q0,
        din1 => val_V_21_reg_1198,
        din2 => grp_fu_1106_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1106_p3);

    flow_control_loop_pipe_sequential_init_U : component denoiser_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln74_fu_464_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_1_fu_148 <= select_ln74_7_fu_692_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_148 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten137_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln74_fu_464_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten137_fu_152 <= add_ln74_2_fu_470_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten137_fu_152 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten77_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln74_fu_464_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten77_fu_144 <= select_ln76_4_fu_985_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten77_fu_144 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    j_1_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln74_fu_464_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_1_fu_140 <= select_ln76_1_fu_714_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_1_fu_140 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln74_fu_464_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_136 <= add_ln78_fu_973_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_136 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                lhs_fu_132 <= sext_ln66_cast_fu_259_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                lhs_fu_132 <= s_V_fu_1079_p1(25 downto 10);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_fu_464_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln84_3_reg_1183 <= add_ln84_3_fu_967_p2;
                select_ln76_2_reg_1162 <= select_ln76_2_fu_780_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln74_reg_1158 <= icmp_ln74_fu_464_p2;
                icmp_ln74_reg_1158_pp0_iter1_reg <= icmp_ln74_reg_1158;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_reg_1158 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                val_V_21_reg_1198 <= val_V_21_fu_1033_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln74_1_fu_634_p2 <= std_logic_vector(signed(sext_ln74_1_fu_630_p1) + signed(zext_ln66_cast_fu_255_p1));
    add_ln74_2_fu_470_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten137_load) + unsigned(ap_const_lv5_1));
    add_ln74_fu_482_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv2_1));
    add_ln76_1_fu_979_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten77_load) + unsigned(ap_const_lv4_1));
    add_ln76_fu_700_p2 <= std_logic_vector(unsigned(select_ln74_fu_494_p3) + unsigned(ap_const_lv2_1));
    add_ln78_fu_973_p2 <= std_logic_vector(unsigned(select_ln76_fu_706_p3) + unsigned(ap_const_lv3_2));
    add_ln83_1_fu_458_p2 <= std_logic_vector(signed(sext_ln83_2_fu_454_p1) + signed(sext_ln76_fu_382_p1));
    add_ln83_2_fu_666_p2 <= std_logic_vector(signed(sext_ln83_4_cast_fu_251_p1) + signed(sext_ln76_1_fu_606_p1));
    add_ln83_3_fu_800_p2 <= std_logic_vector(signed(sext_ln83_5_fu_796_p1) + signed(ap_const_lv13_1100));
    add_ln83_4_fu_810_p2 <= std_logic_vector(signed(sext_ln83_6_fu_806_p1) + signed(sext_ln74_fu_618_p1));
    add_ln83_fu_448_p2 <= std_logic_vector(signed(sext_ln83_1_fu_444_p1) + signed(ap_const_lv13_1100));
    add_ln84_1_fu_903_p2 <= std_logic_vector(unsigned(zext_ln84_fu_899_p1) + unsigned(add_ln74_1_fu_634_p2));
    add_ln84_2_fu_957_p2 <= std_logic_vector(unsigned(or_ln1_fu_949_p3) + unsigned(zext_ln76_1_fu_722_p1));
    add_ln84_3_fu_967_p2 <= std_logic_vector(unsigned(zext_ln84_1_fu_963_p1) + unsigned(add_ln74_1_fu_634_p2));
    add_ln84_7_fu_885_p3 <= (trunc_ln83_fu_816_p1 & select_ln76_fu_706_p3);
    add_ln84_fu_893_p2 <= std_logic_vector(unsigned(zext_ln76_2_fu_726_p1) + unsigned(add_ln84_7_fu_885_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln74_reg_1158)
    begin
        if (((icmp_ln74_reg_1158 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_1_fu_148)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_i <= i_1_fu_148;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten137_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten137_fu_152)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten137_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten137_load <= indvar_flatten137_fu_152;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten77_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten77_fu_144)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten77_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten77_load <= indvar_flatten77_fu_144;
        end if; 
    end process;


    ap_sig_allocacmp_j_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_1_fu_140)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_j <= j_1_fu_140;
        end if; 
    end process;


    ap_sig_allocacmp_k_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_136)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_k_load <= k_fu_136;
        end if; 
    end process;


    ap_sig_allocacmp_lhs_load_4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, lhs_fu_132, s_V_fu_1079_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_sig_allocacmp_lhs_load_4 <= s_V_fu_1079_p1(25 downto 10);
        else 
            ap_sig_allocacmp_lhs_load_4 <= lhs_fu_132;
        end if; 
    end process;

    brmerge78_fu_430_p2 <= (tmp14_fu_424_p2 or tmp13_fu_418_p2);
    brmerge78_mid1123_fu_652_p2 <= (tmp14_mid1121_fu_646_p2 or tmp13_mid1119_fu_640_p2);
    brmerge78_mid1_fu_774_p2 <= (tmp14_mid1_fu_768_p2 or tmp13_mid1_fu_762_p2);
    cmp24_i_not_fu_344_p2 <= "1" when (empty_fu_310_p2 = ap_const_lv4_0) else "0";
    cmp24_i_not_mid1_fu_552_p2 <= "1" when (p_mid195_fu_518_p2 = ap_const_lv4_0) else "0";
    cmp25_i228_not_fu_350_p2 <= "1" when (signed(empty_74_fu_320_p2) > signed(ap_const_lv5_D)) else "0";
    cmp25_i228_not_mid1_fu_566_p2 <= "1" when (signed(p_mid197_fu_528_p2) > signed(ap_const_lv5_D)) else "0";
    cmp27_i_not_fu_406_p2 <= "1" when (empty_76_fu_390_p2 = ap_const_lv4_0) else "0";
    cmp27_i_not_mid1_fu_750_p2 <= "1" when (p_mid173_fu_734_p2 = ap_const_lv4_0) else "0";
    cmp29_i_not_fu_412_p2 <= "1" when (signed(empty_77_fu_400_p2) > signed(ap_const_lv5_D)) else "0";
    cmp29_i_not_mid1_fu_756_p2 <= "1" when (signed(p_mid175_fu_744_p2) > signed(ap_const_lv5_D)) else "0";

    conv2_kernel_V_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln1271_3_fu_909_p1, zext_ln1271_fu_1040_p1, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                conv2_kernel_V_address0 <= zext_ln1271_fu_1040_p1(9 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                conv2_kernel_V_address0 <= zext_ln1271_3_fu_909_p1(9 - 1 downto 0);
            else 
                conv2_kernel_V_address0 <= "XXXXXXXXX";
            end if;
        else 
            conv2_kernel_V_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    conv2_kernel_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            conv2_kernel_V_ce0 <= ap_const_logic_1;
        else 
            conv2_kernel_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    d_address0 <= zext_ln83_1_fu_938_p1(14 - 1 downto 0);
    d_address1 <= zext_ln83_fu_880_p1(14 - 1 downto 0);

    d_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            d_ce0 <= ap_const_logic_1;
        else 
            d_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    d_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            d_ce1 <= ap_const_logic_1;
        else 
            d_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    empty_74_fu_320_p2 <= std_logic_vector(unsigned(p_cast82_fu_316_p1) + unsigned(ap_const_lv5_1F));
    empty_75_fu_338_p2 <= std_logic_vector(unsigned(p_shl14_cast_fu_334_p1) - unsigned(zext_ln74_fu_302_p1));
    empty_76_fu_390_p2 <= std_logic_vector(unsigned(zext_ln76_fu_386_p1) + unsigned(select_ln68));
    empty_77_fu_400_p2 <= std_logic_vector(unsigned(p_cast123_fu_396_p1) + unsigned(ap_const_lv5_1F));
    empty_fu_310_p2 <= std_logic_vector(unsigned(zext_ln74_1_fu_306_p1) + unsigned(select_ln68_2));
    grp_fu_1097_p2 <= (ap_sig_allocacmp_lhs_load_4 & ap_const_lv10_0);
    grp_fu_1106_p2 <= (tmp_13_fu_1062_p4 & ap_const_lv10_0);
    icmp_ln74_fu_464_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten137_load = ap_const_lv5_12) else "0";
    icmp_ln76_fu_488_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten77_load = ap_const_lv4_6) else "0";
    lshr_ln4_fu_872_p3 <= (select_ln76_3_fu_864_p3 & trunc_ln83_fu_816_p1);
    lshr_ln83_1_fu_930_p3 <= (select_ln76_3_fu_864_p3 & tmp_12_fu_920_p4);
    or_ln1_fu_949_p3 <= (ap_const_lv1_0 & or_ln84_fu_943_p2);
    or_ln74_fu_686_p2 <= (xor_ln78_fu_680_p2 or icmp_ln76_fu_488_p2);
    or_ln83_fu_914_p2 <= (shl_ln83_fu_820_p2 or ap_const_lv3_2);
    or_ln84_fu_943_p2 <= (ap_const_lv5_9 or add_ln84_7_fu_885_p3);
    p_cast123_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_76_fu_390_p2),5));
    p_cast123_mid1_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid173_fu_734_p2),5));
    p_cast82_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_310_p2),5));
    p_cast82_mid1_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid195_fu_518_p2),5));
    p_mid173_fu_734_p2 <= std_logic_vector(unsigned(zext_ln76_3_fu_730_p1) + unsigned(select_ln68));
    p_mid175_fu_744_p2 <= std_logic_vector(unsigned(p_cast123_mid1_fu_740_p1) + unsigned(ap_const_lv5_1F));
    p_mid195_fu_518_p2 <= std_logic_vector(unsigned(zext_ln74_3_fu_514_p1) + unsigned(select_ln68_2));
    p_mid197_fu_528_p2 <= std_logic_vector(unsigned(p_cast82_mid1_fu_524_p1) + unsigned(ap_const_lv5_1F));
    p_mid199_fu_546_p2 <= std_logic_vector(unsigned(p_shl14_cast_mid1_fu_542_p1) - unsigned(zext_ln74_2_fu_510_p1));
    p_shl14_cast_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_326_p3),5));
    p_shl14_cast_mid1_fu_542_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl14_mid1_fu_534_p3),5));
    p_shl14_mid1_fu_534_p3 <= (add_ln74_fu_482_p2 & ap_const_lv2_0);
    p_shl_fu_326_p3 <= (ap_sig_allocacmp_i & ap_const_lv2_0);
    s_V_15_out <= lhs_fu_132;

    s_V_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln74_reg_1158_pp0_iter1_reg, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln74_reg_1158_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            s_V_15_out_ap_vld <= ap_const_logic_1;
        else 
            s_V_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    s_V_fu_1079_p1 <= grp_fu_1106_p3;
    select_ln74_1_fu_502_p3 <= 
        ap_const_lv3_0 when (icmp_ln76_fu_488_p2(0) = '1') else 
        ap_sig_allocacmp_k_load;
    select_ln74_2_fu_558_p3 <= 
        cmp24_i_not_mid1_fu_552_p2 when (icmp_ln76_fu_488_p2(0) = '1') else 
        cmp24_i_not_fu_344_p2;
    select_ln74_3_fu_572_p3 <= 
        cmp25_i228_not_mid1_fu_566_p2 when (icmp_ln76_fu_488_p2(0) = '1') else 
        cmp25_i228_not_fu_350_p2;
    select_ln74_4_fu_610_p3 <= 
        sub_ln83_1_fu_600_p2 when (icmp_ln76_fu_488_p2(0) = '1') else 
        sub_ln83_fu_376_p2;
    select_ln74_5_fu_622_p3 <= 
        p_mid199_fu_546_p2 when (icmp_ln76_fu_488_p2(0) = '1') else 
        empty_75_fu_338_p2;
    select_ln74_6_fu_658_p3 <= 
        brmerge78_mid1123_fu_652_p2 when (icmp_ln76_fu_488_p2(0) = '1') else 
        brmerge78_fu_430_p2;
    select_ln74_7_fu_692_p3 <= 
        add_ln74_fu_482_p2 when (icmp_ln76_fu_488_p2(0) = '1') else 
        ap_sig_allocacmp_i;
    select_ln74_8_fu_846_p3 <= 
        tmp_s_fu_826_p4 when (icmp_ln76_fu_488_p2(0) = '1') else 
        tmp_10_fu_836_p4;
    select_ln74_fu_494_p3 <= 
        ap_const_lv2_0 when (icmp_ln76_fu_488_p2(0) = '1') else 
        ap_sig_allocacmp_j;
    select_ln76_1_fu_714_p3 <= 
        select_ln74_fu_494_p3 when (or_ln74_fu_686_p2(0) = '1') else 
        add_ln76_fu_700_p2;
    select_ln76_2_fu_780_p3 <= 
        select_ln74_6_fu_658_p3 when (or_ln74_fu_686_p2(0) = '1') else 
        brmerge78_mid1_fu_774_p2;
    select_ln76_3_fu_864_p3 <= 
        select_ln74_8_fu_846_p3 when (or_ln74_fu_686_p2(0) = '1') else 
        tmp_11_fu_854_p4;
    select_ln76_4_fu_985_p3 <= 
        ap_const_lv4_1 when (icmp_ln76_fu_488_p2(0) = '1') else 
        add_ln76_1_fu_979_p2;
    select_ln76_fu_706_p3 <= 
        select_ln74_1_fu_502_p3 when (or_ln74_fu_686_p2(0) = '1') else 
        ap_const_lv3_0;
        sext_ln66_cast_fu_259_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln66),16));

        sext_ln74_1_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln74_5_fu_622_p3),9));

        sext_ln74_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln74_4_fu_610_p3),14));

        sext_ln76_1_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln83_1_fu_600_p2),14));

        sext_ln76_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln83_fu_376_p2),14));

        sext_ln83_1_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln2_fu_436_p3),13));

        sext_ln83_2_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln83_fu_448_p2),14));

        sext_ln83_3_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln83_2_mid1_fu_588_p3),12));

        sext_ln83_4_cast_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln83_4),14));

        sext_ln83_5_fu_796_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln83_mid1_fu_788_p3),13));

        sext_ln83_6_fu_806_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln83_3_fu_800_p2),14));

        sext_ln83_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln83_2_fu_364_p3),12));

    shl_ln2_fu_436_p3 <= (empty_77_fu_400_p2 & ap_const_lv3_0);
    shl_ln83_1_fu_356_p3 <= (empty_74_fu_320_p2 & ap_const_lv7_0);
    shl_ln83_1_mid1_fu_580_p3 <= (p_mid197_fu_528_p2 & ap_const_lv7_0);
    shl_ln83_2_fu_364_p3 <= (empty_74_fu_320_p2 & ap_const_lv4_0);
    shl_ln83_2_mid1_fu_588_p3 <= (p_mid197_fu_528_p2 & ap_const_lv4_0);
    shl_ln83_fu_820_p2 <= std_logic_vector(shift_left(unsigned(select_ln76_fu_706_p3),to_integer(unsigned('0' & ap_const_lv3_1(3-1 downto 0)))));
    shl_ln83_mid1_fu_788_p3 <= (p_mid175_fu_744_p2 & ap_const_lv3_0);
    sub_ln83_1_fu_600_p2 <= std_logic_vector(unsigned(shl_ln83_1_mid1_fu_580_p3) - unsigned(sext_ln83_3_fu_596_p1));
    sub_ln83_fu_376_p2 <= std_logic_vector(unsigned(shl_ln83_1_fu_356_p3) - unsigned(sext_ln83_fu_372_p1));
    tmp13_fu_418_p2 <= (cmp27_i_not_fu_406_p2 or cmp25_i228_not_fu_350_p2);
    tmp13_mid1119_fu_640_p2 <= (cmp27_i_not_mid1115 or cmp25_i228_not_mid1_fu_566_p2);
    tmp13_mid1_fu_762_p2 <= (select_ln74_3_fu_572_p3 or cmp27_i_not_mid1_fu_750_p2);
    tmp14_fu_424_p2 <= (cmp29_i_not_fu_412_p2 or cmp24_i_not_fu_344_p2);
    tmp14_mid1121_fu_646_p2 <= (cmp29_i_not_mid1117 or cmp24_i_not_mid1_fu_552_p2);
    tmp14_mid1_fu_768_p2 <= (select_ln74_2_fu_558_p3 or cmp29_i_not_mid1_fu_756_p2);
    tmp_10_fu_836_p4 <= add_ln83_1_fu_458_p2(13 downto 3);
    tmp_11_fu_854_p4 <= add_ln83_4_fu_810_p2(13 downto 3);
    tmp_12_fu_920_p4 <= or_ln83_fu_914_p2(2 downto 1);
    tmp_13_fu_1062_p1 <= grp_fu_1097_p3;
    tmp_13_fu_1062_p4 <= tmp_13_fu_1062_p1(25 downto 10);
    tmp_fu_672_p3 <= ap_sig_allocacmp_k_load(2 downto 2);
    tmp_s_fu_826_p4 <= add_ln83_2_fu_666_p2(13 downto 3);
    trunc_ln83_fu_816_p1 <= select_ln76_fu_706_p3(2 - 1 downto 0);
    val_V_20_fu_1018_p3 <= 
        ap_const_lv16_0 when (select_ln76_2_reg_1162(0) = '1') else 
        d_q1;
    val_V_21_fu_1033_p3 <= 
        ap_const_lv16_0 when (select_ln76_2_reg_1162(0) = '1') else 
        d_q0;
    xor_ln78_fu_680_p2 <= (tmp_fu_672_p3 xor ap_const_lv1_1);
    zext_ln1271_3_fu_909_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln84_1_fu_903_p2),64));
    zext_ln1271_fu_1040_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln84_3_reg_1183),64));
    zext_ln66_cast_fu_255_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln66),9));
    zext_ln74_1_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i),4));
    zext_ln74_2_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_fu_482_p2),5));
    zext_ln74_3_fu_514_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_fu_482_p2),4));
    zext_ln74_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i),5));
    zext_ln76_1_fu_722_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln76_1_fu_714_p3),6));
    zext_ln76_2_fu_726_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln76_1_fu_714_p3),5));
    zext_ln76_3_fu_730_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_fu_700_p2),4));
    zext_ln76_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j),4));
    zext_ln83_1_fu_938_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln83_1_fu_930_p3),64));
    zext_ln83_fu_880_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln4_fu_872_p3),64));
    zext_ln84_1_fu_963_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln84_2_fu_957_p2),9));
    zext_ln84_fu_899_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln84_fu_893_p2),9));
end behav;
