-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity denoiser_top_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    select_ln115_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    select_ln117_2 : IN STD_LOGIC_VECTOR (4 downto 0);
    select_ln117 : IN STD_LOGIC_VECTOR (4 downto 0);
    zext_ln115 : IN STD_LOGIC_VECTOR (7 downto 0);
    cmp27_i431_not_mid1258 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp29_i433_not_mid1260 : IN STD_LOGIC_VECTOR (0 downto 0);
    zext_ln132_3 : IN STD_LOGIC_VECTOR (12 downto 0);
    d_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    d_ce0 : OUT STD_LOGIC;
    d_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    d_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    d_ce1 : OUT STD_LOGIC;
    d_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    s_V_16_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    s_V_16_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of denoiser_top_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv13_1100 : STD_LOGIC_VECTOR (12 downto 0) := "1000100000000";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv7_9 : STD_LOGIC_VECTOR (6 downto 0) := "0001001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln123_reg_1148 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal conv3_kernel_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal conv3_kernel_V_ce0 : STD_LOGIC;
    signal conv3_kernel_V_q0 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln123_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_reg_1148_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln125_2_fu_760_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln125_2_reg_1152 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln133_4_fu_957_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln133_4_reg_1173 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal val_V_16_fu_1023_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal val_V_16_reg_1188 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln132_fu_864_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln1271_fu_907_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln132_1_fu_936_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1271_3_fu_1030_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal lhs_fu_132 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_lhs_load_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal k_fu_136 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln127_fu_963_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_k_load : STD_LOGIC_VECTOR (3 downto 0);
    signal j_fu_140 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln125_1_fu_698_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_j_3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten222_fu_144 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln125_4_fu_975_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten222_load : STD_LOGIC_VECTOR (4 downto 0);
    signal i_fu_148 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln123_7_fu_676_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten282_fu_152 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln123_2_fu_466_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten282_load : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal zext_ln132_3_cast_fu_251_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln123_fu_302_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_fu_306_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast119_fu_312_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl1_fu_322_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl26_cast_fu_330_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_69_fu_316_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln132_2_fu_360_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln132_1_fu_352_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln132_fu_368_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln125_fu_378_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_71_fu_382_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast127_fu_388_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_72_fu_392_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal cmp25_i429_not_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp27_i431_not_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp24_i427_not_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp29_i433_not_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp29_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp28_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln3_fu_428_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln132_1_fu_436_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln132_fu_440_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln132_2_fu_446_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln132_2_fu_450_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln132_fu_372_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln125_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln123_fu_478_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln123_1_fu_506_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_mid1240_fu_510_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast119_mid1_fu_516_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl26_mid1_fu_526_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl26_cast_mid1_fu_534_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal cmp24_i427_not_mid1_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mid1242_fu_520_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal cmp25_i429_not_mid1_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln132_2_mid1_fu_580_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln132_1_mid1_fu_572_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln132_3_fu_588_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln132_1_fu_592_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_mid1244_fu_538_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_70_fu_334_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln123_5_fu_606_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln123_fu_614_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln115_cast_fu_259_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp29_mid1264_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp28_mid1262_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge88_mid1266_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge88_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln132_3_cast_cast_fu_255_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_fu_656_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln127_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln123_fu_490_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln123_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln123_1_fu_498_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln125_fu_684_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln125_2_fu_710_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_mid1218_fu_714_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast127_mid1_fu_720_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_mid1220_fu_724_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln123_3_fu_564_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp27_i431_not_mid1_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln123_2_fu_550_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp29_i433_not_mid1_fu_736_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp29_mid1_fu_748_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp28_mid1_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln123_6_fu_642_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge88_mid1_fu_754_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln132_mid1_fu_768_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln132_4_fu_776_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln132_3_fu_780_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln132_5_fu_786_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln132_4_fu_790_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln123_4_fu_598_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln125_fu_690_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln132_2_fu_650_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln132_1_fu_454_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_s_fu_810_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_820_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln132_4_fu_794_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln123_8_fu_830_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_6_fu_838_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln125_3_fu_848_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln132_fu_800_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln5_fu_856_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_7_fu_869_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln133_7_fu_879_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln125_1_fu_706_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln133_fu_887_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln133_fu_891_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln133_1_fu_897_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln123_1_fu_618_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln133_1_fu_901_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln132_fu_804_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln132_fu_912_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_918_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln132_1_fu_928_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln133_2_fu_941_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln133_3_fu_947_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln133_2_fu_953_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln125_1_fu_969_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal val_V_15_fu_1008_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_1052_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1087_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_9_fu_1052_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal s_V_fu_1069_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1096_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1087_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_1096_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component denoiser_top_mac_muladd_12s_16s_26ns_26_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (25 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component denoiser_top_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_conv3_kernel_V_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component denoiser_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    conv3_kernel_V_U : component denoiser_top_inference_Pipeline_loop_kh_3_loop_kw_3_loop_ic_3_conv3_kernel_V_ROM_AUTO_1R
    generic map (
        DataWidth => 12,
        AddressRange => 288,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => conv3_kernel_V_address0,
        ce0 => conv3_kernel_V_ce0,
        q0 => conv3_kernel_V_q0);

    mac_muladd_12s_16s_26ns_26_4_1_U32 : component denoiser_top_mac_muladd_12s_16s_26ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 12,
        din1_WIDTH => 16,
        din2_WIDTH => 26,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => conv3_kernel_V_q0,
        din1 => val_V_15_fu_1008_p3,
        din2 => grp_fu_1087_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1087_p3);

    mac_muladd_12s_16s_26ns_26_4_1_U33 : component denoiser_top_mac_muladd_12s_16s_26ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 12,
        din1_WIDTH => 16,
        din2_WIDTH => 26,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => conv3_kernel_V_q0,
        din1 => val_V_16_reg_1188,
        din2 => grp_fu_1096_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1096_p3);

    flow_control_loop_pipe_sequential_init_U : component denoiser_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln123_fu_460_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_148 <= select_ln123_7_fu_676_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_148 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten222_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln123_fu_460_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten222_fu_144 <= select_ln125_4_fu_975_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten222_fu_144 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten282_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln123_fu_460_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten282_fu_152 <= add_ln123_2_fu_466_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten282_fu_152 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln123_fu_460_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_140 <= select_ln125_1_fu_698_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_140 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln123_fu_460_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_136 <= add_ln127_fu_963_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_136 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                lhs_fu_132 <= select_ln115_2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                lhs_fu_132 <= s_V_fu_1069_p1(25 downto 10);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_460_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln133_4_reg_1173 <= add_ln133_4_fu_957_p2;
                select_ln125_2_reg_1152 <= select_ln125_2_fu_760_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln123_reg_1148 <= icmp_ln123_fu_460_p2;
                icmp_ln123_reg_1148_pp0_iter1_reg <= icmp_ln123_reg_1148;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_reg_1148 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                val_V_16_reg_1188 <= val_V_16_fu_1023_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln123_1_fu_618_p2 <= std_logic_vector(signed(sext_ln123_fu_614_p1) + signed(zext_ln115_cast_fu_259_p1));
    add_ln123_2_fu_466_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten282_load) + unsigned(ap_const_lv6_1));
    add_ln123_fu_478_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv2_1));
    add_ln125_1_fu_969_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten222_load) + unsigned(ap_const_lv5_1));
    add_ln125_fu_684_p2 <= std_logic_vector(unsigned(select_ln123_fu_490_p3) + unsigned(ap_const_lv2_1));
    add_ln127_fu_963_p2 <= std_logic_vector(unsigned(select_ln125_fu_690_p3) + unsigned(ap_const_lv4_2));
    add_ln132_1_fu_454_p2 <= std_logic_vector(unsigned(zext_ln132_2_fu_450_p1) + unsigned(sub_ln132_fu_372_p2));
    add_ln132_2_fu_650_p2 <= std_logic_vector(unsigned(zext_ln132_3_cast_cast_fu_255_p1) + unsigned(sub_ln132_1_fu_592_p2));
    add_ln132_3_fu_780_p2 <= std_logic_vector(signed(sext_ln132_4_fu_776_p1) + signed(ap_const_lv13_1100));
    add_ln132_4_fu_794_p2 <= std_logic_vector(unsigned(zext_ln132_4_fu_790_p1) + unsigned(select_ln123_4_fu_598_p3));
    add_ln132_fu_440_p2 <= std_logic_vector(signed(sext_ln132_1_fu_436_p1) + signed(ap_const_lv13_1100));
    add_ln133_1_fu_901_p2 <= std_logic_vector(unsigned(zext_ln133_1_fu_897_p1) + unsigned(add_ln123_1_fu_618_p2));
    add_ln133_2_fu_941_p2 <= std_logic_vector(unsigned(zext_ln133_fu_887_p1) + unsigned(ap_const_lv7_9));
    add_ln133_3_fu_947_p2 <= std_logic_vector(unsigned(add_ln133_2_fu_941_p2) + unsigned(zext_ln125_1_fu_706_p1));
    add_ln133_4_fu_957_p2 <= std_logic_vector(unsigned(zext_ln133_2_fu_953_p1) + unsigned(add_ln123_1_fu_618_p2));
    add_ln133_7_fu_879_p3 <= (tmp_7_fu_869_p4 & select_ln125_fu_690_p3);
    add_ln133_fu_891_p2 <= std_logic_vector(unsigned(zext_ln125_1_fu_706_p1) + unsigned(zext_ln133_fu_887_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln123_reg_1148)
    begin
        if (((icmp_ln123_reg_1148 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_148)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_148;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten222_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten222_fu_144)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten222_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten222_load <= indvar_flatten222_fu_144;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten282_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten282_fu_152)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten282_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten282_load <= indvar_flatten282_fu_152;
        end if; 
    end process;


    ap_sig_allocacmp_j_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_fu_140)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_3 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_j_3 <= j_fu_140;
        end if; 
    end process;


    ap_sig_allocacmp_k_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_136)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_k_load <= k_fu_136;
        end if; 
    end process;


    ap_sig_allocacmp_lhs_load_3_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, lhs_fu_132, s_V_fu_1069_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_sig_allocacmp_lhs_load_3 <= s_V_fu_1069_p1(25 downto 10);
        else 
            ap_sig_allocacmp_lhs_load_3 <= lhs_fu_132;
        end if; 
    end process;

    brmerge88_fu_422_p2 <= (tmp29_fu_416_p2 or tmp28_fu_410_p2);
    brmerge88_mid1266_fu_636_p2 <= (tmp29_mid1264_fu_630_p2 or tmp28_mid1262_fu_624_p2);
    brmerge88_mid1_fu_754_p2 <= (tmp29_mid1_fu_748_p2 or tmp28_mid1_fu_742_p2);
    cmp24_i427_not_fu_340_p2 <= "1" when (empty_fu_306_p2 = ap_const_lv5_0) else "0";
    cmp24_i427_not_mid1_fu_544_p2 <= "1" when (p_mid1240_fu_510_p2 = ap_const_lv5_0) else "0";
    cmp25_i429_not_fu_346_p2 <= "1" when (signed(empty_69_fu_316_p2) > signed(ap_const_lv6_1B)) else "0";
    cmp25_i429_not_mid1_fu_558_p2 <= "1" when (signed(p_mid1242_fu_520_p2) > signed(ap_const_lv6_1B)) else "0";
    cmp27_i431_not_fu_398_p2 <= "1" when (empty_71_fu_382_p2 = ap_const_lv5_0) else "0";
    cmp27_i431_not_mid1_fu_730_p2 <= "1" when (p_mid1218_fu_714_p2 = ap_const_lv5_0) else "0";
    cmp29_i433_not_fu_404_p2 <= "1" when (signed(empty_72_fu_392_p2) > signed(ap_const_lv6_1B)) else "0";
    cmp29_i433_not_mid1_fu_736_p2 <= "1" when (signed(p_mid1220_fu_724_p2) > signed(ap_const_lv6_1B)) else "0";

    conv3_kernel_V_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln1271_fu_907_p1, zext_ln1271_3_fu_1030_p1, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                conv3_kernel_V_address0 <= zext_ln1271_3_fu_1030_p1(9 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                conv3_kernel_V_address0 <= zext_ln1271_fu_907_p1(9 - 1 downto 0);
            else 
                conv3_kernel_V_address0 <= "XXXXXXXXX";
            end if;
        else 
            conv3_kernel_V_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    conv3_kernel_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            conv3_kernel_V_ce0 <= ap_const_logic_1;
        else 
            conv3_kernel_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    d_address0 <= zext_ln132_1_fu_936_p1(14 - 1 downto 0);
    d_address1 <= zext_ln132_fu_864_p1(14 - 1 downto 0);

    d_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            d_ce0 <= ap_const_logic_1;
        else 
            d_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    d_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            d_ce1 <= ap_const_logic_1;
        else 
            d_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    empty_69_fu_316_p2 <= std_logic_vector(unsigned(p_cast119_fu_312_p1) + unsigned(ap_const_lv6_3F));
    empty_70_fu_334_p2 <= std_logic_vector(unsigned(p_shl26_cast_fu_330_p1) - unsigned(zext_ln123_fu_302_p1));
    empty_71_fu_382_p2 <= std_logic_vector(unsigned(zext_ln125_fu_378_p1) + unsigned(select_ln117));
    empty_72_fu_392_p2 <= std_logic_vector(unsigned(p_cast127_fu_388_p1) + unsigned(ap_const_lv6_3F));
    empty_fu_306_p2 <= std_logic_vector(unsigned(zext_ln123_fu_302_p1) + unsigned(select_ln117_2));
    grp_fu_1087_p2 <= (ap_sig_allocacmp_lhs_load_3 & ap_const_lv10_0);
    grp_fu_1096_p2 <= (tmp_9_fu_1052_p4 & ap_const_lv10_0);
    icmp_ln123_fu_460_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten282_load = ap_const_lv6_24) else "0";
    icmp_ln125_fu_484_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten222_load = ap_const_lv5_C) else "0";
    lshr_ln132_1_fu_928_p3 <= (select_ln125_3_fu_848_p3 & tmp_8_fu_918_p4);
    lshr_ln5_fu_856_p3 <= (select_ln125_3_fu_848_p3 & trunc_ln132_fu_800_p1);
    or_ln123_fu_670_p2 <= (xor_ln127_fu_664_p2 or icmp_ln125_fu_484_p2);
    or_ln132_fu_912_p2 <= (shl_ln132_fu_804_p2 or ap_const_lv4_2);
    p_cast119_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_306_p2),6));
    p_cast119_mid1_fu_516_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid1240_fu_510_p2),6));
    p_cast127_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_71_fu_382_p2),6));
    p_cast127_mid1_fu_720_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid1218_fu_714_p2),6));
    p_mid1218_fu_714_p2 <= std_logic_vector(unsigned(zext_ln125_2_fu_710_p1) + unsigned(select_ln117));
    p_mid1220_fu_724_p2 <= std_logic_vector(unsigned(p_cast127_mid1_fu_720_p1) + unsigned(ap_const_lv6_3F));
    p_mid1240_fu_510_p2 <= std_logic_vector(unsigned(zext_ln123_1_fu_506_p1) + unsigned(select_ln117_2));
    p_mid1242_fu_520_p2 <= std_logic_vector(unsigned(p_cast119_mid1_fu_516_p1) + unsigned(ap_const_lv6_3F));
    p_mid1244_fu_538_p2 <= std_logic_vector(unsigned(p_shl26_cast_mid1_fu_534_p1) - unsigned(zext_ln123_1_fu_506_p1));
    p_shl1_fu_322_p3 <= (ap_sig_allocacmp_i_2 & ap_const_lv2_0);
    p_shl26_cast_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl1_fu_322_p3),5));
    p_shl26_cast_mid1_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl26_mid1_fu_526_p3),5));
    p_shl26_mid1_fu_526_p3 <= (add_ln123_fu_478_p2 & ap_const_lv2_0);
    s_V_16_out <= lhs_fu_132;

    s_V_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln123_reg_1148_pp0_iter1_reg, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln123_reg_1148_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            s_V_16_out_ap_vld <= ap_const_logic_1;
        else 
            s_V_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    s_V_fu_1069_p1 <= grp_fu_1096_p3;
    select_ln123_1_fu_498_p3 <= 
        ap_const_lv4_0 when (icmp_ln125_fu_484_p2(0) = '1') else 
        ap_sig_allocacmp_k_load;
    select_ln123_2_fu_550_p3 <= 
        cmp24_i427_not_mid1_fu_544_p2 when (icmp_ln125_fu_484_p2(0) = '1') else 
        cmp24_i427_not_fu_340_p2;
    select_ln123_3_fu_564_p3 <= 
        cmp25_i429_not_mid1_fu_558_p2 when (icmp_ln125_fu_484_p2(0) = '1') else 
        cmp25_i429_not_fu_346_p2;
    select_ln123_4_fu_598_p3 <= 
        sub_ln132_1_fu_592_p2 when (icmp_ln125_fu_484_p2(0) = '1') else 
        sub_ln132_fu_372_p2;
    select_ln123_5_fu_606_p3 <= 
        p_mid1244_fu_538_p2 when (icmp_ln125_fu_484_p2(0) = '1') else 
        empty_70_fu_334_p2;
    select_ln123_6_fu_642_p3 <= 
        brmerge88_mid1266_fu_636_p2 when (icmp_ln125_fu_484_p2(0) = '1') else 
        brmerge88_fu_422_p2;
    select_ln123_7_fu_676_p3 <= 
        add_ln123_fu_478_p2 when (icmp_ln125_fu_484_p2(0) = '1') else 
        ap_sig_allocacmp_i_2;
    select_ln123_8_fu_830_p3 <= 
        tmp_s_fu_810_p4 when (icmp_ln125_fu_484_p2(0) = '1') else 
        tmp_5_fu_820_p4;
    select_ln123_fu_490_p3 <= 
        ap_const_lv2_0 when (icmp_ln125_fu_484_p2(0) = '1') else 
        ap_sig_allocacmp_j_3;
    select_ln125_1_fu_698_p3 <= 
        select_ln123_fu_490_p3 when (or_ln123_fu_670_p2(0) = '1') else 
        add_ln125_fu_684_p2;
    select_ln125_2_fu_760_p3 <= 
        select_ln123_6_fu_642_p3 when (or_ln123_fu_670_p2(0) = '1') else 
        brmerge88_mid1_fu_754_p2;
    select_ln125_3_fu_848_p3 <= 
        select_ln123_8_fu_830_p3 when (or_ln123_fu_670_p2(0) = '1') else 
        tmp_6_fu_838_p4;
    select_ln125_4_fu_975_p3 <= 
        ap_const_lv5_1 when (icmp_ln125_fu_484_p2(0) = '1') else 
        add_ln125_1_fu_969_p2;
    select_ln125_fu_690_p3 <= 
        select_ln123_1_fu_498_p3 when (or_ln123_fu_670_p2(0) = '1') else 
        ap_const_lv4_0;
        sext_ln123_fu_614_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln123_5_fu_606_p3),9));

        sext_ln132_1_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln3_fu_428_p3),13));

        sext_ln132_2_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln132_fu_440_p2),14));

        sext_ln132_3_fu_588_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln132_2_mid1_fu_580_p3),15));

        sext_ln132_4_fu_776_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln132_mid1_fu_768_p3),13));

        sext_ln132_5_fu_786_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln132_3_fu_780_p2),14));

        sext_ln132_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln132_2_fu_360_p3),15));

    shl_ln132_1_fu_352_p3 <= (empty_69_fu_316_p2 & ap_const_lv9_0);
    shl_ln132_1_mid1_fu_572_p3 <= (p_mid1242_fu_520_p2 & ap_const_lv9_0);
    shl_ln132_2_fu_360_p3 <= (empty_69_fu_316_p2 & ap_const_lv6_0);
    shl_ln132_2_mid1_fu_580_p3 <= (p_mid1242_fu_520_p2 & ap_const_lv6_0);
    shl_ln132_fu_804_p2 <= std_logic_vector(shift_left(unsigned(select_ln125_fu_690_p3),to_integer(unsigned('0' & ap_const_lv4_1(4-1 downto 0)))));
    shl_ln132_mid1_fu_768_p3 <= (p_mid1220_fu_724_p2 & ap_const_lv4_0);
    shl_ln3_fu_428_p3 <= (empty_72_fu_392_p2 & ap_const_lv4_0);
    sub_ln132_1_fu_592_p2 <= std_logic_vector(unsigned(shl_ln132_1_mid1_fu_572_p3) - unsigned(sext_ln132_3_fu_588_p1));
    sub_ln132_fu_372_p2 <= std_logic_vector(unsigned(shl_ln132_1_fu_352_p3) - unsigned(sext_ln132_fu_368_p1));
    tmp28_fu_410_p2 <= (cmp27_i431_not_fu_398_p2 or cmp25_i429_not_fu_346_p2);
    tmp28_mid1262_fu_624_p2 <= (cmp27_i431_not_mid1258 or cmp25_i429_not_mid1_fu_558_p2);
    tmp28_mid1_fu_742_p2 <= (select_ln123_3_fu_564_p3 or cmp27_i431_not_mid1_fu_730_p2);
    tmp29_fu_416_p2 <= (cmp29_i433_not_fu_404_p2 or cmp24_i427_not_fu_340_p2);
    tmp29_mid1264_fu_630_p2 <= (cmp29_i433_not_mid1260 or cmp24_i427_not_mid1_fu_544_p2);
    tmp29_mid1_fu_748_p2 <= (select_ln123_2_fu_550_p3 or cmp29_i433_not_mid1_fu_736_p2);
    tmp_5_fu_820_p4 <= add_ln132_1_fu_454_p2(14 downto 4);
    tmp_6_fu_838_p4 <= add_ln132_4_fu_794_p2(14 downto 4);
    tmp_7_fu_869_p4 <= select_ln125_fu_690_p3(2 downto 1);
    tmp_8_fu_918_p4 <= or_ln132_fu_912_p2(3 downto 1);
    tmp_9_fu_1052_p1 <= grp_fu_1087_p3;
    tmp_9_fu_1052_p4 <= tmp_9_fu_1052_p1(25 downto 10);
    tmp_fu_656_p3 <= ap_sig_allocacmp_k_load(3 downto 3);
    tmp_s_fu_810_p4 <= add_ln132_2_fu_650_p2(14 downto 4);
    trunc_ln132_fu_800_p1 <= select_ln125_fu_690_p3(3 - 1 downto 0);
    val_V_15_fu_1008_p3 <= 
        ap_const_lv16_0 when (select_ln125_2_reg_1152(0) = '1') else 
        d_q1;
    val_V_16_fu_1023_p3 <= 
        ap_const_lv16_0 when (select_ln125_2_reg_1152(0) = '1') else 
        d_q0;
    xor_ln127_fu_664_p2 <= (tmp_fu_656_p3 xor ap_const_lv1_1);
    zext_ln115_cast_fu_259_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln115),9));
    zext_ln123_1_fu_506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln123_fu_478_p2),5));
    zext_ln123_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_2),5));
    zext_ln125_1_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln125_1_fu_698_p3),7));
    zext_ln125_2_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln125_fu_684_p2),5));
    zext_ln125_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_3),5));
    zext_ln1271_3_fu_1030_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln133_4_reg_1173),64));
    zext_ln1271_fu_907_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln133_1_fu_901_p2),64));
    zext_ln132_1_fu_936_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln132_1_fu_928_p3),64));
    zext_ln132_2_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln132_2_fu_446_p1),15));
    zext_ln132_3_cast_cast_fu_255_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln132_3_cast_fu_251_p1),15));
        zext_ln132_3_cast_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(zext_ln132_3),14));

    zext_ln132_4_fu_790_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln132_5_fu_786_p1),15));
    zext_ln132_fu_864_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln5_fu_856_p3),64));
    zext_ln133_1_fu_897_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln133_fu_891_p2),9));
    zext_ln133_2_fu_953_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln133_3_fu_947_p2),9));
    zext_ln133_fu_887_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln133_7_fu_879_p3),7));
end behav;
