// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module denoiser_top_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln66,
        select_ln68_2,
        select_ln68,
        zext_ln66,
        cmp27_i_not_mid1115,
        cmp29_i_not_mid1117,
        sext_ln83_4,
        d_address0,
        d_ce0,
        d_q0,
        d_address1,
        d_ce1,
        d_q1,
        s_V_15_out,
        s_V_15_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] sext_ln66;
input  [3:0] select_ln68_2;
input  [3:0] select_ln68;
input  [7:0] zext_ln66;
input  [0:0] cmp27_i_not_mid1115;
input  [0:0] cmp29_i_not_mid1117;
input  [12:0] sext_ln83_4;
output  [13:0] d_address0;
output   d_ce0;
input  [15:0] d_q0;
output  [13:0] d_address1;
output   d_ce1;
input  [15:0] d_q1;
output  [15:0] s_V_15_out;
output   s_V_15_out_ap_vld;

reg ap_idle;
reg d_ce0;
reg d_ce1;
reg s_V_15_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln74_reg_1158;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [8:0] conv2_kernel_V_address0;
reg    conv2_kernel_V_ce0;
wire  signed [10:0] conv2_kernel_V_q0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln74_fu_464_p2;
reg   [0:0] icmp_ln74_reg_1158_pp0_iter1_reg;
wire   [0:0] select_ln76_2_fu_780_p3;
reg   [0:0] select_ln76_2_reg_1162;
wire   [8:0] add_ln84_3_fu_967_p2;
reg   [8:0] add_ln84_3_reg_1183;
wire    ap_block_pp0_stage1_11001;
wire   [15:0] val_V_21_fu_1033_p3;
reg  signed [15:0] val_V_21_reg_1198;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln83_fu_880_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1271_3_fu_909_p1;
wire   [63:0] zext_ln83_1_fu_938_p1;
wire   [63:0] zext_ln1271_fu_1040_p1;
wire    ap_block_pp0_stage1;
reg   [15:0] lhs_fu_132;
wire  signed [15:0] sext_ln66_cast_fu_259_p1;
reg   [15:0] ap_sig_allocacmp_lhs_load_4;
wire    ap_loop_init;
reg   [2:0] k_fu_136;
wire   [2:0] add_ln78_fu_973_p2;
reg   [2:0] ap_sig_allocacmp_k_load;
reg   [1:0] j_1_fu_140;
wire   [1:0] select_ln76_1_fu_714_p3;
reg   [1:0] ap_sig_allocacmp_j;
reg   [3:0] indvar_flatten77_fu_144;
wire   [3:0] select_ln76_4_fu_985_p3;
reg   [3:0] ap_sig_allocacmp_indvar_flatten77_load;
reg   [1:0] i_1_fu_148;
wire   [1:0] select_ln74_7_fu_692_p3;
reg   [1:0] ap_sig_allocacmp_i;
reg   [4:0] indvar_flatten137_fu_152;
wire   [4:0] add_ln74_2_fu_470_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten137_load;
wire    ap_block_pp0_stage1_01001;
wire   [3:0] zext_ln74_1_fu_306_p1;
wire   [3:0] empty_fu_310_p2;
wire   [4:0] p_cast82_fu_316_p1;
wire   [3:0] p_shl_fu_326_p3;
wire   [4:0] p_shl14_cast_fu_334_p1;
wire   [4:0] zext_ln74_fu_302_p1;
wire   [4:0] empty_74_fu_320_p2;
wire   [8:0] shl_ln83_2_fu_364_p3;
wire   [11:0] shl_ln83_1_fu_356_p3;
wire  signed [11:0] sext_ln83_fu_372_p1;
wire  signed [11:0] sub_ln83_fu_376_p2;
wire   [3:0] zext_ln76_fu_386_p1;
wire   [3:0] empty_76_fu_390_p2;
wire   [4:0] p_cast123_fu_396_p1;
wire   [4:0] empty_77_fu_400_p2;
wire   [0:0] cmp25_i228_not_fu_350_p2;
wire   [0:0] cmp27_i_not_fu_406_p2;
wire   [0:0] cmp24_i_not_fu_344_p2;
wire   [0:0] cmp29_i_not_fu_412_p2;
wire   [0:0] tmp14_fu_424_p2;
wire   [0:0] tmp13_fu_418_p2;
wire   [7:0] shl_ln2_fu_436_p3;
wire  signed [12:0] sext_ln83_1_fu_444_p1;
wire   [12:0] add_ln83_fu_448_p2;
wire  signed [13:0] sext_ln83_2_fu_454_p1;
wire  signed [13:0] sext_ln76_fu_382_p1;
wire   [0:0] icmp_ln76_fu_488_p2;
wire   [1:0] add_ln74_fu_482_p2;
wire   [3:0] zext_ln74_3_fu_514_p1;
wire   [3:0] p_mid195_fu_518_p2;
wire   [4:0] p_cast82_mid1_fu_524_p1;
wire   [3:0] p_shl14_mid1_fu_534_p3;
wire   [4:0] p_shl14_cast_mid1_fu_542_p1;
wire   [4:0] zext_ln74_2_fu_510_p1;
wire   [0:0] cmp24_i_not_mid1_fu_552_p2;
wire   [4:0] p_mid197_fu_528_p2;
wire   [0:0] cmp25_i228_not_mid1_fu_566_p2;
wire   [8:0] shl_ln83_2_mid1_fu_588_p3;
wire   [11:0] shl_ln83_1_mid1_fu_580_p3;
wire  signed [11:0] sext_ln83_3_fu_596_p1;
wire  signed [11:0] sub_ln83_1_fu_600_p2;
wire   [11:0] select_ln74_4_fu_610_p3;
wire   [4:0] p_mid199_fu_546_p2;
wire   [4:0] empty_75_fu_338_p2;
wire   [4:0] select_ln74_5_fu_622_p3;
wire  signed [8:0] sext_ln74_1_fu_630_p1;
wire   [8:0] zext_ln66_cast_fu_255_p1;
wire   [0:0] tmp14_mid1121_fu_646_p2;
wire   [0:0] tmp13_mid1119_fu_640_p2;
wire   [0:0] brmerge78_mid1123_fu_652_p2;
wire   [0:0] brmerge78_fu_430_p2;
wire  signed [13:0] sext_ln83_4_cast_fu_251_p1;
wire  signed [13:0] sext_ln76_1_fu_606_p1;
wire   [0:0] tmp_fu_672_p3;
wire   [0:0] xor_ln78_fu_680_p2;
wire   [1:0] select_ln74_fu_494_p3;
wire   [0:0] or_ln74_fu_686_p2;
wire   [2:0] select_ln74_1_fu_502_p3;
wire   [1:0] add_ln76_fu_700_p2;
wire   [3:0] zext_ln76_3_fu_730_p1;
wire   [3:0] p_mid173_fu_734_p2;
wire   [4:0] p_cast123_mid1_fu_740_p1;
wire   [4:0] p_mid175_fu_744_p2;
wire   [0:0] select_ln74_3_fu_572_p3;
wire   [0:0] cmp27_i_not_mid1_fu_750_p2;
wire   [0:0] select_ln74_2_fu_558_p3;
wire   [0:0] cmp29_i_not_mid1_fu_756_p2;
wire   [0:0] tmp14_mid1_fu_768_p2;
wire   [0:0] tmp13_mid1_fu_762_p2;
wire   [0:0] select_ln74_6_fu_658_p3;
wire   [0:0] brmerge78_mid1_fu_774_p2;
wire   [7:0] shl_ln83_mid1_fu_788_p3;
wire  signed [12:0] sext_ln83_5_fu_796_p1;
wire   [12:0] add_ln83_3_fu_800_p2;
wire  signed [13:0] sext_ln83_6_fu_806_p1;
wire  signed [13:0] sext_ln74_fu_618_p1;
wire   [2:0] select_ln76_fu_706_p3;
wire   [13:0] add_ln83_2_fu_666_p2;
wire   [13:0] add_ln83_1_fu_458_p2;
wire   [10:0] tmp_s_fu_826_p4;
wire   [10:0] tmp_10_fu_836_p4;
wire   [13:0] add_ln83_4_fu_810_p2;
wire   [10:0] select_ln74_8_fu_846_p3;
wire   [10:0] tmp_11_fu_854_p4;
wire   [10:0] select_ln76_3_fu_864_p3;
wire   [1:0] trunc_ln83_fu_816_p1;
wire   [12:0] lshr_ln4_fu_872_p3;
wire   [4:0] zext_ln76_2_fu_726_p1;
wire   [4:0] add_ln84_7_fu_885_p3;
wire   [4:0] add_ln84_fu_893_p2;
wire   [8:0] zext_ln84_fu_899_p1;
wire   [8:0] add_ln74_1_fu_634_p2;
wire   [8:0] add_ln84_1_fu_903_p2;
wire   [2:0] shl_ln83_fu_820_p2;
wire   [2:0] or_ln83_fu_914_p2;
wire   [1:0] tmp_12_fu_920_p4;
wire   [12:0] lshr_ln83_1_fu_930_p3;
wire   [4:0] or_ln84_fu_943_p2;
wire   [5:0] or_ln1_fu_949_p3;
wire   [5:0] zext_ln76_1_fu_722_p1;
wire   [5:0] add_ln84_2_fu_957_p2;
wire   [8:0] zext_ln84_1_fu_963_p1;
wire   [3:0] add_ln76_1_fu_979_p2;
wire  signed [15:0] val_V_20_fu_1018_p3;
wire  signed [25:0] tmp_13_fu_1062_p1;
wire   [25:0] grp_fu_1097_p3;
wire   [15:0] tmp_13_fu_1062_p4;
wire  signed [25:0] s_V_fu_1079_p1;
wire   [25:0] grp_fu_1106_p3;
wire   [25:0] grp_fu_1097_p2;
wire   [25:0] grp_fu_1106_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

denoiser_top_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2_conv2_kernel_V_ROM_AUTO_1R #(
    .DataWidth( 11 ),
    .AddressRange( 288 ),
    .AddressWidth( 9 ))
conv2_kernel_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv2_kernel_V_address0),
    .ce0(conv2_kernel_V_ce0),
    .q0(conv2_kernel_V_q0)
);

denoiser_top_mac_muladd_11s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_11s_16s_26ns_26_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv2_kernel_V_q0),
    .din1(val_V_20_fu_1018_p3),
    .din2(grp_fu_1097_p2),
    .ce(1'b1),
    .dout(grp_fu_1097_p3)
);

denoiser_top_mac_muladd_11s_16s_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_11s_16s_26ns_26_4_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv2_kernel_V_q0),
    .din1(val_V_21_reg_1198),
    .din2(grp_fu_1106_p2),
    .ce(1'b1),
    .dout(grp_fu_1106_p3)
);

denoiser_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln74_fu_464_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_148 <= select_ln74_7_fu_692_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_148 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln74_fu_464_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten137_fu_152 <= add_ln74_2_fu_470_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten137_fu_152 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln74_fu_464_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten77_fu_144 <= select_ln76_4_fu_985_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten77_fu_144 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln74_fu_464_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_1_fu_140 <= select_ln76_1_fu_714_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            j_1_fu_140 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln74_fu_464_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_136 <= add_ln78_fu_973_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_136 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        lhs_fu_132 <= sext_ln66_cast_fu_259_p1;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        lhs_fu_132 <= {{s_V_fu_1079_p1[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln74_fu_464_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln84_3_reg_1183 <= add_ln84_3_fu_967_p2;
        select_ln76_2_reg_1162 <= select_ln76_2_fu_780_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln74_reg_1158 <= icmp_ln74_fu_464_p2;
        icmp_ln74_reg_1158_pp0_iter1_reg <= icmp_ln74_reg_1158;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln74_reg_1158 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        val_V_21_reg_1198 <= val_V_21_fu_1033_p3;
    end
end

always @ (*) begin
    if (((icmp_ln74_reg_1158 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 2'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten137_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten137_load = indvar_flatten137_fu_152;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten77_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten77_load = indvar_flatten77_fu_144;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j = 2'd0;
    end else begin
        ap_sig_allocacmp_j = j_1_fu_140;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_load = 3'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_lhs_load_4 = {{s_V_fu_1079_p1[25:10]}};
    end else begin
        ap_sig_allocacmp_lhs_load_4 = lhs_fu_132;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            conv2_kernel_V_address0 = zext_ln1271_fu_1040_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            conv2_kernel_V_address0 = zext_ln1271_3_fu_909_p1;
        end else begin
            conv2_kernel_V_address0 = 'bx;
        end
    end else begin
        conv2_kernel_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        conv2_kernel_V_ce0 = 1'b1;
    end else begin
        conv2_kernel_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_ce0 = 1'b1;
    end else begin
        d_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_ce1 = 1'b1;
    end else begin
        d_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln74_reg_1158_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s_V_15_out_ap_vld = 1'b1;
    end else begin
        s_V_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln74_1_fu_634_p2 = ($signed(sext_ln74_1_fu_630_p1) + $signed(zext_ln66_cast_fu_255_p1));

assign add_ln74_2_fu_470_p2 = (ap_sig_allocacmp_indvar_flatten137_load + 5'd1);

assign add_ln74_fu_482_p2 = (ap_sig_allocacmp_i + 2'd1);

assign add_ln76_1_fu_979_p2 = (ap_sig_allocacmp_indvar_flatten77_load + 4'd1);

assign add_ln76_fu_700_p2 = (select_ln74_fu_494_p3 + 2'd1);

assign add_ln78_fu_973_p2 = (select_ln76_fu_706_p3 + 3'd2);

assign add_ln83_1_fu_458_p2 = ($signed(sext_ln83_2_fu_454_p1) + $signed(sext_ln76_fu_382_p1));

assign add_ln83_2_fu_666_p2 = ($signed(sext_ln83_4_cast_fu_251_p1) + $signed(sext_ln76_1_fu_606_p1));

assign add_ln83_3_fu_800_p2 = ($signed(sext_ln83_5_fu_796_p1) + $signed(13'd4352));

assign add_ln83_4_fu_810_p2 = ($signed(sext_ln83_6_fu_806_p1) + $signed(sext_ln74_fu_618_p1));

assign add_ln83_fu_448_p2 = ($signed(sext_ln83_1_fu_444_p1) + $signed(13'd4352));

assign add_ln84_1_fu_903_p2 = (zext_ln84_fu_899_p1 + add_ln74_1_fu_634_p2);

assign add_ln84_2_fu_957_p2 = (or_ln1_fu_949_p3 + zext_ln76_1_fu_722_p1);

assign add_ln84_3_fu_967_p2 = (zext_ln84_1_fu_963_p1 + add_ln74_1_fu_634_p2);

assign add_ln84_7_fu_885_p3 = {{trunc_ln83_fu_816_p1}, {select_ln76_fu_706_p3}};

assign add_ln84_fu_893_p2 = (zext_ln76_2_fu_726_p1 + add_ln84_7_fu_885_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign brmerge78_fu_430_p2 = (tmp14_fu_424_p2 | tmp13_fu_418_p2);

assign brmerge78_mid1123_fu_652_p2 = (tmp14_mid1121_fu_646_p2 | tmp13_mid1119_fu_640_p2);

assign brmerge78_mid1_fu_774_p2 = (tmp14_mid1_fu_768_p2 | tmp13_mid1_fu_762_p2);

assign cmp24_i_not_fu_344_p2 = ((empty_fu_310_p2 == 4'd0) ? 1'b1 : 1'b0);

assign cmp24_i_not_mid1_fu_552_p2 = ((p_mid195_fu_518_p2 == 4'd0) ? 1'b1 : 1'b0);

assign cmp25_i228_not_fu_350_p2 = (($signed(empty_74_fu_320_p2) > $signed(5'd13)) ? 1'b1 : 1'b0);

assign cmp25_i228_not_mid1_fu_566_p2 = (($signed(p_mid197_fu_528_p2) > $signed(5'd13)) ? 1'b1 : 1'b0);

assign cmp27_i_not_fu_406_p2 = ((empty_76_fu_390_p2 == 4'd0) ? 1'b1 : 1'b0);

assign cmp27_i_not_mid1_fu_750_p2 = ((p_mid173_fu_734_p2 == 4'd0) ? 1'b1 : 1'b0);

assign cmp29_i_not_fu_412_p2 = (($signed(empty_77_fu_400_p2) > $signed(5'd13)) ? 1'b1 : 1'b0);

assign cmp29_i_not_mid1_fu_756_p2 = (($signed(p_mid175_fu_744_p2) > $signed(5'd13)) ? 1'b1 : 1'b0);

assign d_address0 = zext_ln83_1_fu_938_p1;

assign d_address1 = zext_ln83_fu_880_p1;

assign empty_74_fu_320_p2 = ($signed(p_cast82_fu_316_p1) + $signed(5'd31));

assign empty_75_fu_338_p2 = (p_shl14_cast_fu_334_p1 - zext_ln74_fu_302_p1);

assign empty_76_fu_390_p2 = (zext_ln76_fu_386_p1 + select_ln68);

assign empty_77_fu_400_p2 = ($signed(p_cast123_fu_396_p1) + $signed(5'd31));

assign empty_fu_310_p2 = (zext_ln74_1_fu_306_p1 + select_ln68_2);

assign grp_fu_1097_p2 = {{ap_sig_allocacmp_lhs_load_4}, {10'd0}};

assign grp_fu_1106_p2 = {{tmp_13_fu_1062_p4}, {10'd0}};

assign icmp_ln74_fu_464_p2 = ((ap_sig_allocacmp_indvar_flatten137_load == 5'd18) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_488_p2 = ((ap_sig_allocacmp_indvar_flatten77_load == 4'd6) ? 1'b1 : 1'b0);

assign lshr_ln4_fu_872_p3 = {{select_ln76_3_fu_864_p3}, {trunc_ln83_fu_816_p1}};

assign lshr_ln83_1_fu_930_p3 = {{select_ln76_3_fu_864_p3}, {tmp_12_fu_920_p4}};

assign or_ln1_fu_949_p3 = {{1'd0}, {or_ln84_fu_943_p2}};

assign or_ln74_fu_686_p2 = (xor_ln78_fu_680_p2 | icmp_ln76_fu_488_p2);

assign or_ln83_fu_914_p2 = (shl_ln83_fu_820_p2 | 3'd2);

assign or_ln84_fu_943_p2 = (5'd9 | add_ln84_7_fu_885_p3);

assign p_cast123_fu_396_p1 = empty_76_fu_390_p2;

assign p_cast123_mid1_fu_740_p1 = p_mid173_fu_734_p2;

assign p_cast82_fu_316_p1 = empty_fu_310_p2;

assign p_cast82_mid1_fu_524_p1 = p_mid195_fu_518_p2;

assign p_mid173_fu_734_p2 = (zext_ln76_3_fu_730_p1 + select_ln68);

assign p_mid175_fu_744_p2 = ($signed(p_cast123_mid1_fu_740_p1) + $signed(5'd31));

assign p_mid195_fu_518_p2 = (zext_ln74_3_fu_514_p1 + select_ln68_2);

assign p_mid197_fu_528_p2 = ($signed(p_cast82_mid1_fu_524_p1) + $signed(5'd31));

assign p_mid199_fu_546_p2 = (p_shl14_cast_mid1_fu_542_p1 - zext_ln74_2_fu_510_p1);

assign p_shl14_cast_fu_334_p1 = p_shl_fu_326_p3;

assign p_shl14_cast_mid1_fu_542_p1 = p_shl14_mid1_fu_534_p3;

assign p_shl14_mid1_fu_534_p3 = {{add_ln74_fu_482_p2}, {2'd0}};

assign p_shl_fu_326_p3 = {{ap_sig_allocacmp_i}, {2'd0}};

assign s_V_15_out = lhs_fu_132;

assign s_V_fu_1079_p1 = grp_fu_1106_p3;

assign select_ln74_1_fu_502_p3 = ((icmp_ln76_fu_488_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_k_load);

assign select_ln74_2_fu_558_p3 = ((icmp_ln76_fu_488_p2[0:0] == 1'b1) ? cmp24_i_not_mid1_fu_552_p2 : cmp24_i_not_fu_344_p2);

assign select_ln74_3_fu_572_p3 = ((icmp_ln76_fu_488_p2[0:0] == 1'b1) ? cmp25_i228_not_mid1_fu_566_p2 : cmp25_i228_not_fu_350_p2);

assign select_ln74_4_fu_610_p3 = ((icmp_ln76_fu_488_p2[0:0] == 1'b1) ? sub_ln83_1_fu_600_p2 : sub_ln83_fu_376_p2);

assign select_ln74_5_fu_622_p3 = ((icmp_ln76_fu_488_p2[0:0] == 1'b1) ? p_mid199_fu_546_p2 : empty_75_fu_338_p2);

assign select_ln74_6_fu_658_p3 = ((icmp_ln76_fu_488_p2[0:0] == 1'b1) ? brmerge78_mid1123_fu_652_p2 : brmerge78_fu_430_p2);

assign select_ln74_7_fu_692_p3 = ((icmp_ln76_fu_488_p2[0:0] == 1'b1) ? add_ln74_fu_482_p2 : ap_sig_allocacmp_i);

assign select_ln74_8_fu_846_p3 = ((icmp_ln76_fu_488_p2[0:0] == 1'b1) ? tmp_s_fu_826_p4 : tmp_10_fu_836_p4);

assign select_ln74_fu_494_p3 = ((icmp_ln76_fu_488_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j);

assign select_ln76_1_fu_714_p3 = ((or_ln74_fu_686_p2[0:0] == 1'b1) ? select_ln74_fu_494_p3 : add_ln76_fu_700_p2);

assign select_ln76_2_fu_780_p3 = ((or_ln74_fu_686_p2[0:0] == 1'b1) ? select_ln74_6_fu_658_p3 : brmerge78_mid1_fu_774_p2);

assign select_ln76_3_fu_864_p3 = ((or_ln74_fu_686_p2[0:0] == 1'b1) ? select_ln74_8_fu_846_p3 : tmp_11_fu_854_p4);

assign select_ln76_4_fu_985_p3 = ((icmp_ln76_fu_488_p2[0:0] == 1'b1) ? 4'd1 : add_ln76_1_fu_979_p2);

assign select_ln76_fu_706_p3 = ((or_ln74_fu_686_p2[0:0] == 1'b1) ? select_ln74_1_fu_502_p3 : 3'd0);

assign sext_ln66_cast_fu_259_p1 = $signed(sext_ln66);

assign sext_ln74_1_fu_630_p1 = $signed(select_ln74_5_fu_622_p3);

assign sext_ln74_fu_618_p1 = $signed(select_ln74_4_fu_610_p3);

assign sext_ln76_1_fu_606_p1 = sub_ln83_1_fu_600_p2;

assign sext_ln76_fu_382_p1 = sub_ln83_fu_376_p2;

assign sext_ln83_1_fu_444_p1 = $signed(shl_ln2_fu_436_p3);

assign sext_ln83_2_fu_454_p1 = $signed(add_ln83_fu_448_p2);

assign sext_ln83_3_fu_596_p1 = $signed(shl_ln83_2_mid1_fu_588_p3);

assign sext_ln83_4_cast_fu_251_p1 = $signed(sext_ln83_4);

assign sext_ln83_5_fu_796_p1 = $signed(shl_ln83_mid1_fu_788_p3);

assign sext_ln83_6_fu_806_p1 = $signed(add_ln83_3_fu_800_p2);

assign sext_ln83_fu_372_p1 = $signed(shl_ln83_2_fu_364_p3);

assign shl_ln2_fu_436_p3 = {{empty_77_fu_400_p2}, {3'd0}};

assign shl_ln83_1_fu_356_p3 = {{empty_74_fu_320_p2}, {7'd0}};

assign shl_ln83_1_mid1_fu_580_p3 = {{p_mid197_fu_528_p2}, {7'd0}};

assign shl_ln83_2_fu_364_p3 = {{empty_74_fu_320_p2}, {4'd0}};

assign shl_ln83_2_mid1_fu_588_p3 = {{p_mid197_fu_528_p2}, {4'd0}};

assign shl_ln83_fu_820_p2 = select_ln76_fu_706_p3 << 3'd1;

assign shl_ln83_mid1_fu_788_p3 = {{p_mid175_fu_744_p2}, {3'd0}};

assign sub_ln83_1_fu_600_p2 = ($signed(shl_ln83_1_mid1_fu_580_p3) - $signed(sext_ln83_3_fu_596_p1));

assign sub_ln83_fu_376_p2 = ($signed(shl_ln83_1_fu_356_p3) - $signed(sext_ln83_fu_372_p1));

assign tmp13_fu_418_p2 = (cmp27_i_not_fu_406_p2 | cmp25_i228_not_fu_350_p2);

assign tmp13_mid1119_fu_640_p2 = (cmp27_i_not_mid1115 | cmp25_i228_not_mid1_fu_566_p2);

assign tmp13_mid1_fu_762_p2 = (select_ln74_3_fu_572_p3 | cmp27_i_not_mid1_fu_750_p2);

assign tmp14_fu_424_p2 = (cmp29_i_not_fu_412_p2 | cmp24_i_not_fu_344_p2);

assign tmp14_mid1121_fu_646_p2 = (cmp29_i_not_mid1117 | cmp24_i_not_mid1_fu_552_p2);

assign tmp14_mid1_fu_768_p2 = (select_ln74_2_fu_558_p3 | cmp29_i_not_mid1_fu_756_p2);

assign tmp_10_fu_836_p4 = {{add_ln83_1_fu_458_p2[13:3]}};

assign tmp_11_fu_854_p4 = {{add_ln83_4_fu_810_p2[13:3]}};

assign tmp_12_fu_920_p4 = {{or_ln83_fu_914_p2[2:1]}};

assign tmp_13_fu_1062_p1 = grp_fu_1097_p3;

assign tmp_13_fu_1062_p4 = {{tmp_13_fu_1062_p1[25:10]}};

assign tmp_fu_672_p3 = ap_sig_allocacmp_k_load[32'd2];

assign tmp_s_fu_826_p4 = {{add_ln83_2_fu_666_p2[13:3]}};

assign trunc_ln83_fu_816_p1 = select_ln76_fu_706_p3[1:0];

assign val_V_20_fu_1018_p3 = ((select_ln76_2_reg_1162[0:0] == 1'b1) ? 16'd0 : d_q1);

assign val_V_21_fu_1033_p3 = ((select_ln76_2_reg_1162[0:0] == 1'b1) ? 16'd0 : d_q0);

assign xor_ln78_fu_680_p2 = (tmp_fu_672_p3 ^ 1'd1);

assign zext_ln1271_3_fu_909_p1 = add_ln84_1_fu_903_p2;

assign zext_ln1271_fu_1040_p1 = add_ln84_3_reg_1183;

assign zext_ln66_cast_fu_255_p1 = zext_ln66;

assign zext_ln74_1_fu_306_p1 = ap_sig_allocacmp_i;

assign zext_ln74_2_fu_510_p1 = add_ln74_fu_482_p2;

assign zext_ln74_3_fu_514_p1 = add_ln74_fu_482_p2;

assign zext_ln74_fu_302_p1 = ap_sig_allocacmp_i;

assign zext_ln76_1_fu_722_p1 = select_ln76_1_fu_714_p3;

assign zext_ln76_2_fu_726_p1 = select_ln76_1_fu_714_p3;

assign zext_ln76_3_fu_730_p1 = add_ln76_fu_700_p2;

assign zext_ln76_fu_386_p1 = ap_sig_allocacmp_j;

assign zext_ln83_1_fu_938_p1 = lshr_ln83_1_fu_930_p3;

assign zext_ln83_fu_880_p1 = lshr_ln4_fu_872_p3;

assign zext_ln84_1_fu_963_p1 = add_ln84_2_fu_957_p2;

assign zext_ln84_fu_899_p1 = add_ln84_fu_893_p2;

endmodule //denoiser_top_inference_Pipeline_loop_kh_2_loop_kw_2_loop_ic_2
